{"total_count": 24, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/67", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/67/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/67/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/67/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/67", "id": 536252704, "node_id": "MDU6SXNzdWU1MzYyNTI3MDQ=", "number": 67, "title": "Import under Django 3.0 fails", "user": {"login": "peterthomassen", "id": 4242683, "node_id": "MDQ6VXNlcjQyNDI2ODM=", "avatar_url": "https://avatars2.githubusercontent.com/u/4242683?v=4", "gravatar_id": "", "url": "https://api.github.com/users/peterthomassen", "html_url": "https://github.com/peterthomassen", "followers_url": "https://api.github.com/users/peterthomassen/followers", "following_url": "https://api.github.com/users/peterthomassen/following{/other_user}", "gists_url": "https://api.github.com/users/peterthomassen/gists{/gist_id}", "starred_url": "https://api.github.com/users/peterthomassen/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/peterthomassen/subscriptions", "organizations_url": "https://api.github.com/users/peterthomassen/orgs", "repos_url": "https://api.github.com/users/peterthomassen/repos", "events_url": "https://api.github.com/users/peterthomassen/events{/privacy}", "received_events_url": "https://api.github.com/users/peterthomassen/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2019-12-11T09:42:05Z", "updated_at": "2020-01-30T09:23:08Z", "closed_at": "2019-12-11T15:39:41Z", "author_association": "NONE", "active_lock_reason": null, "body": "The [Python 2 compatibility APIs are removed with the Django 3.0 release](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis). Importing from `djcelery_email.utils` thus leads to `ImportError: cannot import name 'six' from 'django.utils'`.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/65", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/65/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/65/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/65/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/65", "id": 478091167, "node_id": "MDU6SXNzdWU0NzgwOTExNjc=", "number": 65, "title": "Woking fail with Celery 4.3", "user": {"login": "endersonmenezes", "id": 11020807, "node_id": "MDQ6VXNlcjExMDIwODA3", "avatar_url": "https://avatars2.githubusercontent.com/u/11020807?v=4", "gravatar_id": "", "url": "https://api.github.com/users/endersonmenezes", "html_url": "https://github.com/endersonmenezes", "followers_url": "https://api.github.com/users/endersonmenezes/followers", "following_url": "https://api.github.com/users/endersonmenezes/following{/other_user}", "gists_url": "https://api.github.com/users/endersonmenezes/gists{/gist_id}", "starred_url": "https://api.github.com/users/endersonmenezes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/endersonmenezes/subscriptions", "organizations_url": "https://api.github.com/users/endersonmenezes/orgs", "repos_url": "https://api.github.com/users/endersonmenezes/repos", "events_url": "https://api.github.com/users/endersonmenezes/events{/privacy}", "received_events_url": "https://api.github.com/users/endersonmenezes/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-08-07T19:04:18Z", "updated_at": "2019-08-07T19:07:11Z", "closed_at": "2019-08-07T19:06:41Z", "author_association": "NONE", "active_lock_reason": null, "body": "I have traceback errors when using a Celery 4.3, any help for this?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/55", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/55/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/55/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/55/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/55", "id": 403731228, "node_id": "MDU6SXNzdWU0MDM3MzEyMjg=", "number": 55, "title": "Django 2.1 support", "user": {"login": "barseghyanartur", "id": 4925587, "node_id": "MDQ6VXNlcjQ5MjU1ODc=", "avatar_url": "https://avatars3.githubusercontent.com/u/4925587?v=4", "gravatar_id": "", "url": "https://api.github.com/users/barseghyanartur", "html_url": "https://github.com/barseghyanartur", "followers_url": "https://api.github.com/users/barseghyanartur/followers", "following_url": "https://api.github.com/users/barseghyanartur/following{/other_user}", "gists_url": "https://api.github.com/users/barseghyanartur/gists{/gist_id}", "starred_url": "https://api.github.com/users/barseghyanartur/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/barseghyanartur/subscriptions", "organizations_url": "https://api.github.com/users/barseghyanartur/orgs", "repos_url": "https://api.github.com/users/barseghyanartur/repos", "events_url": "https://api.github.com/users/barseghyanartur/events{/privacy}", "received_events_url": "https://api.github.com/users/barseghyanartur/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-01-28T09:58:47Z", "updated_at": "2019-05-29T15:55:20Z", "closed_at": "2019-05-29T15:55:20Z", "author_association": "NONE", "active_lock_reason": null, "body": "Is Django 2.1 officially supported? If so, please, update tox, travis and supported Django versions clause. In my tests (clone, install reqs, run tests ``./runtests.py``) it seems to work.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/53", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/53/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/53/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/53/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/53", "id": 325022147, "node_id": "MDU6SXNzdWUzMjUwMjIxNDc=", "number": 53, "title": "django-celery-email 2.0.0 has requirement celery>=4.0,", "user": {"login": "ACPK", "id": 2019893, "node_id": "MDQ6VXNlcjIwMTk4OTM=", "avatar_url": "https://avatars1.githubusercontent.com/u/2019893?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ACPK", "html_url": "https://github.com/ACPK", "followers_url": "https://api.github.com/users/ACPK/followers", "following_url": "https://api.github.com/users/ACPK/following{/other_user}", "gists_url": "https://api.github.com/users/ACPK/gists{/gist_id}", "starred_url": "https://api.github.com/users/ACPK/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ACPK/subscriptions", "organizations_url": "https://api.github.com/users/ACPK/orgs", "repos_url": "https://api.github.com/users/ACPK/repos", "events_url": "https://api.github.com/users/ACPK/events{/privacy}", "received_events_url": "https://api.github.com/users/ACPK/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2018-05-21T18:55:14Z", "updated_at": "2018-05-21T18:55:22Z", "closed_at": "2018-05-21T18:55:22Z", "author_association": "NONE", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/48", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/48/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/48/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/48/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/48", "id": 287065209, "node_id": "MDU6SXNzdWUyODcwNjUyMDk=", "number": 48, "title": "Django 2.0 compatibility?", "user": {"login": "SebJansen", "id": 9006306, "node_id": "MDQ6VXNlcjkwMDYzMDY=", "avatar_url": "https://avatars0.githubusercontent.com/u/9006306?v=4", "gravatar_id": "", "url": "https://api.github.com/users/SebJansen", "html_url": "https://github.com/SebJansen", "followers_url": "https://api.github.com/users/SebJansen/followers", "following_url": "https://api.github.com/users/SebJansen/following{/other_user}", "gists_url": "https://api.github.com/users/SebJansen/gists{/gist_id}", "starred_url": "https://api.github.com/users/SebJansen/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/SebJansen/subscriptions", "organizations_url": "https://api.github.com/users/SebJansen/orgs", "repos_url": "https://api.github.com/users/SebJansen/repos", "events_url": "https://api.github.com/users/SebJansen/events{/privacy}", "received_events_url": "https://api.github.com/users/SebJansen/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2018-01-09T12:01:31Z", "updated_at": "2018-05-22T03:04:37Z", "closed_at": "2018-05-22T03:04:37Z", "author_association": "NONE", "active_lock_reason": null, "body": "  Does it work wit Django 2.0?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/45", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/45/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/45/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/45/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/45", "id": 243603495, "node_id": "MDU6SXNzdWUyNDM2MDM0OTU=", "number": 45, "title": "Attachments:  TypeError(\"a bytes-like object is required, not 'str'\",", "user": {"login": "sidmitra", "id": 108775, "node_id": "MDQ6VXNlcjEwODc3NQ==", "avatar_url": "https://avatars2.githubusercontent.com/u/108775?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sidmitra", "html_url": "https://github.com/sidmitra", "followers_url": "https://api.github.com/users/sidmitra/followers", "following_url": "https://api.github.com/users/sidmitra/following{/other_user}", "gists_url": "https://api.github.com/users/sidmitra/gists{/gist_id}", "starred_url": "https://api.github.com/users/sidmitra/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sidmitra/subscriptions", "organizations_url": "https://api.github.com/users/sidmitra/orgs", "repos_url": "https://api.github.com/users/sidmitra/repos", "events_url": "https://api.github.com/users/sidmitra/events{/privacy}", "received_events_url": "https://api.github.com/users/sidmitra/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-07-18T05:27:17Z", "updated_at": "2017-07-19T16:33:22Z", "closed_at": "2017-07-19T15:49:53Z", "author_association": "NONE", "active_lock_reason": null, "body": "I get the following error when i try to attach files.\r\n```\r\n[2017-07-18 05:15:38,369: WARNING/PoolWorker-4] djcelery_email_send_multiple[c7cebd25-27d8-4b3c-9734-0a6a5729ee4f]: Failed to send email message to ['foobar@example.com'], retrying. (TypeError(\"a bytes-like object is required, not 'str'\",))\r\n```\r\n\r\nI've tried a number of ways to attach files. But essentially it's this\r\n```\r\ndocfile = default_storage.open(attachment['file_path'], 'r')\r\nif docfile:\r\n    message.attach(attachment['name'], docfile.read())\r\n```\r\nI have to do all the default_storage stuff because my files live on S3 and I need to open it via the storage and then call read().  But i don't think it matters what storage i use. Also docfile.read() returns a bytes string. Note i'm using `python 3.6+` and version `2.0.0` of the module.\r\n\r\nIt seems calling `attach()` converts it to `str`. After some debugging, it seems to happen here https://github.com/django/django/blob/master/django/core/mail/message.py#L324\r\n\r\n\r\nIt seems [here](https://github.com/pmclanahan/django-celery-email/blob/master/djcelery_email/utils.py#L59) we're expecting contents to be binary(does that mean a bytes string?)  \r\n```\r\nfilename, binary_contents, mimetype = attachment\r\ncontents = base64.b64encode(binary_contents).decode('ascii')\r\n```\r\nThis is where i get the TypeError.  Note my attached files are txt. \r\n\r\nThere could probably be something obvious i'm missing here, on how to attach files.\r\nI will explore some more(and try other files) and add some more info later. But any help would be greatly appreciated.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/43", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/43/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/43/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/43/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/43", "id": 232866447, "node_id": "MDU6SXNzdWUyMzI4NjY0NDc=", "number": 43, "title": "Celery 4.x support", "user": {"login": "barseghyanartur", "id": 4925587, "node_id": "MDQ6VXNlcjQ5MjU1ODc=", "avatar_url": "https://avatars3.githubusercontent.com/u/4925587?v=4", "gravatar_id": "", "url": "https://api.github.com/users/barseghyanartur", "html_url": "https://github.com/barseghyanartur", "followers_url": "https://api.github.com/users/barseghyanartur/followers", "following_url": "https://api.github.com/users/barseghyanartur/following{/other_user}", "gists_url": "https://api.github.com/users/barseghyanartur/gists{/gist_id}", "starred_url": "https://api.github.com/users/barseghyanartur/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/barseghyanartur/subscriptions", "organizations_url": "https://api.github.com/users/barseghyanartur/orgs", "repos_url": "https://api.github.com/users/barseghyanartur/repos", "events_url": "https://api.github.com/users/barseghyanartur/events{/privacy}", "received_events_url": "https://api.github.com/users/barseghyanartur/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 12, "created_at": "2017-06-01T12:42:51Z", "updated_at": "2017-07-10T20:00:27Z", "closed_at": "2017-07-10T20:00:27Z", "author_association": "NONE", "active_lock_reason": null, "body": "Are there plans for supporting Celery 4.x in nearest future? If so, could you give an estimation?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/42", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/42/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/42/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/42/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/42", "id": 232011404, "node_id": "MDU6SXNzdWUyMzIwMTE0MDQ=", "number": 42, "title": "Does it work with JSON serialisation?", "user": {"login": "barseghyanartur", "id": 4925587, "node_id": "MDQ6VXNlcjQ5MjU1ODc=", "avatar_url": "https://avatars3.githubusercontent.com/u/4925587?v=4", "gravatar_id": "", "url": "https://api.github.com/users/barseghyanartur", "html_url": "https://github.com/barseghyanartur", "followers_url": "https://api.github.com/users/barseghyanartur/followers", "following_url": "https://api.github.com/users/barseghyanartur/following{/other_user}", "gists_url": "https://api.github.com/users/barseghyanartur/gists{/gist_id}", "starred_url": "https://api.github.com/users/barseghyanartur/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/barseghyanartur/subscriptions", "organizations_url": "https://api.github.com/users/barseghyanartur/orgs", "repos_url": "https://api.github.com/users/barseghyanartur/repos", "events_url": "https://api.github.com/users/barseghyanartur/events{/privacy}", "received_events_url": "https://api.github.com/users/barseghyanartur/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-05-29T12:36:07Z", "updated_at": "2017-05-30T14:25:19Z", "closed_at": "2017-05-30T14:24:17Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm upgrading an old project that did make use of `django-celery-email` version 1.0.4.\r\n\r\nCan `django-celery-email` (latest version of) handle JSON serialisation? It hasn't been available in 1.0.4.\r\n\r\nThanks in advance!", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/41", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/41/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/41/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/41/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/41", "id": 201058793, "node_id": "MDU6SXNzdWUyMDEwNTg3OTM=", "number": 41, "title": "Getting \"Received and deleted unknown message.  Wrong destination?!?\" errors from the task", "user": {"login": "harel", "id": 985978, "node_id": "MDQ6VXNlcjk4NTk3OA==", "avatar_url": "https://avatars3.githubusercontent.com/u/985978?v=4", "gravatar_id": "", "url": "https://api.github.com/users/harel", "html_url": "https://github.com/harel", "followers_url": "https://api.github.com/users/harel/followers", "following_url": "https://api.github.com/users/harel/following{/other_user}", "gists_url": "https://api.github.com/users/harel/gists{/gist_id}", "starred_url": "https://api.github.com/users/harel/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/harel/subscriptions", "organizations_url": "https://api.github.com/users/harel/orgs", "repos_url": "https://api.github.com/users/harel/repos", "events_url": "https://api.github.com/users/harel/events{/privacy}", "received_events_url": "https://api.github.com/users/harel/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-01-16T16:07:18Z", "updated_at": "2017-01-17T01:44:47Z", "closed_at": "2017-01-17T01:44:47Z", "author_association": "NONE", "active_lock_reason": null, "body": "I want to use this for Django's automated email error reporting.  They are tested to work synchronously though I'd like them to be sent via a celery task to avoid blocking the response while the email is sent. \r\n\r\nI've setup my environment with django-celery-email (using latest celery 4.x), changed the EMAIL_BACKEND, added a Queue called \"email\", etc.\r\n\r\nI run celery as I normally do: `celery worker -A projectname`, and I can see the new queue there. \r\n\r\nHowever, everytime an email is meant to send, celery spits out this error:\r\n\r\n```\r\n[2017-01-16 15:50:24,066: WARNING/MainProcess] Received and deleted unknown message.  Wrong destination?!?\r\n\r\nThe full contents of the message body was: body: [[[{u'body': u'\"POST /api/1/contacts/ HTTP/1.1\" 500 27\\n\\nReport\\n\"POST /api/1/contacts/ HTTP/1.1\" 500 27\\n\\nDjango Version: 1.10.4\\nPython Executable: /home/harel/dev/crmpro/env/bin/python\\nPython Version: 2.7.12\\nPython Path: [\\'/home/harel/dev/crmpro/crmpro/crmpro\\', \\'/home/harel/dev/crmpro/env/lib/python2.7\\', \\'/home/harel/dev/crmpro/env/lib/python2.7/plat-x86_64-linux-gnu\\', \\'/home/harel/dev/crmpro/env/lib/python2.7/lib-tk\\', \\'/home/harel/dev/crmpro/env/lib/python2.7/lib-old\\', \\'/home/harel/dev/crmpro/env/lib/python2.7/lib-dynload\\', \\'/usr/lib/python2.7\\', \\'/usr/lib/python2.7/plat-x86_64-linux-gnu\\', \\'/usr/lib/python2.7/lib-tk\\', \\'/home/harel/dev/crmpro/env/local/lib/python2.7/site-packages\\', \\'/home/harel/dev/crmpro/env/lib/python2.7/site-packages\\', \\'/home/harel/dev/crmpro/crmpro/crmpro\\']\\nServer time: Mon, 16 Jan 2017 15:50:24 +0000\\nInstalled Applications:\\n[\\'django.contrib.admin\\',\\n \\'django.contrib.auth\\',\\n \\'django.contrib.contenttypes\\',\\n \\'django.contrib.sessions\\',\\n... (16292b)\r\n{content_type:'application/json' content_encoding:'utf-8'\r\n  delivery_info:{'consumer_tag': 'None4', 'redelivered': False, 'routing_key': 'default', 'delivery_tag': 12L, 'exchange': ''} headers={'\\xe5\\xca.\\xdb\\x00\\x00\\x00\\x00\\x00': None, 'P&5\\x07\\x00': None, 'T\\nKB\\x00\\x00\\x00': 'c37cb5d4-22d6-4752-a44b-b8066a732aa1', 'N\\xfd\\x17=\\x00\\x00': 'gen32174@fiber', '\\xcfb\\xddR': 'py', '9*\\xa8': None, '\\xb7/b\\x84\\x00\\x00\\x00': 0, '\\xe0\\x0b\\xfa\\x89\\x00\\x00\\x00': None, '\\xdfR\\xc4x\\x00\\x00\\x00\\x00\\x00': [None, None], 'T3\\x1d ': 'djcelery_email_send_multiple', '\\xae\\xbf': 'c37cb5d4-22d6-4752-a44b-b8066a732aa1', '\\x11s\\x1f\\xd8\\x00\\x00\\x00\\x00': '([{\\'body\\': \\'\"POST /api/1/contacts/ HTTP/1.1\" 500 27\\n\\nReport\\n\"POST /api/1/contacts/ HTTP/1.1\" 500 27\\n\\nDjango Version: 1.10.4\\nPython Executable: /home/harel/dev/crmpro/env/bin/python\\nPython Version: 2.7.12\\nPython Path: [\\'/home/harel/dev/crmpro/crmpro/crmpro\\', \\'/home/harel/dev/crmpro/env/lib/python2.7\\', \\'/home/harel/dev/crmpro/env/lib/python2.7/plat-x86_64-linux-gnu\\', \\'/home/harel/dev/crmpro/env/lib/python2.7/lib-tk\\', \\'/home/harel/dev/crmpro/env/lib/python2.7/lib-old\\', \\'/home/harel/dev/crmpro/env/lib/python2.7/lib-dynload\\', \\'/usr/lib/python2.7\\', \\'/usr/lib/python2.7/plat-x86_64-linux-gnu\\', \\'/usr/lib/python2.7/lib-tk\\', \\'/home/harel/dev/crmpro/env/local/lib/python2.7/site-packages\\', \\'/home/harel/dev/crmpro/env/lib/python2.7/site-packages\\', \\'/home/harel/dev/crmpro/crmpro/crmpro\\']\\nServer time: Mon, 16 Jan 2017 15:50:24 +0000\\nInstalled Applications:\\n[\\'django.contrib.admin\\',\\n \\'django.contrib.auth\\',\\n \\'django.contrib.contenttypes\\',\\n \\'django.contrib.sessions\\',\\n \\'django.contrib.messages\\',\\n \\'django.contrib.staticfiles\\',\\n...\\', ...}])', 'UL\\xa1\\xfc\\x00\\x00\\x00\\x00\\x00\\x00': '{}'}}\r\n\r\n\r\n```\r\n\r\nAny idea? It looks like the tasks is not receiving a proper \"task\"?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/39", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/39/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/39/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/39/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/39", "id": 178983788, "node_id": "MDU6SXNzdWUxNzg5ODM3ODg=", "number": 39, "title": "SMTPServerDisconnected('please run connect() first',)", "user": {"login": "adi-", "id": 340741, "node_id": "MDQ6VXNlcjM0MDc0MQ==", "avatar_url": "https://avatars0.githubusercontent.com/u/340741?v=4", "gravatar_id": "", "url": "https://api.github.com/users/adi-", "html_url": "https://github.com/adi-", "followers_url": "https://api.github.com/users/adi-/followers", "following_url": "https://api.github.com/users/adi-/following{/other_user}", "gists_url": "https://api.github.com/users/adi-/gists{/gist_id}", "starred_url": "https://api.github.com/users/adi-/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/adi-/subscriptions", "organizations_url": "https://api.github.com/users/adi-/orgs", "repos_url": "https://api.github.com/users/adi-/repos", "events_url": "https://api.github.com/users/adi-/events{/privacy}", "received_events_url": "https://api.github.com/users/adi-/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-09-23T22:08:49Z", "updated_at": "2017-06-23T21:44:57Z", "closed_at": "2017-06-23T21:44:57Z", "author_association": "NONE", "active_lock_reason": null, "body": "I am getting `SMTPServerDisconnected('please run connect() first',)` on some SMTP servers. I have no clue what could be wrong. For example GMail is working fine. When I move to my local provider I get this error. Do you think it could be a problem of django-celery-email?\n\nFunny thing is, when I ommit `EMAIL_TIMEOUT` setting, those e-mails are sent in about 270 seconds or more! One by one ...\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/33", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/33/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/33/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/33/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/33", "id": 151837223, "node_id": "MDU6SXNzdWUxNTE4MzcyMjM=", "number": 33, "title": "TypeError: send_emails() takes at least 1 argument (0 given)", "user": {"login": "okfish", "id": 2776878, "node_id": "MDQ6VXNlcjI3NzY4Nzg=", "avatar_url": "https://avatars3.githubusercontent.com/u/2776878?v=4", "gravatar_id": "", "url": "https://api.github.com/users/okfish", "html_url": "https://github.com/okfish", "followers_url": "https://api.github.com/users/okfish/followers", "following_url": "https://api.github.com/users/okfish/following{/other_user}", "gists_url": "https://api.github.com/users/okfish/gists{/gist_id}", "starred_url": "https://api.github.com/users/okfish/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/okfish/subscriptions", "organizations_url": "https://api.github.com/users/okfish/orgs", "repos_url": "https://api.github.com/users/okfish/repos", "events_url": "https://api.github.com/users/okfish/events{/privacy}", "received_events_url": "https://api.github.com/users/okfish/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2016-04-29T10:30:10Z", "updated_at": "2016-05-08T15:18:19Z", "closed_at": "2016-05-08T15:17:48Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello everyone \nI'm trying to get working this trinity: django-celery, django-celery-email and django-post-office. \nSettings contains \n\n```\nEMAIL_BACKEND = 'post_office.EmailBackend'\nCELERY_EMAIL_TASK_CONFIG = { 'ignore_result': False,}\n\nPOST_OFFICE = {\n    'EMAIL_BACKEND': 'djcelery_email.backends.CeleryEmailBackend',\n    'DEFAULT_PRIORITY': 'now',\n}\n```\n\nAnd everything looks working perfectly except celery periodic task which I've added via django admin. I've choosen the registered task 'djcelery_email_send_multiple' and apply interval of 10'. The task is sending by celery beat on execution but celery demon just outputs:\n\n```\nERROR/MainProcess] Task djcelery_email_send_multiple[3d10fc14-1da3-48a5-b8b5-28df9fefea02] raised unexpected: TypeError('send_emails() takes at least 1 argument (0 given)',)\nTraceback (most recent call last):\n  File \"/home/projects/aquashop/local/lib/python2.7/site-packages/celery/app/trace.py\", line 240, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File \"/home/projects/aquashop/local/lib/python2.7/site-packages/celery/app/trace.py\", line 438, in __protected_call__\n    return self.run(*args, **kwargs)\nTypeError: send_emails() takes at least 1 argument (0 given)\n```\n\nEnv: \ndjango==1.8.9\ncelery==3.1.23\ndjango-celery==3.1.17\ndjango-celery-email==1.1.4\ndjango-post-office==2.0.7\n\nSo, the question is... Is there a workaround for the issue or i should make my own celery task, which would know about queued mails?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/32", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/32/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/32/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/32/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/32", "id": 147198888, "node_id": "MDU6SXNzdWUxNDcxOTg4ODg=", "number": 32, "title": "Is the python 3 supporting?", "user": {"login": "pahaz", "id": 1394025, "node_id": "MDQ6VXNlcjEzOTQwMjU=", "avatar_url": "https://avatars2.githubusercontent.com/u/1394025?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pahaz", "html_url": "https://github.com/pahaz", "followers_url": "https://api.github.com/users/pahaz/followers", "following_url": "https://api.github.com/users/pahaz/following{/other_user}", "gists_url": "https://api.github.com/users/pahaz/gists{/gist_id}", "starred_url": "https://api.github.com/users/pahaz/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pahaz/subscriptions", "organizations_url": "https://api.github.com/users/pahaz/orgs", "repos_url": "https://api.github.com/users/pahaz/repos", "events_url": "https://api.github.com/users/pahaz/events{/privacy}", "received_events_url": "https://api.github.com/users/pahaz/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2016-04-10T06:27:00Z", "updated_at": "2016-07-20T13:06:50Z", "closed_at": "2016-06-01T21:13:50Z", "author_association": "NONE", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/30", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/30/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/30/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/30/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/30", "id": 138679545, "node_id": "MDU6SXNzdWUxMzg2Nzk1NDU=", "number": 30, "title": "How to run worker", "user": {"login": "matejuh", "id": 1061307, "node_id": "MDQ6VXNlcjEwNjEzMDc=", "avatar_url": "https://avatars2.githubusercontent.com/u/1061307?v=4", "gravatar_id": "", "url": "https://api.github.com/users/matejuh", "html_url": "https://github.com/matejuh", "followers_url": "https://api.github.com/users/matejuh/followers", "following_url": "https://api.github.com/users/matejuh/following{/other_user}", "gists_url": "https://api.github.com/users/matejuh/gists{/gist_id}", "starred_url": "https://api.github.com/users/matejuh/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/matejuh/subscriptions", "organizations_url": "https://api.github.com/users/matejuh/orgs", "repos_url": "https://api.github.com/users/matejuh/repos", "events_url": "https://api.github.com/users/matejuh/events{/privacy}", "received_events_url": "https://api.github.com/users/matejuh/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-03-05T13:35:31Z", "updated_at": "2016-03-06T15:52:55Z", "closed_at": "2016-03-06T15:52:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "Can you please add some example how to run the worker?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/25", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/25/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/25/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/25/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/25", "id": 115254012, "node_id": "MDU6SXNzdWUxMTUyNTQwMTI=", "number": 25, "title": "Extra args on EmailMessage no longer working", "user": {"login": "chripede", "id": 406836, "node_id": "MDQ6VXNlcjQwNjgzNg==", "avatar_url": "https://avatars3.githubusercontent.com/u/406836?v=4", "gravatar_id": "", "url": "https://api.github.com/users/chripede", "html_url": "https://github.com/chripede", "followers_url": "https://api.github.com/users/chripede/followers", "following_url": "https://api.github.com/users/chripede/following{/other_user}", "gists_url": "https://api.github.com/users/chripede/gists{/gist_id}", "starred_url": "https://api.github.com/users/chripede/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/chripede/subscriptions", "organizations_url": "https://api.github.com/users/chripede/orgs", "repos_url": "https://api.github.com/users/chripede/repos", "events_url": "https://api.github.com/users/chripede/events{/privacy}", "received_events_url": "https://api.github.com/users/chripede/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 8, "created_at": "2015-11-05T10:28:07Z", "updated_at": "2016-03-10T14:38:19Z", "closed_at": "2016-03-10T14:38:19Z", "author_association": "NONE", "active_lock_reason": null, "body": "I have my configuration set up like this\n\n```\nEMAIL_BACKEND = 'djcelery_email.backends.CeleryEmailBackend'\nCELERY_EMAIL_BACKEND = \"djrill.mail.backends.djrill.DjrillBackend\"\n```\n\nmeaning that I use Mandrill to send mails.\n\nIn 1.0.4 I was able to set extra args on the EmailMessage object to use templates in Mandrill\n\n```\nemail.template_name = 'report-{}'.format(get_language())\nemail.template_content = {}\nemail.global_merge_vars = {\n    'CLIENT': Client.objects.get(slug=client_slug).name,\n}\n```\n\nAll versions after 1.0.4 no longer sends these arguments all the way to Mandrill\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/22", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/22/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/22/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/22/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/22", "id": 105185179, "node_id": "MDU6SXNzdWUxMDUxODUxNzk=", "number": 22, "title": "[ERROR/MainProcess] Received unregistered task of type 'djcelery_email_send_multiple'.", "user": {"login": "EmadMokhtar", "id": 311636, "node_id": "MDQ6VXNlcjMxMTYzNg==", "avatar_url": "https://avatars1.githubusercontent.com/u/311636?v=4", "gravatar_id": "", "url": "https://api.github.com/users/EmadMokhtar", "html_url": "https://github.com/EmadMokhtar", "followers_url": "https://api.github.com/users/EmadMokhtar/followers", "following_url": "https://api.github.com/users/EmadMokhtar/following{/other_user}", "gists_url": "https://api.github.com/users/EmadMokhtar/gists{/gist_id}", "starred_url": "https://api.github.com/users/EmadMokhtar/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/EmadMokhtar/subscriptions", "organizations_url": "https://api.github.com/users/EmadMokhtar/orgs", "repos_url": "https://api.github.com/users/EmadMokhtar/repos", "events_url": "https://api.github.com/users/EmadMokhtar/events{/privacy}", "received_events_url": "https://api.github.com/users/EmadMokhtar/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-09-07T09:52:17Z", "updated_at": "2015-09-07T11:30:05Z", "closed_at": "2015-09-07T11:30:05Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm trying to use the app to send emails but I'm always facing an error.\n\nThese are the packages in my environment:\n\n```\nDjango==1.8.3\namqp==1.4.6\nanyjson==0.3.3\nbilliard==3.3.0.20\ncelery==3.1.18\ndjango-appconf==1.0.1\ndjango-celery==3.1.16\ndjango-celery-email==1.1.2\ndjango-jfu==2.0.9\nkombu==3.0.26\npsycopg2==2.6.1\npytz==2015.4\nsix==1.9.0\nwsgiref==0.1.2\n```\n\n**settings.py**\n\n```\n**\nINSTALLED_APPS = (\n    ***\n    'djcelery',\n    'kombu.transport.django',\n    'djcelery_email',\n    ***\n)\n**\n\nCELERY_RESULT_BACKEND = 'djcelery.backends.database:DatabaseBackend'\n\nCELERY_IMPORTS = [\"djcelery_email.tasks\"]\n```\n\n**celery.py**\n\n```\nfrom __future__ import absolute_import\nfrom celery import Celery\n\napp = Celery('job_costing',\n             broker='django://')\n\nif __name__ == '__main__':\n    app.start()\n```\n\n****init.py****\n\n```\nfrom __future__ import absolute_import\n\n# This will make sure the app is always imported when\n# Django starts so that shared_task will use this app.\nfrom .celery import app as celery_app\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/20", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/20/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/20/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/20/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/20", "id": 100805925, "node_id": "MDU6SXNzdWUxMDA4MDU5MjU=", "number": 20, "title": "How to set celery.base", "user": {"login": "oppianmatt", "id": 48596, "node_id": "MDQ6VXNlcjQ4NTk2", "avatar_url": "https://avatars0.githubusercontent.com/u/48596?v=4", "gravatar_id": "", "url": "https://api.github.com/users/oppianmatt", "html_url": "https://github.com/oppianmatt", "followers_url": "https://api.github.com/users/oppianmatt/followers", "following_url": "https://api.github.com/users/oppianmatt/following{/other_user}", "gists_url": "https://api.github.com/users/oppianmatt/gists{/gist_id}", "starred_url": "https://api.github.com/users/oppianmatt/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/oppianmatt/subscriptions", "organizations_url": "https://api.github.com/users/oppianmatt/orgs", "repos_url": "https://api.github.com/users/oppianmatt/repos", "events_url": "https://api.github.com/users/oppianmatt/events{/privacy}", "received_events_url": "https://api.github.com/users/oppianmatt/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-08-13T15:59:52Z", "updated_at": "2015-11-05T15:38:03Z", "closed_at": "2015-11-05T15:38:03Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "I have an abstract celery base Task for adding extra logging with our celery tasks. Like so:\n\n```\n@task(queue='email', base=LoggingTask)\ndef foo()\n...\n```\n\n But I can't set that in the settings, can't import it since it imports celery which causes circular import and can't use a string.\n\n```\nCELERY_EMAIL_TASK_CONFIG = {\n    # we want emails to be high priority\n    'queue': 'emails',\n    # can also configure rate limit\n    # 'rate_limit': '50/m',\n    'ignore_result': True,\n    # extra logging\n    'base': 'celeryutils.LoggingTask',\n}\n```\n\nhttp://celery.readthedocs.org/en/latest/userguide/tasks.html#abstract-classes\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/18", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/18/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/18/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/18/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/18", "id": 91650480, "node_id": "MDU6SXNzdWU5MTY1MDQ4MA==", "number": 18, "title": "HTML only emails sent as plain text", "user": {"login": "gnarvaja", "id": 126963, "node_id": "MDQ6VXNlcjEyNjk2Mw==", "avatar_url": "https://avatars2.githubusercontent.com/u/126963?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gnarvaja", "html_url": "https://github.com/gnarvaja", "followers_url": "https://api.github.com/users/gnarvaja/followers", "following_url": "https://api.github.com/users/gnarvaja/following{/other_user}", "gists_url": "https://api.github.com/users/gnarvaja/gists{/gist_id}", "starred_url": "https://api.github.com/users/gnarvaja/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gnarvaja/subscriptions", "organizations_url": "https://api.github.com/users/gnarvaja/orgs", "repos_url": "https://api.github.com/users/gnarvaja/repos", "events_url": "https://api.github.com/users/gnarvaja/events{/privacy}", "received_events_url": "https://api.github.com/users/gnarvaja/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2015-06-28T22:31:49Z", "updated_at": "2015-07-06T19:54:48Z", "closed_at": "2015-07-06T19:54:44Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Messages with content_subtype overridden to \"html\" are sent as plain text when passing through djcelery.\n\nIt's because in the serialization process (email_to_dict function), only some attributes are copied. \n\nFix in https://github.com/pmclanahan/django-celery-email/pull/17\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/16", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/16/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/16/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/16/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/16", "id": 80640888, "node_id": "MDU6SXNzdWU4MDY0MDg4OA==", "number": 16, "title": "\"Could not find any downloads that satisfy the requirement django-celery-email\"", "user": {"login": "ebertti", "id": 140394, "node_id": "MDQ6VXNlcjE0MDM5NA==", "avatar_url": "https://avatars0.githubusercontent.com/u/140394?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ebertti", "html_url": "https://github.com/ebertti", "followers_url": "https://api.github.com/users/ebertti/followers", "following_url": "https://api.github.com/users/ebertti/following{/other_user}", "gists_url": "https://api.github.com/users/ebertti/gists{/gist_id}", "starred_url": "https://api.github.com/users/ebertti/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ebertti/subscriptions", "organizations_url": "https://api.github.com/users/ebertti/orgs", "repos_url": "https://api.github.com/users/ebertti/repos", "events_url": "https://api.github.com/users/ebertti/events{/privacy}", "received_events_url": "https://api.github.com/users/ebertti/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-05-25T19:30:52Z", "updated_at": "2015-11-05T15:39:57Z", "closed_at": "2015-11-05T15:39:57Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi, I getting this error on pip install django-celery-email\n\n```\npip install django-celery-email       \nDownloading/unpacking django-celery-email\n  Cannot fetch index base URL https://pypi.python.org/simple/\n  Could not find any downloads that satisfy the requirement django-celery-email\nCleaning up...\nNo distributions at all found for django-celery-email\nStoring debug log for failure in pip.log\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/15", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/15/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/15/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/15/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/15", "id": 65872812, "node_id": "MDU6SXNzdWU2NTg3MjgxMg==", "number": 15, "title": "email doesn't send successfully", "user": {"login": "Mark-Shine", "id": 2160433, "node_id": "MDQ6VXNlcjIxNjA0MzM=", "avatar_url": "https://avatars3.githubusercontent.com/u/2160433?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Mark-Shine", "html_url": "https://github.com/Mark-Shine", "followers_url": "https://api.github.com/users/Mark-Shine/followers", "following_url": "https://api.github.com/users/Mark-Shine/following{/other_user}", "gists_url": "https://api.github.com/users/Mark-Shine/gists{/gist_id}", "starred_url": "https://api.github.com/users/Mark-Shine/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Mark-Shine/subscriptions", "organizations_url": "https://api.github.com/users/Mark-Shine/orgs", "repos_url": "https://api.github.com/users/Mark-Shine/repos", "events_url": "https://api.github.com/users/Mark-Shine/events{/privacy}", "received_events_url": "https://api.github.com/users/Mark-Shine/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-04-02T08:05:50Z", "updated_at": "2015-11-05T15:40:18Z", "closed_at": "2015-11-05T15:40:18Z", "author_association": "NONE", "active_lock_reason": null, "body": "ENV: django 1.6.5, celery 3.1.17, python 2.7\n\nCelery has setup, everything is ok. I have test function add().\n\nI go with instruction, but nothing happened.\n\nSo l looked into the code, and change this line\n\n@shared_task(*_TASK_CONFIG)\ndef send_emails(messages, backend_kwargs=None, *_kwargs):\n\nto \n\n@shared_task\ndef send_emails(messages, backend_kwargs=None, **kwargs):\n\nthen it works!\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/12", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/12/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/12/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/12/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/12", "id": 61129230, "node_id": "MDU6SXNzdWU2MTEyOTIzMA==", "number": 12, "title": "Documentation: Minimum Required Django Version", "user": {"login": "reduxionist", "id": 500775, "node_id": "MDQ6VXNlcjUwMDc3NQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/500775?v=4", "gravatar_id": "", "url": "https://api.github.com/users/reduxionist", "html_url": "https://github.com/reduxionist", "followers_url": "https://api.github.com/users/reduxionist/followers", "following_url": "https://api.github.com/users/reduxionist/following{/other_user}", "gists_url": "https://api.github.com/users/reduxionist/gists{/gist_id}", "starred_url": "https://api.github.com/users/reduxionist/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/reduxionist/subscriptions", "organizations_url": "https://api.github.com/users/reduxionist/orgs", "repos_url": "https://api.github.com/users/reduxionist/repos", "events_url": "https://api.github.com/users/reduxionist/events{/privacy}", "received_events_url": "https://api.github.com/users/reduxionist/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-03-13T16:41:21Z", "updated_at": "2015-11-05T15:40:57Z", "closed_at": "2015-11-05T15:40:57Z", "author_association": "NONE", "active_lock_reason": null, "body": "Project's GitHub description states compatibility with Django 1.2+, but readme indicates 1.3+. There's no way to open a PR for project metadata so I thought I'd open this issue instead.\n\nThanks for sharing your code!\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/8", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/8/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/8/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/8/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/8", "id": 39373356, "node_id": "MDU6SXNzdWUzOTM3MzM1Ng==", "number": 8, "title": "Documentation: Add pickle serializer requirement", "user": {"login": "andresriancho", "id": 865200, "node_id": "MDQ6VXNlcjg2NTIwMA==", "avatar_url": "https://avatars0.githubusercontent.com/u/865200?v=4", "gravatar_id": "", "url": "https://api.github.com/users/andresriancho", "html_url": "https://github.com/andresriancho", "followers_url": "https://api.github.com/users/andresriancho/followers", "following_url": "https://api.github.com/users/andresriancho/following{/other_user}", "gists_url": "https://api.github.com/users/andresriancho/gists{/gist_id}", "starred_url": "https://api.github.com/users/andresriancho/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/andresriancho/subscriptions", "organizations_url": "https://api.github.com/users/andresriancho/orgs", "repos_url": "https://api.github.com/users/andresriancho/repos", "events_url": "https://api.github.com/users/andresriancho/events{/privacy}", "received_events_url": "https://api.github.com/users/andresriancho/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2014-08-03T16:21:50Z", "updated_at": "2015-11-05T15:41:38Z", "closed_at": "2015-11-05T15:41:38Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Add documentation text explaining that this module only works if the `CELERY_TASK_SERIALIZER` is pickle. Otherwise the pickling of email messages fails:\n\n``` python\n>>> from django.core.mail import EmailMessage\n>>> e = EmailMessage('a', 'b', 'c@d.com')\n>>> import json\n>>> json.dumps(e)\nTraceback (most recent call last):\n  File \"<console>\", line 1, in <module>\n  File \"/usr/lib/python2.7/json/__init__.py\", line 231, in dumps\n    return _default_encoder.encode(obj)\n  File \"/usr/lib/python2.7/json/encoder.py\", line 201, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n  File \"/usr/lib/python2.7/json/encoder.py\", line 264, in iterencode\n    return _iterencode(o, 0)\n  File \"/usr/lib/python2.7/json/encoder.py\", line 178, in default\n    raise TypeError(repr(o) + \" is not JSON serializable\")\nTypeError: <django.core.mail.message.EmailMessage object at 0x3f95c10> is not JSON serializable\n>>> \n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/7", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/7/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/7/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/7/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/7", "id": 35831687, "node_id": "MDU6SXNzdWUzNTgzMTY4Nw==", "number": 7, "title": "Running the celery worker server for django-celery-email (Doc Request)", "user": {"login": "radzhome", "id": 2678007, "node_id": "MDQ6VXNlcjI2NzgwMDc=", "avatar_url": "https://avatars1.githubusercontent.com/u/2678007?v=4", "gravatar_id": "", "url": "https://api.github.com/users/radzhome", "html_url": "https://github.com/radzhome", "followers_url": "https://api.github.com/users/radzhome/followers", "following_url": "https://api.github.com/users/radzhome/following{/other_user}", "gists_url": "https://api.github.com/users/radzhome/gists{/gist_id}", "starred_url": "https://api.github.com/users/radzhome/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/radzhome/subscriptions", "organizations_url": "https://api.github.com/users/radzhome/orgs", "repos_url": "https://api.github.com/users/radzhome/repos", "events_url": "https://api.github.com/users/radzhome/events{/privacy}", "received_events_url": "https://api.github.com/users/radzhome/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2014-06-16T20:12:19Z", "updated_at": "2015-11-05T15:42:15Z", "closed_at": "2015-11-05T15:42:15Z", "author_association": "NONE", "active_lock_reason": null, "body": "Looking at the fist steps with celery doc, I can't seem to bridge the gap between installing django-celery-email and installing celery (pip install celery) and setting up the worker server.  Looking at these docs, http://docs.celeryproject.org/en/latest/getting-started/first-steps-with-celery.html#application you have to configure an application. Can someone fill in the gaps for those of us new to celery?  \n\nI also came across this: http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#starting-the-worker-process . Is there a copy and paste task(s).py we can use for the django-celery-email app? Thanks, Rad.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/4", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/4/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/4/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/4/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/4", "id": 24822899, "node_id": "MDU6SXNzdWUyNDgyMjg5OQ==", "number": 4, "title": "Getting connection refused error", "user": {"login": "andrewebdev", "id": 84479, "node_id": "MDQ6VXNlcjg0NDc5", "avatar_url": "https://avatars2.githubusercontent.com/u/84479?v=4", "gravatar_id": "", "url": "https://api.github.com/users/andrewebdev", "html_url": "https://github.com/andrewebdev", "followers_url": "https://api.github.com/users/andrewebdev/followers", "following_url": "https://api.github.com/users/andrewebdev/following{/other_user}", "gists_url": "https://api.github.com/users/andrewebdev/gists{/gist_id}", "starred_url": "https://api.github.com/users/andrewebdev/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/andrewebdev/subscriptions", "organizations_url": "https://api.github.com/users/andrewebdev/orgs", "repos_url": "https://api.github.com/users/andrewebdev/repos", "events_url": "https://api.github.com/users/andrewebdev/events{/privacy}", "received_events_url": "https://api.github.com/users/andrewebdev/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2013-12-27T15:11:00Z", "updated_at": "2013-12-30T19:52:26Z", "closed_at": "2013-12-30T19:51:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "I followed the steps exactly but I'm getting the following error.\n\n`error: [Errno 111] Connection refused`\n\nThis is a existing project, for which email sending works as expected if I use the standard django email backends. However I get this error as soon as I change to the djcelery_email backend.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/1", "repository_url": "https://api.github.com/repos/pmclanahan/django-celery-email", "labels_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/1/labels{/name}", "comments_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/1/comments", "events_url": "https://api.github.com/repos/pmclanahan/django-celery-email/issues/1/events", "html_url": "https://github.com/pmclanahan/django-celery-email/issues/1", "id": 5158575, "node_id": "MDU6SXNzdWU1MTU4NTc1", "number": 1, "title": "rate_limit task setting will discard tasks if exceeded", "user": {"login": "kimsterv", "id": 228135, "node_id": "MDQ6VXNlcjIyODEzNQ==", "avatar_url": "https://avatars3.githubusercontent.com/u/228135?v=4", "gravatar_id": "", "url": "https://api.github.com/users/kimsterv", "html_url": "https://github.com/kimsterv", "followers_url": "https://api.github.com/users/kimsterv/followers", "following_url": "https://api.github.com/users/kimsterv/following{/other_user}", "gists_url": "https://api.github.com/users/kimsterv/gists{/gist_id}", "starred_url": "https://api.github.com/users/kimsterv/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/kimsterv/subscriptions", "organizations_url": "https://api.github.com/users/kimsterv/orgs", "repos_url": "https://api.github.com/users/kimsterv/repos", "events_url": "https://api.github.com/users/kimsterv/events{/privacy}", "received_events_url": "https://api.github.com/users/kimsterv/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2012-06-19T23:13:25Z", "updated_at": "2012-06-20T18:12:17Z", "closed_at": "2012-06-20T18:00:36Z", "author_association": "NONE", "active_lock_reason": null, "body": "I know it's not a required setting, but it appears as though celery will just discard the tasks if this rate_limit is exceeded. In other words, if this is set, and you're exceeded the rate_limit sending emails, the emails will just get discarded which is probably not the behavior you intended.\n\nPlease correct me if I'm wrong.\n", "performed_via_github_app": null, "score": 1.0}]}