{"total_count": 8, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/selwin/django-user_agents/issues/30", "repository_url": "https://api.github.com/repos/selwin/django-user_agents", "labels_url": "https://api.github.com/repos/selwin/django-user_agents/issues/30/labels{/name}", "comments_url": "https://api.github.com/repos/selwin/django-user_agents/issues/30/comments", "events_url": "https://api.github.com/repos/selwin/django-user_agents/issues/30/events", "html_url": "https://github.com/selwin/django-user_agents/issues/30", "id": 353770791, "node_id": "MDU6SXNzdWUzNTM3NzA3OTE=", "number": 30, "title": "support for django2.0", "user": {"login": "wenguonideshou", "id": 24770936, "node_id": "MDQ6VXNlcjI0NzcwOTM2", "avatar_url": "https://avatars0.githubusercontent.com/u/24770936?v=4", "gravatar_id": "", "url": "https://api.github.com/users/wenguonideshou", "html_url": "https://github.com/wenguonideshou", "followers_url": "https://api.github.com/users/wenguonideshou/followers", "following_url": "https://api.github.com/users/wenguonideshou/following{/other_user}", "gists_url": "https://api.github.com/users/wenguonideshou/gists{/gist_id}", "starred_url": "https://api.github.com/users/wenguonideshou/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/wenguonideshou/subscriptions", "organizations_url": "https://api.github.com/users/wenguonideshou/orgs", "repos_url": "https://api.github.com/users/wenguonideshou/repos", "events_url": "https://api.github.com/users/wenguonideshou/events{/privacy}", "received_events_url": "https://api.github.com/users/wenguonideshou/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2018-08-24T12:49:43Z", "updated_at": "2019-06-22T13:34:57Z", "closed_at": "2019-06-22T13:34:57Z", "author_association": "NONE", "active_lock_reason": null, "body": "thanks", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/selwin/django-user_agents/issues/26", "repository_url": "https://api.github.com/repos/selwin/django-user_agents", "labels_url": "https://api.github.com/repos/selwin/django-user_agents/issues/26/labels{/name}", "comments_url": "https://api.github.com/repos/selwin/django-user_agents/issues/26/comments", "events_url": "https://api.github.com/repos/selwin/django-user_agents/issues/26/events", "html_url": "https://github.com/selwin/django-user_agents/issues/26", "id": 304647953, "node_id": "MDU6SXNzdWUzMDQ2NDc5NTM=", "number": 26, "title": "I'm just wandering what is other in os family?", "user": {"login": "lee-seul", "id": 8280976, "node_id": "MDQ6VXNlcjgyODA5NzY=", "avatar_url": "https://avatars0.githubusercontent.com/u/8280976?v=4", "gravatar_id": "", "url": "https://api.github.com/users/lee-seul", "html_url": "https://github.com/lee-seul", "followers_url": "https://api.github.com/users/lee-seul/followers", "following_url": "https://api.github.com/users/lee-seul/following{/other_user}", "gists_url": "https://api.github.com/users/lee-seul/gists{/gist_id}", "starred_url": "https://api.github.com/users/lee-seul/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/lee-seul/subscriptions", "organizations_url": "https://api.github.com/users/lee-seul/orgs", "repos_url": "https://api.github.com/users/lee-seul/repos", "events_url": "https://api.github.com/users/lee-seul/events{/privacy}", "received_events_url": "https://api.github.com/users/lee-seul/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2018-03-13T06:57:12Z", "updated_at": "2018-03-16T02:07:02Z", "closed_at": "2018-03-16T02:07:02Z", "author_association": "NONE", "active_lock_reason": null, "body": "How can I know the os family list? \r\n\r\nI couldn't find that. \r\n\r\nwhat does other means? ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/selwin/django-user_agents/issues/20", "repository_url": "https://api.github.com/repos/selwin/django-user_agents", "labels_url": "https://api.github.com/repos/selwin/django-user_agents/issues/20/labels{/name}", "comments_url": "https://api.github.com/repos/selwin/django-user_agents/issues/20/comments", "events_url": "https://api.github.com/repos/selwin/django-user_agents/issues/20/events", "html_url": "https://github.com/selwin/django-user_agents/issues/20", "id": 233040645, "node_id": "MDU6SXNzdWUyMzMwNDA2NDU=", "number": 20, "title": "Django 1.11 issue", "user": {"login": "zavod", "id": 943836, "node_id": "MDQ6VXNlcjk0MzgzNg==", "avatar_url": "https://avatars3.githubusercontent.com/u/943836?v=4", "gravatar_id": "", "url": "https://api.github.com/users/zavod", "html_url": "https://github.com/zavod", "followers_url": "https://api.github.com/users/zavod/followers", "following_url": "https://api.github.com/users/zavod/following{/other_user}", "gists_url": "https://api.github.com/users/zavod/gists{/gist_id}", "starred_url": "https://api.github.com/users/zavod/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/zavod/subscriptions", "organizations_url": "https://api.github.com/users/zavod/orgs", "repos_url": "https://api.github.com/users/zavod/repos", "events_url": "https://api.github.com/users/zavod/events{/privacy}", "received_events_url": "https://api.github.com/users/zavod/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2017-06-01T23:48:05Z", "updated_at": "2017-08-08T05:05:52Z", "closed_at": "2017-08-08T05:05:52Z", "author_association": "NONE", "active_lock_reason": null, "body": "It's error with Django 1.11\r\n    mw_instance = middleware(handler)\r\nTypeError: object() takes no parameters", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/selwin/django-user_agents/issues/16", "repository_url": "https://api.github.com/repos/selwin/django-user_agents", "labels_url": "https://api.github.com/repos/selwin/django-user_agents/issues/16/labels{/name}", "comments_url": "https://api.github.com/repos/selwin/django-user_agents/issues/16/comments", "events_url": "https://api.github.com/repos/selwin/django-user_agents/issues/16/events", "html_url": "https://github.com/selwin/django-user_agents/issues/16", "id": 189859791, "node_id": "MDU6SXNzdWUxODk4NTk3OTE=", "number": 16, "title": "New release", "user": {"login": "simonft", "id": 6940, "node_id": "MDQ6VXNlcjY5NDA=", "avatar_url": "https://avatars3.githubusercontent.com/u/6940?v=4", "gravatar_id": "", "url": "https://api.github.com/users/simonft", "html_url": "https://github.com/simonft", "followers_url": "https://api.github.com/users/simonft/followers", "following_url": "https://api.github.com/users/simonft/following{/other_user}", "gists_url": "https://api.github.com/users/simonft/gists{/gist_id}", "starred_url": "https://api.github.com/users/simonft/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/simonft/subscriptions", "organizations_url": "https://api.github.com/users/simonft/orgs", "repos_url": "https://api.github.com/users/simonft/repos", "events_url": "https://api.github.com/users/simonft/events{/privacy}", "received_events_url": "https://api.github.com/users/simonft/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2016-11-16T21:58:00Z", "updated_at": "2017-08-08T05:08:20Z", "closed_at": "2017-08-08T05:08:19Z", "author_association": "NONE", "active_lock_reason": null, "body": "Could you release a new version? The fixes for using this with 1.10 would be particularly useful. \r\n\r\nThanks!", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/selwin/django-user_agents/issues/13", "repository_url": "https://api.github.com/repos/selwin/django-user_agents", "labels_url": "https://api.github.com/repos/selwin/django-user_agents/issues/13/labels{/name}", "comments_url": "https://api.github.com/repos/selwin/django-user_agents/issues/13/comments", "events_url": "https://api.github.com/repos/selwin/django-user_agents/issues/13/events", "html_url": "https://github.com/selwin/django-user_agents/issues/13", "id": 168793959, "node_id": "MDU6SXNzdWUxNjg3OTM5NTk=", "number": 13, "title": "UserAgentMiddleware is not working in Django 1.10", "user": {"login": "adrysn", "id": 7539358, "node_id": "MDQ6VXNlcjc1MzkzNTg=", "avatar_url": "https://avatars1.githubusercontent.com/u/7539358?v=4", "gravatar_id": "", "url": "https://api.github.com/users/adrysn", "html_url": "https://github.com/adrysn", "followers_url": "https://api.github.com/users/adrysn/followers", "following_url": "https://api.github.com/users/adrysn/following{/other_user}", "gists_url": "https://api.github.com/users/adrysn/gists{/gist_id}", "starred_url": "https://api.github.com/users/adrysn/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/adrysn/subscriptions", "organizations_url": "https://api.github.com/users/adrysn/orgs", "repos_url": "https://api.github.com/users/adrysn/repos", "events_url": "https://api.github.com/users/adrysn/events{/privacy}", "received_events_url": "https://api.github.com/users/adrysn/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2016-08-02T03:54:13Z", "updated_at": "2017-04-27T13:54:07Z", "closed_at": "2017-04-27T13:54:07Z", "author_association": "NONE", "active_lock_reason": null, "body": "UserAgentMiddleware is not working with Django 1.10. If it is inserted into the list of middlewares in settings file, an error occurs such as below.\n\n```\nUnhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10e19c158>\nTraceback (most recent call last):\n  File \"/Users/adrysn/.pyenv/versions/neumann35/lib/python3.5/site-packages/django/utils/autoreload.py\", line 226, in wrapper\n    fn(*args, **kwargs)\n  File \"/Users/adrysn/.pyenv/versions/neumann35/lib/python3.5/site-packages/django/core/management/commands/runserver.py\", line 142, in inner_run\n    handler = self.get_handler(*args, **options)\n  File \"/Users/adrysn/.pyenv/versions/neumann35/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/runserver.py\", line 27, in get_handler\n    handler = super(Command, self).get_handler(*args, **options)\n  File \"/Users/adrysn/.pyenv/versions/neumann35/lib/python3.5/site-packages/django/core/management/commands/runserver.py\", line 64, in get_handler\n    return get_internal_wsgi_application()\n  File \"/Users/adrysn/.pyenv/versions/neumann35/lib/python3.5/site-packages/django/core/servers/basehttp.py\", line 49, in get_internal_wsgi_application\n    return import_string(app_path)\n  File \"/Users/adrysn/.pyenv/versions/neumann35/lib/python3.5/site-packages/django/utils/module_loading.py\", line 20, in import_string\n    module = import_module(module_path)\n  File \"/Users/adrysn/.pyenv/versions/3.5.0/lib/python3.5/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 986, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 969, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 958, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 673, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 662, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/Users/adrysn/lablup/neumann/neumann/wsgi.py\", line 17, in <module>\n    application = get_wsgi_application()\n  File \"/Users/adrysn/.pyenv/versions/neumann35/lib/python3.5/site-packages/django/core/wsgi.py\", line 14, in get_wsgi_application\n    return WSGIHandler()\n  File \"/Users/adrysn/.pyenv/versions/neumann35/lib/python3.5/site-packages/django/core/handlers/wsgi.py\", line 153, in __init__\n    self.load_middleware()\n  File \"/Users/adrysn/.pyenv/versions/neumann35/lib/python3.5/site-packages/django/core/handlers/base.py\", line 82, in load_middleware\n    mw_instance = middleware(handler)\nTypeError: object() takes no parameters\n```\n\nThis error is probably due to the changed style of middleware introduced in Django 1.10:\nhttps://docs.djangoproject.com/en/1.10/topics/http/middleware/.\n\nThe middleware class should be updated to comply with the new style.\n\nFor the moment, one can replace `object` to `MiddlewareMixin` to enable the middleware.\n\n```\nfrom django.utils.deprecation import MiddlewareMixin\n\nclass UserAgentMiddleware(MiddlewareMixin):\n...\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/selwin/django-user_agents/issues/7", "repository_url": "https://api.github.com/repos/selwin/django-user_agents", "labels_url": "https://api.github.com/repos/selwin/django-user_agents/issues/7/labels{/name}", "comments_url": "https://api.github.com/repos/selwin/django-user_agents/issues/7/comments", "events_url": "https://api.github.com/repos/selwin/django-user_agents/issues/7/events", "html_url": "https://github.com/selwin/django-user_agents/issues/7", "id": 50461967, "node_id": "MDU6SXNzdWU1MDQ2MTk2Nw==", "number": 7, "title": "Curl and other apps", "user": {"login": "darxsys", "id": 2401714, "node_id": "MDQ6VXNlcjI0MDE3MTQ=", "avatar_url": "https://avatars1.githubusercontent.com/u/2401714?v=4", "gravatar_id": "", "url": "https://api.github.com/users/darxsys", "html_url": "https://github.com/darxsys", "followers_url": "https://api.github.com/users/darxsys/followers", "following_url": "https://api.github.com/users/darxsys/following{/other_user}", "gists_url": "https://api.github.com/users/darxsys/gists{/gist_id}", "starred_url": "https://api.github.com/users/darxsys/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/darxsys/subscriptions", "organizations_url": "https://api.github.com/users/darxsys/orgs", "repos_url": "https://api.github.com/users/darxsys/repos", "events_url": "https://api.github.com/users/darxsys/events{/privacy}", "received_events_url": "https://api.github.com/users/darxsys/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2014-11-30T16:09:13Z", "updated_at": "2015-04-25T05:20:22Z", "closed_at": "2015-04-25T05:20:22Z", "author_association": "NONE", "active_lock_reason": null, "body": "So I am using curl to access my website. Your middleware detects Curl as \"Other\" browser family which is not what I (and probably many people) need. Could you change that?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/selwin/django-user_agents/issues/5", "repository_url": "https://api.github.com/repos/selwin/django-user_agents", "labels_url": "https://api.github.com/repos/selwin/django-user_agents/issues/5/labels{/name}", "comments_url": "https://api.github.com/repos/selwin/django-user_agents/issues/5/comments", "events_url": "https://api.github.com/repos/selwin/django-user_agents/issues/5/events", "html_url": "https://github.com/selwin/django-user_agents/issues/5", "id": 36212785, "node_id": "MDU6SXNzdWUzNjIxMjc4NQ==", "number": 5, "title": "Python 3 support", "user": {"login": "hwkns", "id": 746123, "node_id": "MDQ6VXNlcjc0NjEyMw==", "avatar_url": "https://avatars2.githubusercontent.com/u/746123?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hwkns", "html_url": "https://github.com/hwkns", "followers_url": "https://api.github.com/users/hwkns/followers", "following_url": "https://api.github.com/users/hwkns/following{/other_user}", "gists_url": "https://api.github.com/users/hwkns/gists{/gist_id}", "starred_url": "https://api.github.com/users/hwkns/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hwkns/subscriptions", "organizations_url": "https://api.github.com/users/hwkns/orgs", "repos_url": "https://api.github.com/users/hwkns/repos", "events_url": "https://api.github.com/users/hwkns/events{/privacy}", "received_events_url": "https://api.github.com/users/hwkns/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2014-06-21T00:45:01Z", "updated_at": "2014-08-24T08:33:09Z", "closed_at": "2014-07-14T05:48:11Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Does django-user-agents support Python 3?\n\nIf so, it would be nice to designate that on PyPI using classifiers in setup.py (see https://pypi.python.org/pypi?%3Aaction=list_classifiers)\n\nIf not, what does the path forward look like?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/selwin/django-user_agents/issues/1", "repository_url": "https://api.github.com/repos/selwin/django-user_agents", "labels_url": "https://api.github.com/repos/selwin/django-user_agents/issues/1/labels{/name}", "comments_url": "https://api.github.com/repos/selwin/django-user_agents/issues/1/comments", "events_url": "https://api.github.com/repos/selwin/django-user_agents/issues/1/events", "html_url": "https://github.com/selwin/django-user_agents/issues/1", "id": 11066437, "node_id": "MDU6SXNzdWUxMTA2NjQzNw==", "number": 1, "title": "pip install django-user-agents does not install django_user_agents folder", "user": {"login": "guidors", "id": 971277, "node_id": "MDQ6VXNlcjk3MTI3Nw==", "avatar_url": "https://avatars3.githubusercontent.com/u/971277?v=4", "gravatar_id": "", "url": "https://api.github.com/users/guidors", "html_url": "https://github.com/guidors", "followers_url": "https://api.github.com/users/guidors/followers", "following_url": "https://api.github.com/users/guidors/following{/other_user}", "gists_url": "https://api.github.com/users/guidors/gists{/gist_id}", "starred_url": "https://api.github.com/users/guidors/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/guidors/subscriptions", "organizations_url": "https://api.github.com/users/guidors/orgs", "repos_url": "https://api.github.com/users/guidors/repos", "events_url": "https://api.github.com/users/guidors/events{/privacy}", "received_events_url": "https://api.github.com/users/guidors/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2013-02-16T11:58:39Z", "updated_at": "2013-02-16T14:32:10Z", "closed_at": "2013-02-16T14:32:10Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\n\nGreat package, I like it and am checking it out.\nHowever, after pip install django-user-agents the django_user_agents folder with the templatetags folder and the test folder are not installed. Therefore the tests can't be run after installation. Is this supposed to be like that?\n\nBest regards,\n\nGuido\n", "performed_via_github_app": null, "score": 1.0}]}