{"total_count": 16, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/34", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/34/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/34/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/34/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/34", "id": 574110948, "node_id": "MDU6SXNzdWU1NzQxMTA5NDg=", "number": 34, "title": "Provide source distribution on PyPI", "user": {"login": "johnthagen", "id": 10340167, "node_id": "MDQ6VXNlcjEwMzQwMTY3", "avatar_url": "https://avatars1.githubusercontent.com/u/10340167?v=4", "gravatar_id": "", "url": "https://api.github.com/users/johnthagen", "html_url": "https://github.com/johnthagen", "followers_url": "https://api.github.com/users/johnthagen/followers", "following_url": "https://api.github.com/users/johnthagen/following{/other_user}", "gists_url": "https://api.github.com/users/johnthagen/gists{/gist_id}", "starred_url": "https://api.github.com/users/johnthagen/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/johnthagen/subscriptions", "organizations_url": "https://api.github.com/users/johnthagen/orgs", "repos_url": "https://api.github.com/users/johnthagen/repos", "events_url": "https://api.github.com/users/johnthagen/events{/privacy}", "received_events_url": "https://api.github.com/users/johnthagen/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-03-02T16:57:28Z", "updated_at": "2020-03-09T12:35:39Z", "closed_at": "2020-03-09T12:35:38Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Could you please also provide source distributions (`python3 setup.py sdist`) for 0.1.1 and future releases?\r\n\r\nThis helps when using `pip download` for offline installs, otherwise this error can occur:\r\n\r\n```\r\nERROR: Could not find a version that satisfies the requirement django-debug-toolbar-request-history==0.1.1 (from -r /requirements.txt (line 17)) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7)\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/28", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/28/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/28/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/28/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/28", "id": 458781082, "node_id": "MDU6SXNzdWU0NTg3ODEwODI=", "number": 28, "title": "Incompatible with django-debug-toolbar 2.0", "user": {"login": "rodlukas", "id": 13161588, "node_id": "MDQ6VXNlcjEzMTYxNTg4", "avatar_url": "https://avatars3.githubusercontent.com/u/13161588?v=4", "gravatar_id": "", "url": "https://api.github.com/users/rodlukas", "html_url": "https://github.com/rodlukas", "followers_url": "https://api.github.com/users/rodlukas/followers", "following_url": "https://api.github.com/users/rodlukas/following{/other_user}", "gists_url": "https://api.github.com/users/rodlukas/gists{/gist_id}", "starred_url": "https://api.github.com/users/rodlukas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/rodlukas/subscriptions", "organizations_url": "https://api.github.com/users/rodlukas/orgs", "repos_url": "https://api.github.com/users/rodlukas/repos", "events_url": "https://api.github.com/users/rodlukas/events{/privacy}", "received_events_url": "https://api.github.com/users/rodlukas/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 11, "created_at": "2019-06-20T17:29:15Z", "updated_at": "2019-09-18T12:42:30Z", "closed_at": "2019-09-18T12:42:30Z", "author_association": "NONE", "active_lock_reason": null, "body": "Not working with ddt 2.0 (1.11 is ok) due to the exception `KeyError: 'RequestHistoryPanel'` in `request_history.py` on line 218 ([here](https://github.com/djsutho/django-debug-toolbar-request-history/blob/f30e02558ea6bd42c94aa632de8f39ec87a32439/ddt_request_history/panels/request_history.py#L218)), probably due to some [backward incompatible changes](https://github.com/jazzband/django-debug-toolbar/blob/master/docs/changes.rst#backwards-incompatible-changes) made in v2.0", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/25", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/25/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/25/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/25/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/25", "id": 435756593, "node_id": "MDU6SXNzdWU0MzU3NTY1OTM=", "number": 25, "title": "Panels don't load selected request from history with django-debug-toolbar 1.9.1", "user": {"login": "laffuste", "id": 3774128, "node_id": "MDQ6VXNlcjM3NzQxMjg=", "avatar_url": "https://avatars2.githubusercontent.com/u/3774128?v=4", "gravatar_id": "", "url": "https://api.github.com/users/laffuste", "html_url": "https://github.com/laffuste", "followers_url": "https://api.github.com/users/laffuste/followers", "following_url": "https://api.github.com/users/laffuste/following{/other_user}", "gists_url": "https://api.github.com/users/laffuste/gists{/gist_id}", "starred_url": "https://api.github.com/users/laffuste/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/laffuste/subscriptions", "organizations_url": "https://api.github.com/users/laffuste/orgs", "repos_url": "https://api.github.com/users/laffuste/repos", "events_url": "https://api.github.com/users/laffuste/events{/privacy}", "received_events_url": "https://api.github.com/users/laffuste/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-04-22T14:55:17Z", "updated_at": "2019-06-19T09:18:35Z", "closed_at": "2019-06-19T09:18:34Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Django==1.8.19\r\ndjango-debug-toolbar==1.9.1\r\ndjango-debug-toolbar-request-history==0.0.10\r\n\r\n### Steps to reproduce\r\n1. Open any page with ddt and ddtrh activated\r\n1. Do some ajax\r\n1. Open ddtrh panel and click on one of the ajax requests\r\n1. Open SQL panel: the SQL shown does not correspond to the ajax call but to the first page render\r\n\r\n### Cause\r\n\r\nThe issue is caused because django-debug-toolbar < 1.10 used jQuery to [retrieve the store-id](https://github.com/jazzband/django-debug-toolbar/blob/c8345d2e1c04e784dc8d38681a0037b1e0849066/debug_toolbar/static/debug_toolbar/js/toolbar.js#L22) in its first request. django-debug-toolbar-request-history then [sets the store-id directly to the attribute](https://github.com/djsutho/django-debug-toolbar-request-history/blob/b3da3e12762d68c23a307ffb279e6047f80ba695/ddt_request_history/panels/request_history.html#L57), which bypasses jQuery data cache. When calling a panel for the second time with a new store-id, jQuery's `$('#djDebug').data('store-id')` will return the cached value (the first set store-id).\r\n\r\nTo fix this, jquery data cache should be cleaned, so the next call to `$('#djDebug').data('store-id')` hits the real value.\r\n\r\nNote: django-debug-toolbar uses it's own jQuery.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/22", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/22/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/22/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/22/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/22", "id": 360597676, "node_id": "MDU6SXNzdWUzNjA1OTc2NzY=", "number": 22, "title": "Incompatible with django-debug-toolbar 1.10", "user": {"login": "tienne-B", "id": 6293465, "node_id": "MDQ6VXNlcjYyOTM0NjU=", "avatar_url": "https://avatars3.githubusercontent.com/u/6293465?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tienne-B", "html_url": "https://github.com/tienne-B", "followers_url": "https://api.github.com/users/tienne-B/followers", "following_url": "https://api.github.com/users/tienne-B/following{/other_user}", "gists_url": "https://api.github.com/users/tienne-B/gists{/gist_id}", "starred_url": "https://api.github.com/users/tienne-B/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tienne-B/subscriptions", "organizations_url": "https://api.github.com/users/tienne-B/orgs", "repos_url": "https://api.github.com/users/tienne-B/repos", "events_url": "https://api.github.com/users/tienne-B/events{/privacy}", "received_events_url": "https://api.github.com/users/tienne-B/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2018-09-16T03:28:27Z", "updated_at": "2018-09-23T08:32:30Z", "closed_at": "2018-09-23T08:19:52Z", "author_association": "NONE", "active_lock_reason": null, "body": "This is probably due to django-debug-toolbar getting rid of its jQuery dependency.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/18", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/18/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/18/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/18/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/18", "id": 290197036, "node_id": "MDU6SXNzdWUyOTAxOTcwMzY=", "number": 18, "title": "Request history panel makes SQL panel log extra queries", "user": {"login": "x-yuri", "id": 730588, "node_id": "MDQ6VXNlcjczMDU4OA==", "avatar_url": "https://avatars0.githubusercontent.com/u/730588?v=4", "gravatar_id": "", "url": "https://api.github.com/users/x-yuri", "html_url": "https://github.com/x-yuri", "followers_url": "https://api.github.com/users/x-yuri/followers", "following_url": "https://api.github.com/users/x-yuri/following{/other_user}", "gists_url": "https://api.github.com/users/x-yuri/gists{/gist_id}", "starred_url": "https://api.github.com/users/x-yuri/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/x-yuri/subscriptions", "organizations_url": "https://api.github.com/users/x-yuri/orgs", "repos_url": "https://api.github.com/users/x-yuri/repos", "events_url": "https://api.github.com/users/x-yuri/events{/privacy}", "received_events_url": "https://api.github.com/users/x-yuri/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2018-01-20T14:43:15Z", "updated_at": "2018-02-06T08:16:55Z", "closed_at": "2018-02-06T08:16:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "The issue here is that `django-debug-toolbar` first executes [`process_response`][1] method of every panel, then disables [instrumentation][2], then runs [`generate_stats`][3]. With Request history panel, `generate_stats` is called when the former processes response, before instrumentation having been disabled.\r\n\r\n[1]: https://github.com/jazzband/django-debug-toolbar/blob/1.9.1/debug_toolbar/middleware.py#L102\r\n[2]: https://github.com/jazzband/django-debug-toolbar/blob/1.9.1/debug_toolbar/middleware.py#L110\r\n[3]: https://github.com/jazzband/django-debug-toolbar/blob/1.9.1/debug_toolbar/middleware.py#L132\r\n\r\nAs a part of generating stats *Request* panel records session data, which makes an SQL request. The request is recorded by SQL panel, since instrumentation has not yet been disabled. As a result in Debug toolbar I see \"1 query in x ms.\" But when I open SQL panel I see no SQL queries. Supposedly because data for the panel are provided by Request history panel. And by the time Request History panel called `generate_stats` on SQL panel, no extra queries were executed.\r\n\r\n[4]: https://github.com/jazzband/django-debug-toolbar/blob/1.9.1/debug_toolbar/panels/request.py#L57", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/16", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/16/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/16/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/16/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/16", "id": 277441490, "node_id": "MDU6SXNzdWUyNzc0NDE0OTA=", "number": 16, "title": "allow_ajax doesn't work with django-debug-toolbar==1.9.1", "user": {"login": "benjaminrigaud", "id": 1983087, "node_id": "MDQ6VXNlcjE5ODMwODc=", "avatar_url": "https://avatars3.githubusercontent.com/u/1983087?v=4", "gravatar_id": "", "url": "https://api.github.com/users/benjaminrigaud", "html_url": "https://github.com/benjaminrigaud", "followers_url": "https://api.github.com/users/benjaminrigaud/followers", "following_url": "https://api.github.com/users/benjaminrigaud/following{/other_user}", "gists_url": "https://api.github.com/users/benjaminrigaud/gists{/gist_id}", "starred_url": "https://api.github.com/users/benjaminrigaud/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/benjaminrigaud/subscriptions", "organizations_url": "https://api.github.com/users/benjaminrigaud/orgs", "repos_url": "https://api.github.com/users/benjaminrigaud/repos", "events_url": "https://api.github.com/users/benjaminrigaud/events{/privacy}", "received_events_url": "https://api.github.com/users/benjaminrigaud/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2017-11-28T16:07:54Z", "updated_at": "2017-12-06T12:14:25Z", "closed_at": "2017-12-06T12:14:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "The SQL tab shows a 404: NOT FOUND\r\nAnd the Request History tab shows no ajax requests.\r\n\r\nIt used to work fine with ddt==1.9.0\r\n\r\nThe doc says `For vesions of the debug toolbar less than 1.8 you can record ajax requests by adding SHOW_TOOLBAR_CALLBACK to DEBUG_TOOLBAR_CONFIG`\r\n\r\nDoes it mean we shouldn't be able to see Ajax requests with DDT >= 1.8.0?\r\n\r\nBen", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/15", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/15/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/15/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/15/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/15", "id": 255922387, "node_id": "MDU6SXNzdWUyNTU5MjIzODc=", "number": 15, "title": "KeyError: None on stats for request_history", "user": {"login": "PythonicNinja", "id": 1098417, "node_id": "MDQ6VXNlcjEwOTg0MTc=", "avatar_url": "https://avatars3.githubusercontent.com/u/1098417?v=4", "gravatar_id": "", "url": "https://api.github.com/users/PythonicNinja", "html_url": "https://github.com/PythonicNinja", "followers_url": "https://api.github.com/users/PythonicNinja/followers", "following_url": "https://api.github.com/users/PythonicNinja/following{/other_user}", "gists_url": "https://api.github.com/users/PythonicNinja/gists{/gist_id}", "starred_url": "https://api.github.com/users/PythonicNinja/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/PythonicNinja/subscriptions", "organizations_url": "https://api.github.com/users/PythonicNinja/orgs", "repos_url": "https://api.github.com/users/PythonicNinja/repos", "events_url": "https://api.github.com/users/PythonicNinja/events{/privacy}", "received_events_url": "https://api.github.com/users/PythonicNinja/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2017-09-07T12:37:33Z", "updated_at": "2018-02-06T09:51:03Z", "closed_at": "2018-02-06T09:50:08Z", "author_association": "NONE", "active_lock_reason": null, "body": "```\r\nTraceback (most recent call last):\r\n  File \"env/src/django/django/core/handlers/exception.py\", line 41, in inner\r\n    response = get_response(request)\r\n  File \"env/src/django/django/utils/deprecation.py\", line 142, in __call__\r\n    response = self.process_response(request, response)\r\n  File \"env/lib/python3.5/site-packages/debug_toolbar/middleware.py\", line 102, in process_response\r\n    new_response = panel.process_response(request, response)\r\n  File \"env/lib/python3.5/site-packages/ddt_request_history/panels/request_history.py\", line 164, in process_response\r\n    panel.generate_stats(request, response)\r\n  File \"env/lib/python3.5/site-packages/debug_toolbar/panels/profiling.py\", line 170, in generate_stats\r\n    root = FunctionCall(self.stats, self.stats.get_root_func(), depth=0)\r\n  File \"env/lib/python3.5/site-packages/debug_toolbar/panels/profiling.py\", line 51, in __init__\r\n    self.stats = statobj.stats[func][:4]\r\nKeyError: None\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/14", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/14/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/14/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/14/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/14", "id": 244101216, "node_id": "MDU6SXNzdWUyNDQxMDEyMTY=", "number": 14, "title": "Error importing DebugToolbarMiddleware", "user": {"login": "dirkmoors", "id": 1183654, "node_id": "MDQ6VXNlcjExODM2NTQ=", "avatar_url": "https://avatars3.githubusercontent.com/u/1183654?v=4", "gravatar_id": "", "url": "https://api.github.com/users/dirkmoors", "html_url": "https://github.com/dirkmoors", "followers_url": "https://api.github.com/users/dirkmoors/followers", "following_url": "https://api.github.com/users/dirkmoors/following{/other_user}", "gists_url": "https://api.github.com/users/dirkmoors/gists{/gist_id}", "starred_url": "https://api.github.com/users/dirkmoors/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dirkmoors/subscriptions", "organizations_url": "https://api.github.com/users/dirkmoors/orgs", "repos_url": "https://api.github.com/users/dirkmoors/repos", "events_url": "https://api.github.com/users/dirkmoors/events{/privacy}", "received_events_url": "https://api.github.com/users/dirkmoors/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 8, "created_at": "2017-07-19T16:32:47Z", "updated_at": "2018-02-12T08:49:51Z", "closed_at": "2018-02-12T08:49:51Z", "author_association": "NONE", "active_lock_reason": null, "body": "When I'm trying to integrate it into my project, I'm getting:\r\n```python\r\napp_1       | Traceback (most recent call last):\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/gunicorn/arbiter.py\", line 578, in spawn_worker\r\napp_1       |     worker.init_process()\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py\", line 126, in init_process\r\napp_1       |     self.load_wsgi()\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/gunicorn/workers/base.py\", line 135, in load_wsgi\r\napp_1       |     self.wsgi = self.app.wsgi()\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/gunicorn/app/base.py\", line 67, in wsgi\r\napp_1       |     self.callable = self.load()\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py\", line 65, in load\r\napp_1       |     return self.load_wsgiapp()\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py\", line 52, in load_wsgiapp\r\napp_1       |     return util.import_app(self.app_uri)\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/gunicorn/util.py\", line 352, in import_app\r\napp_1       |     __import__(module)\r\napp_1       |   File \"/data/src/ekona/wsgi.py\", line 16, in <module>\r\napp_1       |     application = get_wsgi_application()\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/django/core/wsgi.py\", line 14, in get_wsgi_application\r\napp_1       |     return WSGIHandler()\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/django/core/handlers/wsgi.py\", line 153, in __init__\r\napp_1       |     self.load_middleware()\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py\", line 80, in load_middleware\r\napp_1       |     middleware = import_string(middleware_path)\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/django/utils/module_loading.py\", line 20, in import_string\r\napp_1       |     module = import_module(module_path)\r\napp_1       |   File \"/usr/local/lib/python3.5/importlib/__init__.py\", line 126, in import_module\r\napp_1       |     return _bootstrap._gcd_import(name[level:], package, level)\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/debug_toolbar/middleware.py\", line 17, in <module>\r\napp_1       |     from debug_toolbar.toolbar import DebugToolbar\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/debug_toolbar/toolbar.py\", line 135, in <module>\r\napp_1       |     urlpatterns = DebugToolbar.get_urls()\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/debug_toolbar/toolbar.py\", line 128, in get_urls\r\napp_1       |     for panel_class in cls.get_panel_classes():\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/debug_toolbar/toolbar.py\", line 111, in get_panel_classes\r\napp_1       |     for panel_path in dt_settings.get_panels()\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/debug_toolbar/toolbar.py\", line 111, in <listcomp>\r\napp_1       |     for panel_path in dt_settings.get_panels()\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/django/utils/module_loading.py\", line 20, in import_string\r\napp_1       |     module = import_module(module_path)\r\napp_1       |   File \"/usr/local/lib/python3.5/importlib/__init__.py\", line 126, in import_module\r\napp_1       |     return _bootstrap._gcd_import(name[level:], package, level)\r\napp_1       |   File \"/usr/local/lib/python3.5/site-packages/ddt_request_history/panels/request_history.py\", line 19, in <module>\r\napp_1       |     from debug_toolbar.middleware import DebugToolbarMiddleware\r\n````\r\n\r\nI'm on Django 1.10.7, Debug Toolbar 1.8, and master branch for this repo.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/13", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/13/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/13/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/13/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/13", "id": 240017680, "node_id": "MDU6SXNzdWUyNDAwMTc2ODA=", "number": 13, "title": "Viewing request history is \"leaking\" a file handle (minor)", "user": {"login": "jlaunonen", "id": 1665808, "node_id": "MDQ6VXNlcjE2NjU4MDg=", "avatar_url": "https://avatars0.githubusercontent.com/u/1665808?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jlaunonen", "html_url": "https://github.com/jlaunonen", "followers_url": "https://api.github.com/users/jlaunonen/followers", "following_url": "https://api.github.com/users/jlaunonen/following{/other_user}", "gists_url": "https://api.github.com/users/jlaunonen/gists{/gist_id}", "starred_url": "https://api.github.com/users/jlaunonen/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jlaunonen/subscriptions", "organizations_url": "https://api.github.com/users/jlaunonen/orgs", "repos_url": "https://api.github.com/users/jlaunonen/repos", "events_url": "https://api.github.com/users/jlaunonen/events{/privacy}", "received_events_url": "https://api.github.com/users/jlaunonen/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-07-02T15:42:36Z", "updated_at": "2017-08-06T11:36:30Z", "closed_at": "2017-08-06T11:36:30Z", "author_association": "NONE", "active_lock_reason": null, "body": "Causes following warning to be issued (on v0.0.4 with `python -Wd` enabled):\r\n\r\n> ddt_request_history/panels/request_history.py:144: ResourceWarning: unclosed file <_io.TextIOWrapper name='ddt_request_history/panels/request_history.html' mode='r' encoding='UTF-8'>\r\n>  t = Template(open(template_path).read())\r\n\r\nThe culprit at [ddt_request_history/panels/request_history.py#L177](https://github.com/djsutho/django-debug-toolbar-request-history/blob/e614072553f2adfb9a0fe50a691b08eb567b91db/ddt_request_history/panels/request_history.py#L177) should probably read something like\r\n\r\n```python\r\nwith open(template_path) as f:\r\n    t = Template(f.read())\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/11", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/11/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/11/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/11/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/11", "id": 235865467, "node_id": "MDU6SXNzdWUyMzU4NjU0Njc=", "number": 11, "title": "DDTRH==0.0.4 | DDT 1.8 - Http404 for all other panels after update", "user": {"login": "julian-rachmann", "id": 20297677, "node_id": "MDQ6VXNlcjIwMjk3Njc3", "avatar_url": "https://avatars2.githubusercontent.com/u/20297677?v=4", "gravatar_id": "", "url": "https://api.github.com/users/julian-rachmann", "html_url": "https://github.com/julian-rachmann", "followers_url": "https://api.github.com/users/julian-rachmann/followers", "following_url": "https://api.github.com/users/julian-rachmann/following{/other_user}", "gists_url": "https://api.github.com/users/julian-rachmann/gists{/gist_id}", "starred_url": "https://api.github.com/users/julian-rachmann/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/julian-rachmann/subscriptions", "organizations_url": "https://api.github.com/users/julian-rachmann/orgs", "repos_url": "https://api.github.com/users/julian-rachmann/repos", "events_url": "https://api.github.com/users/julian-rachmann/events{/privacy}", "received_events_url": "https://api.github.com/users/julian-rachmann/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2017-06-14T12:40:17Z", "updated_at": "2017-07-27T00:50:41Z", "closed_at": "2017-07-23T13:22:34Z", "author_association": "NONE", "active_lock_reason": null, "body": "After upgrading to Django Debug Toolbar 1.8, all panels except Request History return Http404. Request History also does not return AJAX requests, even though I have the config set as per below:\r\n\r\n```\r\nDEBUG_TOOLBAR_CONFIG = {\r\n    'SHOW_TOOLBAR_CALLBACK': 'ddt_request_history.panels.request_history.allow_ajax',\r\n}\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/10", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/10/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/10/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/10/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/10", "id": 202801957, "node_id": "MDU6SXNzdWUyMDI4MDE5NTc=", "number": 10, "title": "Bug: Double escaping of SQL queries", "user": {"login": "NotSqrt", "id": 1997005, "node_id": "MDQ6VXNlcjE5OTcwMDU=", "avatar_url": "https://avatars3.githubusercontent.com/u/1997005?v=4", "gravatar_id": "", "url": "https://api.github.com/users/NotSqrt", "html_url": "https://github.com/NotSqrt", "followers_url": "https://api.github.com/users/NotSqrt/followers", "following_url": "https://api.github.com/users/NotSqrt/following{/other_user}", "gists_url": "https://api.github.com/users/NotSqrt/gists{/gist_id}", "starred_url": "https://api.github.com/users/NotSqrt/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/NotSqrt/subscriptions", "organizations_url": "https://api.github.com/users/NotSqrt/orgs", "repos_url": "https://api.github.com/users/NotSqrt/repos", "events_url": "https://api.github.com/users/NotSqrt/events{/privacy}", "received_events_url": "https://api.github.com/users/NotSqrt/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-01-24T12:14:14Z", "updated_at": "2017-02-14T12:29:55Z", "closed_at": "2017-02-14T12:29:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\r\n\r\nCommit 728468bcb2d8d32c4e9f22d9e4d9660f01d41cd1 introduces double escaping of SQL queries:\r\n\r\nAt commit 0281cb9c7dc199106684764bbd11737b045e242b:\r\n![selection_304](https://cloud.githubusercontent.com/assets/1997005/22246743/90edc0b0-e236-11e6-8105-88e5c97ac22c.png)\r\n\r\nAt commit 728468bcb2d8d32c4e9f22d9e4d9660f01d41cd1:\r\n![selection_305](https://cloud.githubusercontent.com/assets/1997005/22246746/9504d95e-e236-11e6-97d6-f5aef350baad.png)\r\n\r\n\r\nCf faulkner/django-debug-panel@a8bc8a28d1b9def22632cbdb40a488ce27654f0b for a potentially similar bug.\r\n\r\nThanks !", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/9", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/9/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/9/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/9/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/9", "id": 198285295, "node_id": "MDU6SXNzdWUxOTgyODUyOTU=", "number": 9, "title": "Create and publish Pypi package", "user": {"login": "russkel", "id": 1073606, "node_id": "MDQ6VXNlcjEwNzM2MDY=", "avatar_url": "https://avatars3.githubusercontent.com/u/1073606?v=4", "gravatar_id": "", "url": "https://api.github.com/users/russkel", "html_url": "https://github.com/russkel", "followers_url": "https://api.github.com/users/russkel/followers", "following_url": "https://api.github.com/users/russkel/following{/other_user}", "gists_url": "https://api.github.com/users/russkel/gists{/gist_id}", "starred_url": "https://api.github.com/users/russkel/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/russkel/subscriptions", "organizations_url": "https://api.github.com/users/russkel/orgs", "repos_url": "https://api.github.com/users/russkel/repos", "events_url": "https://api.github.com/users/russkel/events{/privacy}", "received_events_url": "https://api.github.com/users/russkel/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2017-01-01T23:04:06Z", "updated_at": "2017-02-14T11:55:03Z", "closed_at": "2017-02-14T11:49:41Z", "author_association": "NONE", "active_lock_reason": null, "body": "Then people will not need to put git links in their pip requirements files :).", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/8", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/8/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/8/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/8/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/8", "id": 181076759, "node_id": "MDU6SXNzdWUxODEwNzY3NTk=", "number": 8, "title": "SQLPanel: No SQL queries were recorded during this request", "user": {"login": "yassam", "id": 111379, "node_id": "MDQ6VXNlcjExMTM3OQ==", "avatar_url": "https://avatars0.githubusercontent.com/u/111379?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yassam", "html_url": "https://github.com/yassam", "followers_url": "https://api.github.com/users/yassam/followers", "following_url": "https://api.github.com/users/yassam/following{/other_user}", "gists_url": "https://api.github.com/users/yassam/gists{/gist_id}", "starred_url": "https://api.github.com/users/yassam/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yassam/subscriptions", "organizations_url": "https://api.github.com/users/yassam/orgs", "repos_url": "https://api.github.com/users/yassam/repos", "events_url": "https://api.github.com/users/yassam/events{/privacy}", "received_events_url": "https://api.github.com/users/yassam/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2016-10-05T06:46:36Z", "updated_at": "2016-10-22T06:37:13Z", "closed_at": "2016-10-22T06:32:36Z", "author_association": "NONE", "active_lock_reason": null, "body": "Trying the latest version of this in combination with Debug Toolbar 1.5.\n\nWhen I click on all but the first request, the SQL Panel says \"No SQL queries were recorded during this request\".\n\nThe summary SQL entry on the right looks ok, e.g. \"1624 queries in 1325.60ms\", but when I click on the summary panel to get the main SQL display on the left, it says \"No SQL queries...\"\n\nIs there something specific I need to do to get SQL queries recorded for all requests?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/6", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/6/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/6/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/6/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/6", "id": 116746497, "node_id": "MDU6SXNzdWUxMTY3NDY0OTc=", "number": 6, "title": "key error \"utime\" with ajax call:datatype set as json", "user": {"login": "dassio", "id": 733502, "node_id": "MDQ6VXNlcjczMzUwMg==", "avatar_url": "https://avatars3.githubusercontent.com/u/733502?v=4", "gravatar_id": "", "url": "https://api.github.com/users/dassio", "html_url": "https://github.com/dassio", "followers_url": "https://api.github.com/users/dassio/followers", "following_url": "https://api.github.com/users/dassio/following{/other_user}", "gists_url": "https://api.github.com/users/dassio/gists{/gist_id}", "starred_url": "https://api.github.com/users/dassio/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dassio/subscriptions", "organizations_url": "https://api.github.com/users/dassio/orgs", "repos_url": "https://api.github.com/users/dassio/repos", "events_url": "https://api.github.com/users/dassio/events{/privacy}", "received_events_url": "https://api.github.com/users/dassio/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-11-13T10:58:10Z", "updated_at": "2016-10-22T06:42:03Z", "closed_at": "2016-10-22T06:42:03Z", "author_association": "NONE", "active_lock_reason": null, "body": "using ajax with datatype set as following:\n`$.ajax({\n            datatype: \"son\",`\n\nError:\n  **\\* KeyError: u'utile'\n\nseems like code return here directly,cause `_HTML_TYPES` do not include json :\n`if any((getattr(response, 'streaming', False),\n                'gzip' in content_encoding,\n                content_type not in _HTML_TYPES)):\n            return response`\n\n`panel.generate_stats(request, response)` didn't get run:\n       `# Insert the toolbar in the response.\n        content = force_text(response.content, encoding=settings.DEFAULT_CHARSET)\n        insert_before = dt_settings.CONFIG['INSERT_BEFORE']\n        try:                    # Python >= 2.7\n            pattern = re.escape(insert_before)\n            bits = re.split(pattern, content, flags=re.IGNORECASE)\n        except TypeError:       # Python < 2.7\n            pattern = '(.+?)(%s|$)' % re.escape(insert_before)\n            matches = re.findall(pattern, content, flags=re.DOTALL | re.IGNORECASE)\n            bits = [m[0] for m in matches if m[1] == insert_before]\n            # When the body ends with a newline, there's two trailing groups.\n            bits.append(''.join(m[0] for m in matches if m[1] == ''))\n        if len(bits) > 1:\n            # When the toolbar will be inserted for sure, generate the stats.\n            for panel in reversed(toolbar.enabled_panels):\n                panel.generate_stats(request, response)`\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/4", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/4/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/4/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/4/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/4", "id": 91511265, "node_id": "MDU6SXNzdWU5MTUxMTI2NQ==", "number": 4, "title": "Getting multiple errors", "user": {"login": "jsvh", "id": 831792, "node_id": "MDQ6VXNlcjgzMTc5Mg==", "avatar_url": "https://avatars2.githubusercontent.com/u/831792?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jsvh", "html_url": "https://github.com/jsvh", "followers_url": "https://api.github.com/users/jsvh/followers", "following_url": "https://api.github.com/users/jsvh/following{/other_user}", "gists_url": "https://api.github.com/users/jsvh/gists{/gist_id}", "starred_url": "https://api.github.com/users/jsvh/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jsvh/subscriptions", "organizations_url": "https://api.github.com/users/jsvh/orgs", "repos_url": "https://api.github.com/users/jsvh/repos", "events_url": "https://api.github.com/users/jsvh/events{/privacy}", "received_events_url": "https://api.github.com/users/jsvh/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-06-27T20:36:39Z", "updated_at": "2015-06-30T01:45:09Z", "closed_at": "2015-06-30T01:42:52Z", "author_association": "NONE", "active_lock_reason": null, "body": "Using django 1.8.2, Python 2.7.5, jquery 2.1.4, debug toolbar 1.3.2, psycopg2\nTrying to use it for ajax requests\n\nNo problems when loading.\n\nWhen clicking the panel I get the following error.\n\n```\nSyntaxError: Unexpected keyword 'function'. Expected ';' after var declaration.\n```\n\nThe requests load properly but the toggles don't work.\n\n```\nReferenceError: Can't find variable: djdtTogglePost\n```\n\nAny help would be appreciated...\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/2", "repository_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history", "labels_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/2/labels{/name}", "comments_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/2/comments", "events_url": "https://api.github.com/repos/djsutho/django-debug-toolbar-request-history/issues/2/events", "html_url": "https://github.com/djsutho/django-debug-toolbar-request-history/issues/2", "id": 41797721, "node_id": "MDU6SXNzdWU0MTc5NzcyMQ==", "number": 2, "title": "500: INTERNAL SERVER ERROR", "user": {"login": "arsham", "id": 428611, "node_id": "MDQ6VXNlcjQyODYxMQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/428611?v=4", "gravatar_id": "", "url": "https://api.github.com/users/arsham", "html_url": "https://github.com/arsham", "followers_url": "https://api.github.com/users/arsham/followers", "following_url": "https://api.github.com/users/arsham/following{/other_user}", "gists_url": "https://api.github.com/users/arsham/gists{/gist_id}", "starred_url": "https://api.github.com/users/arsham/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/arsham/subscriptions", "organizations_url": "https://api.github.com/users/arsham/orgs", "repos_url": "https://api.github.com/users/arsham/repos", "events_url": "https://api.github.com/users/arsham/events{/privacy}", "received_events_url": "https://api.github.com/users/arsham/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2014-09-03T09:34:10Z", "updated_at": "2014-09-16T15:11:48Z", "closed_at": "2014-09-16T15:11:48Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\n\nI get this error: 500: INTERNAL SERVER ERROR.\nEverything else in toolbar works fine.\n\nThis is the traceback:\n\n```\n    Internal Server Error: /__debug__/render_panel/\n    Traceback (most recent call last):\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/core/handlers/base.py\", line 105, in get_response\n        response = middleware_method(request, callback, callback_args, callback_kwargs)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/debug_toolbar/middleware.py\", line 74, in process_view\n        response = panel.process_view(request, view_func, view_args, view_kwargs)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/ddt_request_history/panels/request_history.py\", line 72, in process_view\n        return HttpResponse(self.content)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/ddt_request_history/panels/request_history.py\", line 117, in content\n        return t.render(Context({'toolbars': toolbars}))\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/base.py\", line 140, in render\n        return self._render(context)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/test/utils.py\", line 85, in instrumented_test_render\n        return self.nodelist.render(context)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/base.py\", line 840, in render\n        bit = self.render_node(node, context)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/debug.py\", line 78, in render_node\n        return node.render(context)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/defaulttags.py\", line 196, in render\n        nodelist.append(node.render(context))\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/defaulttags.py\", line 196, in render\n        nodelist.append(node.render(context))\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/debug.py\", line 88, in render\n        output = self.filter_expression.resolve(context)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/base.py\", line 585, in resolve\n        obj = self.var.resolve(context)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/base.py\", line 735, in resolve\n        value = self._resolve_lookup(context)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/base.py\", line 789, in _resolve_lookup\n        current = current()\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/debug_toolbar/panels/signals.py\", line 39, in nav_subtitle\n        signals = self.get_stats()['signals']\n    KeyError: 'signals'\n    127.0.0.1 - - [03/Sep/2014 10:23:34] \"GET /__debug__/render_panel/?store_id=55c6f8d32b9f4acb9683af6172b94a01&panel_id=RequestHistoryPanel HTTP/1.1\" 500 -\n\n    Traceback (most recent call last):\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/contrib/staticfiles/handlers.py\", line 67, in __call__\n        return self.application(environ, start_response)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/core/handlers/wsgi.py\", line 206, in __call__\n        response = self.get_response(request)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/core/handlers/base.py\", line 194, in get_response\n        response = self.handle_uncaught_exception(request, resolver, sys.exc_info())\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/core/handlers/base.py\", line 229, in handle_uncaught_exception\n        return debug.technical_500_response(request, *exc_info)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django_extensions/management/technical_response.py\", line 5, in null_technical_500_response\n        six.reraise(exc_type, exc_value, tb)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/six.py\", line 611, in reraise\n        raise value\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/core/handlers/base.py\", line 105, in get_response\n        response = middleware_method(request, callback, callback_args, callback_kwargs)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/debug_toolbar/middleware.py\", line 74, in process_view\n        response = panel.process_view(request, view_func, view_args, view_kwargs)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/ddt_request_history/panels/request_history.py\", line 72, in process_view\n        return HttpResponse(self.content)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/ddt_request_history/panels/request_history.py\", line 117, in content\n        return t.render(Context({'toolbars': toolbars}))\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/base.py\", line 140, in render\n        return self._render(context)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/test/utils.py\", line 85, in instrumented_test_render\n        return self.nodelist.render(context)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/base.py\", line 840, in render\n        bit = self.render_node(node, context)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/debug.py\", line 78, in render_node\n        return node.render(context)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/defaulttags.py\", line 196, in render\n        nodelist.append(node.render(context))\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/defaulttags.py\", line 196, in render\n        nodelist.append(node.render(context))\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/debug.py\", line 88, in render\n        output = self.filter_expression.resolve(context)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/base.py\", line 585, in resolve\n        obj = self.var.resolve(context)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/base.py\", line 735, in resolve\n        value = self._resolve_lookup(context)\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/django/template/base.py\", line 789, in _resolve_lookup\n        current = current()\n      File \"/home/arsham/environments/p3.4/lib/python3.4/site-packages/debug_toolbar/panels/signals.py\", line 39, in nav_subtitle\n        signals = self.get_stats()['signals']\n    KeyError: 'signals'\n```\n\nThanks\n", "performed_via_github_app": null, "score": 1.0}]}