{"total_count": 9, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/googleapis/python-asset/issues/73", "repository_url": "https://api.github.com/repos/googleapis/python-asset", "labels_url": "https://api.github.com/repos/googleapis/python-asset/issues/73/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-asset/issues/73/comments", "events_url": "https://api.github.com/repos/googleapis/python-asset/issues/73/events", "html_url": "https://github.com/googleapis/python-asset/issues/73", "id": 676832241, "node_id": "MDU6SXNzdWU2NzY4MzIyNDE=", "number": 73, "title": "Synthesis failed for python-asset", "user": {"login": "yoshi-automation", "id": 44816363, "node_id": "MDQ6VXNlcjQ0ODE2MzYz", "avatar_url": "https://avatars1.githubusercontent.com/u/44816363?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yoshi-automation", "html_url": "https://github.com/yoshi-automation", "followers_url": "https://api.github.com/users/yoshi-automation/followers", "following_url": "https://api.github.com/users/yoshi-automation/following{/other_user}", "gists_url": "https://api.github.com/users/yoshi-automation/gists{/gist_id}", "starred_url": "https://api.github.com/users/yoshi-automation/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yoshi-automation/subscriptions", "organizations_url": "https://api.github.com/users/yoshi-automation/orgs", "repos_url": "https://api.github.com/users/yoshi-automation/repos", "events_url": "https://api.github.com/users/yoshi-automation/events{/privacy}", "received_events_url": "https://api.github.com/users/yoshi-automation/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814747206, "node_id": "MDU6TGFiZWwxODE0NzQ3MjA2", "url": "https://api.github.com/repos/googleapis/python-asset/labels/api:%20cloudasset", "name": "api: cloudasset", "color": "97ad3f", "default": false, "description": "Issues related to the Cloud Asset Inventory API."}, {"id": 1840714553, "node_id": "MDU6TGFiZWwxODQwNzE0NTUz", "url": "https://api.github.com/repos/googleapis/python-asset/labels/autosynth%20failure", "name": "autosynth failure", "color": "ededed", "default": false, "description": null}, {"id": 1814749014, "node_id": "MDU6TGFiZWwxODE0NzQ5MDE0", "url": "https://api.github.com/repos/googleapis/python-asset/labels/priority:%20p1", "name": "priority: p1", "color": "ffa03e", "default": false, "description": "Medium priority. Will be fixed prior to next release."}, {"id": 1814748903, "node_id": "MDU6TGFiZWwxODE0NzQ4OTAz", "url": "https://api.github.com/repos/googleapis/python-asset/labels/type:%20bug", "name": "type: bug", "color": "db4437", "default": false, "description": "Error or flaw in code with unintended results or allowing sub-optimal usage patterns."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-08-11T12:21:05Z", "updated_at": "2020-08-12T12:23:13Z", "closed_at": "2020-08-12T12:23:13Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Hello! Autosynth couldn't regenerate python-asset. :broken_heart:\n\nHere's the output from running `synth.py`:\n\n```\n88d](https://www.github.com/googleapis/python-bigquery/commit/0d2a88d8072154cfc9152afd6d26a60ddcdfbc73))\n-   **bigquery:** expose date_as_object parameter to users ([#&#8203;150](https://www.github.com/googleapis/python-bigquery/issues/150)) ([a2d5ce9](https://www.github.com/googleapis/python-bigquery/commit/a2d5ce9e97992318d7dc85c51c053cab74e25a11))\n-   **bigquery:** expose date_as_object parameter to users ([#&#8203;150](https://www.github.com/googleapis/python-bigquery/issues/150)) ([cbd831e](https://www.github.com/googleapis/python-bigquery/commit/cbd831e08024a67148723afd49e1db085e0a862c))\n\n##### Bug Fixes\n\n-   dry run queries with DB API cursor ([#&#8203;128](https://www.github.com/googleapis/python-bigquery/issues/128)) ([bc33a67](https://www.github.com/googleapis/python-bigquery/commit/bc33a678a765f0232615aa2038b8cc67c88468a0))\n-   omit `NaN` values when uploading from `insert_rows_from_dataframe` ([#&#8203;170](https://www.github.com/googleapis/python-bigquery/issues/170)) ([f9f2f45](https://www.github.com/googleapis/python-bigquery/commit/f9f2f45bc009c03cd257441bd4b6beb1754e2177))\n\n##### Documentation\n\n-   **bigquery:** add client thread-safety documentation ([#&#8203;132](https://www.github.com/googleapis/python-bigquery/issues/132)) ([fce76b3](https://www.github.com/googleapis/python-bigquery/commit/fce76b3776472b1da798df862a3405e659e35bab))\n-   **bigquery:** add docstring for conflict exception ([#&#8203;171](https://www.github.com/googleapis/python-bigquery/issues/171)) ([9c3409b](https://www.github.com/googleapis/python-bigquery/commit/9c3409bb06218bf499620544f8e92802df0cce47))\n-   **bigquery:** consistent use of optional keyword ([#&#8203;153](https://www.github.com/googleapis/python-bigquery/issues/153)) ([79d8c61](https://www.github.com/googleapis/python-bigquery/commit/79d8c61064cca18b596a24b6f738c7611721dd5c))\n-   **bigquery:** fix the broken docs ([#&#8203;139](https://www.github.com/googleapis/python-bigquery/issues/139)) ([3235255](https://www.github.com/googleapis/python-bigquery/commit/3235255cc5f483949f34d2e8ef13b372e8713782))\n\n</details>\n\n---\n\n### Renovate configuration\n\n:date: **Schedule**: At any time (no schedule defined).\n\n:vertical_traffic_light: **Automerge**: Disabled by config. Please merge this manually once you are satisfied.\n\n:recycle: **Rebasing**: Renovate will not automatically rebase this PR, because other commits have been found.\n\n:no_bell: **Ignore**: Close this PR and you won't be reminded about this update again.\n\n---\n\n - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box\n\n---\n\nThis PR has been generated by [WhiteSource Renovate](https://renovate.whitesourcesoftware.com). View repository job log [here](https://app.renovatebot.com/dashboard#googleapis/python-asset).\n\nSource-Author: WhiteSource Renovate <bot@renovateapp.com>\nSource-Date: Mon Aug 10 19:06:03 2020 +0200\nSource-Repo: googleapis/python-asset\nSource-Sha: 079064caeb4dded72e3b9e43ab56ff7b76603cc8\nSource-Link: https://github.com/googleapis/python-asset/commit/079064caeb4dded72e3b9e43ab56ff7b76603cc8\n[autosynth-self-0 71bf276] chore(deps): update dependency google-cloud-bigquery to v1.26.1\n 4 files changed, 27 insertions(+), 17 deletions(-)\n2020-08-11 05:20:39,824 autosynth [DEBUG] > Running: git reset --hard HEAD\nHEAD is now at 71bf276 chore(deps): update dependency google-cloud-bigquery to v1.26.1\n2020-08-11 05:20:39,832 autosynth [DEBUG] > Running: git checkout autosynth-self\nSwitched to branch 'autosynth-self'\n2020-08-11 05:20:39,840 autosynth [DEBUG] > Running: git diff HEAD..autosynth-self-0 -- . :(exclude)synth.metadata\n2020-08-11 05:20:39,845 autosynth [DEBUG] > Running: git diff HEAD autosynth-self-0\n2020-08-11 05:20:39,851 autosynth [DEBUG] > Running: git apply /tmpfs/tmp/tmpdxkz7cnc/autosynth-self-0.patch\n2020-08-11 05:20:39,855 autosynth [DEBUG] > Running: git add -A\n2020-08-11 05:20:39,862 autosynth [DEBUG] > Running: git status --porcelain\n2020-08-11 05:20:39,869 autosynth [DEBUG] > Running: git commit -m changes without context\n\n        autosynth cannot find the source of changes triggered by earlier changes in this\n        repository, or by version upgrades to tools such as linters.\n[autosynth-self 9066ad8] changes without context\n 4 files changed, 27 insertions(+), 17 deletions(-)\n2020-08-11 05:20:39,880 autosynth [DEBUG] > Running: git diff HEAD..autosynth-self-1 -- . :(exclude)synth.metadata\n2020-08-11 05:20:39,885 autosynth [DEBUG] > Running: git diff HEAD..autosynth-self-1 -- synth.metadata\n2020-08-11 05:20:39,889 autosynth [DEBUG] > Running: git push --force origin autosynth-self\nTo https://github.com/googleapis/python-asset.git\n + da4408d...9066ad8 autosynth-self -> autosynth-self (forced update)\n2020-08-11 05:20:43,613 autosynth [DEBUG] > Running: git log -1 --pretty=%b\n2020-08-11 05:20:53,863 autosynth [ERROR] > Error making request (502): Server Error\n2020-08-11 05:20:53,863 autosynth [DEBUG] > {'message': 'Server Error'}\n2020-08-11 05:20:53,863 autosynth [ERROR] > 502 Server Error: Bad Gateway for url: https://api.github.com/repos/googleapis/python-asset/pulls\n2020-08-11 05:20:53,997 autosynth [DEBUG] > Running: git checkout 079064caeb4dded72e3b9e43ab56ff7b76603cc8\nNote: checking out '079064caeb4dded72e3b9e43ab56ff7b76603cc8'.\n\nYou are in 'detached HEAD' state. You can look around, make experimental\nchanges and commit them, and you can discard any commits you make in this\nstate without impacting any branches by performing another checkout.\n\nIf you want to create a new branch to retain commits you create, you may\ndo so (now or later) by using -b with the checkout command again. Example:\n\n  git checkout -b <new-branch-name>\n\nHEAD is now at 079064c chore(deps): update dependency google-cloud-bigquery to v1.26.1 (#62)\n2020-08-11 05:20:54,005 autosynth [DEBUG] > Running: git checkout f1d8e6619ca2b9ebbc68c13af4ec5dba2803fc44\nHEAD is now at f1d8e66 feat: when obsolete file tracking gets flipped on, and there are no changes to the generated code, create a pull request anyway (#709)\n2020-08-11 05:20:54,011 autosynth [DEBUG] > Running: git branch -f autosynth-0\n2020-08-11 05:20:54,016 autosynth [DEBUG] > Running: git checkout autosynth-0\nSwitched to branch 'autosynth-0'\n2020-08-11 05:20:54,021 autosynth [DEBUG] > Running: git merge --ff-only autosynth-self-0\nUpdating 079064c..71bf276\nFast-forward\n .../services/asset_service/async_client.py         |  4 ++--\n .../services/asset_service/transports/base.py      |  4 ++--\n samples/snippets/noxfile.py                        | 26 ++++++++++++----------\n synth.metadata                                     | 10 ++++++++-\n 4 files changed, 27 insertions(+), 17 deletions(-)\n2020-08-11 05:20:54,032 autosynth [DEBUG] > Running: git reset --hard HEAD\nHEAD is now at 71bf276 chore(deps): update dependency google-cloud-bigquery to v1.26.1\n2020-08-11 05:20:54,039 autosynth [DEBUG] > Running: git checkout autosynth\nSwitched to branch 'autosynth'\n2020-08-11 05:20:54,046 autosynth [DEBUG] > Running: git diff HEAD..autosynth-0 -- . :(exclude)synth.metadata\n2020-08-11 05:20:54,052 autosynth [DEBUG] > Running: git diff HEAD autosynth-0\n2020-08-11 05:20:54,057 autosynth [DEBUG] > Running: git apply /tmpfs/tmp/tmpdxkz7cnc/autosynth-0.patch\n2020-08-11 05:20:54,061 autosynth [DEBUG] > Running: git add -A\n2020-08-11 05:20:54,067 autosynth [DEBUG] > Running: git status --porcelain\n2020-08-11 05:20:54,074 autosynth [DEBUG] > Running: git commit -m changes without context\n\n        autosynth cannot find the source of changes triggered by earlier changes in this\n        repository, or by version upgrades to tools such as linters.\n[autosynth b54e052] changes without context\n 4 files changed, 27 insertions(+), 17 deletions(-)\n2020-08-11 05:20:54,083 autosynth [DEBUG] > Running: git diff autosynth-0..autosynth-9 -- . :(exclude)synth.metadata\n2020-08-11 05:20:54,088 autosynth [DEBUG] > Running: git diff autosynth-0..autosynth-9 -- synth.metadata\n2020-08-11 05:20:54,092 autosynth [DEBUG] > Running: git push --force origin autosynth\nTo https://github.com/googleapis/python-asset.git\n + d4eddb6...b54e052 autosynth -> autosynth (forced update)\n2020-08-11 05:20:57,794 autosynth [DEBUG] > Running: git log -1 --pretty=%b\n2020-08-11 05:21:03,988 autosynth [DEBUG] > Running: git clean -fdx\nRemoving .nox/\nRemoving __pycache__/\nTraceback (most recent call last):\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 690, in <module>\n    main()\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 539, in main\n    return _inner_main(temp_dir)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 670, in _inner_main\n    commit_count = synthesize_loop(x, multiple_prs, change_pusher, synthesizer)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 403, in synthesize_loop\n    fork.push_changes(change_pusher)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 304, in push_changes\n    pr = change_pusher.push_changes(self.commit_count, self.branch, pr_title)\n  File \"/tmpfs/src/github/synthtool/autosynth/change_pusher.py\", line 103, in push_changes\n    self._repository, branch=branch, title=pr_title, body=new_body,\n  File \"/tmpfs/src/github/synthtool/autosynth/github.py\", line 94, in create_pull_request\n    return cast(Dict, _get_json_or_raise_exception(response))\n  File \"/tmpfs/src/github/synthtool/autosynth/github.py\", line 488, in _get_json_or_raise_exception\n    response.raise_for_status()\n  File \"/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/requests/models.py\", line 941, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://api.github.com/repos/googleapis/python-asset/pulls\n\n```\n\nGoogle internal developers can see the full log [here](http://sponge2/results/invocations/196f8a04-9215-4923-887e-d554ded632e7/targets/github%2Fsynthtool;config=default/tests;query=python-asset;failed=false).\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-asset/issues/66", "repository_url": "https://api.github.com/repos/googleapis/python-asset", "labels_url": "https://api.github.com/repos/googleapis/python-asset/issues/66/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-asset/issues/66/comments", "events_url": "https://api.github.com/repos/googleapis/python-asset/issues/66/events", "html_url": "https://github.com/googleapis/python-asset/issues/66", "id": 673766485, "node_id": "MDU6SXNzdWU2NzM3NjY0ODU=", "number": 66, "title": "testing: A flake in quickstart_listassets_test: test_list_assets", "user": {"login": "tmatsuo", "id": 41815, "node_id": "MDQ6VXNlcjQxODE1", "avatar_url": "https://avatars2.githubusercontent.com/u/41815?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tmatsuo", "html_url": "https://github.com/tmatsuo", "followers_url": "https://api.github.com/users/tmatsuo/followers", "following_url": "https://api.github.com/users/tmatsuo/following{/other_user}", "gists_url": "https://api.github.com/users/tmatsuo/gists{/gist_id}", "starred_url": "https://api.github.com/users/tmatsuo/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tmatsuo/subscriptions", "organizations_url": "https://api.github.com/users/tmatsuo/orgs", "repos_url": "https://api.github.com/users/tmatsuo/repos", "events_url": "https://api.github.com/users/tmatsuo/events{/privacy}", "received_events_url": "https://api.github.com/users/tmatsuo/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814747206, "node_id": "MDU6TGFiZWwxODE0NzQ3MjA2", "url": "https://api.github.com/repos/googleapis/python-asset/labels/api:%20cloudasset", "name": "api: cloudasset", "color": "97ad3f", "default": false, "description": "Issues related to the Cloud Asset Inventory API."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-08-05T18:45:03Z", "updated_at": "2020-08-06T07:46:52Z", "closed_at": "2020-08-06T07:46:52Z", "author_association": "MEMBER", "active_lock_reason": null, "body": "See:\r\nhttps://github.com/GoogleCloudPlatform/python-docs-samples/issues/4399\r\n\r\nFiltering the query with `\"bigquery.googleapis.com/Table\"` should stabilize the test.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-asset/issues/65", "repository_url": "https://api.github.com/repos/googleapis/python-asset", "labels_url": "https://api.github.com/repos/googleapis/python-asset/issues/65/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-asset/issues/65/comments", "events_url": "https://api.github.com/repos/googleapis/python-asset/issues/65/events", "html_url": "https://github.com/googleapis/python-asset/issues/65", "id": 673521689, "node_id": "MDU6SXNzdWU2NzM1MjE2ODk=", "number": 65, "title": "Synthesis failed for python-asset", "user": {"login": "yoshi-automation", "id": 44816363, "node_id": "MDQ6VXNlcjQ0ODE2MzYz", "avatar_url": "https://avatars1.githubusercontent.com/u/44816363?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yoshi-automation", "html_url": "https://github.com/yoshi-automation", "followers_url": "https://api.github.com/users/yoshi-automation/followers", "following_url": "https://api.github.com/users/yoshi-automation/following{/other_user}", "gists_url": "https://api.github.com/users/yoshi-automation/gists{/gist_id}", "starred_url": "https://api.github.com/users/yoshi-automation/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yoshi-automation/subscriptions", "organizations_url": "https://api.github.com/users/yoshi-automation/orgs", "repos_url": "https://api.github.com/users/yoshi-automation/repos", "events_url": "https://api.github.com/users/yoshi-automation/events{/privacy}", "received_events_url": "https://api.github.com/users/yoshi-automation/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814747206, "node_id": "MDU6TGFiZWwxODE0NzQ3MjA2", "url": "https://api.github.com/repos/googleapis/python-asset/labels/api:%20cloudasset", "name": "api: cloudasset", "color": "97ad3f", "default": false, "description": "Issues related to the Cloud Asset Inventory API."}, {"id": 1840714553, "node_id": "MDU6TGFiZWwxODQwNzE0NTUz", "url": "https://api.github.com/repos/googleapis/python-asset/labels/autosynth%20failure", "name": "autosynth failure", "color": "ededed", "default": false, "description": null}, {"id": 1814749014, "node_id": "MDU6TGFiZWwxODE0NzQ5MDE0", "url": "https://api.github.com/repos/googleapis/python-asset/labels/priority:%20p1", "name": "priority: p1", "color": "ffa03e", "default": false, "description": "Medium priority. Will be fixed prior to next release."}, {"id": 1814748903, "node_id": "MDU6TGFiZWwxODE0NzQ4OTAz", "url": "https://api.github.com/repos/googleapis/python-asset/labels/type:%20bug", "name": "type: bug", "color": "db4437", "default": false, "description": "Error or flaw in code with unintended results or allowing sub-optimal usage patterns."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-08-05T13:01:06Z", "updated_at": "2020-08-06T12:21:07Z", "closed_at": "2020-08-06T12:21:07Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Hello! Autosynth couldn't regenerate python-asset. :broken_heart:\n\nHere's the output from running `synth.py`:\n\n```\nsynthtool/python-asset/synth.py.\nOn branch autosynth-1\nnothing to commit, working tree clean\n2020-08-05 06:00:50,647 synthtool [DEBUG] > Using precloned repo /home/kbuilder/.cache/synthtool/synthtool\n2020-08-05 06:00:50,652 synthtool [DEBUG] > Ensuring dependencies.\n2020-08-05 06:00:50,661 synthtool [DEBUG] > Using precloned repo /home/kbuilder/.cache/synthtool/synthtool\n2020-08-05 06:00:50,665 synthtool [DEBUG] > Cloning googleapis.\n2020-08-05 06:00:51,020 synthtool [DEBUG] > Generating code for: //google/cloud/asset/v1beta1:asset-v1beta1-py.\n2020-08-05 06:00:53,061 synthtool [SUCCESS] > Generated code into /tmpfs/tmp/tmpn1wlfem6.\n2020-08-05 06:00:53,104 synthtool [DEBUG] > Generating code for: //google/cloud/asset/v1p1beta1:asset-v1p1beta1-py.\n2020-08-05 06:00:55,152 synthtool [SUCCESS] > Generated code into /tmpfs/tmp/tmp7ymxypdo.\n2020-08-05 06:00:55,195 synthtool [DEBUG] > Generating code for: //google/cloud/asset/v1p2beta1:asset-v1p2beta1-py.\n2020-08-05 06:00:57,233 synthtool [SUCCESS] > Generated code into /tmpfs/tmp/tmpj69z1ch_.\n2020-08-05 06:00:57,275 synthtool [DEBUG] > Generating code for: //google/cloud/asset/v1p4beta1:asset-v1p4beta1-py.\n2020-08-05 06:00:59,566 synthtool [SUCCESS] > Generated code into /tmpfs/tmp/tmp7kqdn4ne.\n2020-08-05 06:00:59,614 synthtool [DEBUG] > Generating code for: //google/cloud/asset/v1p5beta1:asset-v1p5beta1-py.\n2020-08-05 06:01:01,523 synthtool [SUCCESS] > Generated code into /tmpfs/tmp/tmpn9zd5rtu.\n2020-08-05 06:01:01,571 synthtool [DEBUG] > Generating code for: //google/cloud/asset/v1:asset-v1-py.\n2020-08-05 06:01:04,397 synthtool [SUCCESS] > Generated code into /tmpfs/tmp/tmpsjpnosvm.\n2020-08-05 06:01:04,448 synthtool [WARNING] > No replacements made in google/cloud/asset_v*/proto/assets_pb2.py for pattern from google.iam.v1 import policy_pb2 as, maybe replacement is no longer needed?\n2020-08-05 06:01:04,450 synthtool [WARNING] > No replacements made in google/cloud/asset_v*/proto/assets_pb2.py for pattern from google.iam.v1 import iam_policy_pb2_grpc as google_dot_iam_dot_v1_dot_policy__pb2, maybe replacement is no longer needed?\n2020-08-05 06:01:04,452 synthtool [WARNING] > No replacements made in google/cloud/asset_v*/proto/assets_pb2.py for pattern _ASSET\\.fields_by_name\\['iam_policy'\\]\\.message_type = google_dot_iam_dot_v1_dot_policy__pb2\\._POLICY, maybe replacement is no longer needed?\n2020-08-05 06:01:04,453 synthtool [WARNING] > No replacements made in google/cloud/asset_v*/proto/assets_pb2.py for pattern _IAMPOLICYSEARCHRESULT\\.fields_by_name\\['policy'\\]\\.message_type = google_dot_iam_dot_v1_dot_policy__pb2\\._POLICY, maybe replacement is no longer needed?\n2020-08-05 06:01:04,455 synthtool [WARNING] > No replacements made in google/cloud/asset_v*/proto/assets_pb2.py for pattern _IAMPOLICYANALYSISRESULT\\.fields_by_name\\['iam_binding'\\]\\.message_type = google_dot_iam_dot_v1_dot_policy__pb2\\._BINDING, maybe replacement is no longer needed?\n2020-08-05 06:01:04,457 synthtool [WARNING] > No replacements made in google/cloud/asset_v*/proto/assets_pb2.py for pattern           The full name of the asset. For example: ``//compute.googleapi\n          s.com/projects/my_project_123/zones/zone1/instances/instance1`\n          `. See `Resource Names <https://cloud.google.com/apis/design/r\n          esource_names#full_resource_name>`__ for more information.\n, maybe replacement is no longer needed?\n2020-08-05 06:01:04,460 synthtool [WARNING] > No replacements made in google/cloud/**/asset_service_client.py for pattern google-cloud-cloudasset, maybe replacement is no longer needed?\n2020-08-05 06:01:04,464 synthtool [WARNING] > No replacements made in google/cloud/**/proto/*_pb2.py for pattern '__doc__': \"\"\"Attributes:, maybe replacement is no longer needed?\n2020-08-05 06:01:04,465 synthtool [WARNING] > No replacements made in google/cloud/asset_v*/types.py for pattern from google\\.cloud\\.asset_(v.*)\\.proto import ((access_level_pb2)|(service_perimeter_pb2)|(access_policy_pb2)), maybe replacement is no longer needed?\n2020-08-05 06:01:04,466 synthtool [WARNING] > No replacements made in google/cloud/asset_v*/types.py for pattern from google\\.cloud\\.asset_v.*\\.proto import orgpolicy_pb2, maybe replacement is no longer needed?\n2020-08-05 06:01:04,467 synthtool [INFO] > Replaced '(def __init__\\\\()' in google/cloud/asset_v1/gapic/asset_service_client.py.\n2020-08-05 06:01:04,468 synthtool [INFO] > Replaced '(def __init__\\\\()' in google/cloud/asset_v1beta1/gapic/asset_service_client.py.\n2020-08-05 06:01:04,470 synthtool [WARNING] > No replacements made in ['google/cloud/asset_v1/gapic/asset_service_client.py', 'google/cloud/asset_v1beta1/gapic/asset_service_client.py'] for pattern def batch_get_assets_history\\(\n            self,\n            parent,\n            asset_names=None,\n            content_type=None,\n            read_time_window=None,\n            retry=google\\.api_core\\.gapic_v1\\.method\\.DEFAULT,\n            timeout=google\\.api_core\\.gapic_v1\\.method\\.DEFAULT,\n            metadata=None\\):, maybe replacement is no longer needed?\n2020-08-05 06:01:04,486 synthtool [DEBUG] > Wrote metadata to synth.metadata.\nTraceback (most recent call last):\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmpfs/src/github/synthtool/synthtool/__main__.py\", line 102, in <module>\n    main()\n  File \"/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/tmpfs/src/github/synthtool/env/lib/python3.6/site-packages/click/core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"/tmpfs/src/github/synthtool/synthtool/__main__.py\", line 94, in main\n    spec.loader.exec_module(synth_module)  # type: ignore\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/home/kbuilder/.cache/synthtool/python-asset/synth.py\", line 170, in <module>\n    raise Exception(\"Parameter order replace not made.\")\nException: Parameter order replace not made.\n2020-08-05 06:01:04,522 autosynth [ERROR] > Synthesis failed\n2020-08-05 06:01:04,522 autosynth [DEBUG] > Running: git reset --hard HEAD\nHEAD is now at 00b43e8 fix: limit asset types to avoid exceeding quota\n2020-08-05 06:01:04,528 autosynth [DEBUG] > Running: git checkout autosynth\nSwitched to branch 'autosynth'\n2020-08-05 06:01:04,533 autosynth [DEBUG] > Running: git clean -fdx\nRemoving __pycache__/\nRemoving docs/asset_v1/\nRemoving docs/asset_v1beta1/\nRemoving docs/asset_v1p1beta1/\nRemoving docs/asset_v1p2beta1/\nRemoving docs/asset_v1p4beta1/\nRemoving docs/asset_v1p5beta1/\nRemoving google/__pycache__/\nRemoving google/cloud/asset/\nRemoving google/cloud/asset_v1/py.typed\nRemoving google/cloud/asset_v1/services/\nRemoving google/cloud/asset_v1/types/\nRemoving google/cloud/asset_v1beta1/py.typed\nRemoving google/cloud/asset_v1beta1/services/\nRemoving google/cloud/asset_v1beta1/types/\nRemoving google/cloud/asset_v1p1beta1/py.typed\nRemoving google/cloud/asset_v1p1beta1/services/\nRemoving google/cloud/asset_v1p1beta1/types/\nRemoving google/cloud/asset_v1p2beta1/py.typed\nRemoving google/cloud/asset_v1p2beta1/services/\nRemoving google/cloud/asset_v1p2beta1/types/\nRemoving google/cloud/asset_v1p4beta1/py.typed\nRemoving google/cloud/asset_v1p4beta1/services/\nRemoving google/cloud/asset_v1p4beta1/types/\nRemoving google/cloud/asset_v1p5beta1/py.typed\nRemoving google/cloud/asset_v1p5beta1/services/\nRemoving google/cloud/asset_v1p5beta1/types/\nRemoving mypy.ini\nRemoving scripts/fixup_asset_v1_keywords.py\nRemoving scripts/fixup_asset_v1beta1_keywords.py\nRemoving scripts/fixup_asset_v1p1beta1_keywords.py\nRemoving scripts/fixup_asset_v1p2beta1_keywords.py\nRemoving scripts/fixup_asset_v1p4beta1_keywords.py\nRemoving scripts/fixup_asset_v1p5beta1_keywords.py\nRemoving tests/unit/gapic/asset_v1/\nRemoving tests/unit/gapic/asset_v1beta1/\nRemoving tests/unit/gapic/asset_v1p1beta1/\nRemoving tests/unit/gapic/asset_v1p2beta1/\nRemoving tests/unit/gapic/asset_v1p4beta1/\nRemoving tests/unit/gapic/asset_v1p5beta1/\nTraceback (most recent call last):\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 690, in <module>\n    main()\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 539, in main\n    return _inner_main(temp_dir)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 670, in _inner_main\n    commit_count = synthesize_loop(x, multiple_prs, change_pusher, synthesizer)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 375, in synthesize_loop\n    has_changes = toolbox.synthesize_version_in_new_branch(synthesizer, youngest)\n  File \"/tmpfs/src/github/synthtool/autosynth/synth.py\", line 273, in synthesize_version_in_new_branch\n    synthesizer.synthesize(synth_log_path, self.environ)\n  File \"/tmpfs/src/github/synthtool/autosynth/synthesizer.py\", line 120, in synthesize\n    synth_proc.check_returncode()  # Raise an exception.\n  File \"/home/kbuilder/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py\", line 389, in check_returncode\n    self.stderr)\nsubprocess.CalledProcessError: Command '['/tmpfs/src/github/synthtool/env/bin/python3', '-m', 'synthtool', '--metadata', 'synth.metadata', 'synth.py', '--']' returned non-zero exit status 1.\n\n```\n\nGoogle internal developers can see the full log [here](http://sponge2/results/invocations/4be218b6-dac7-413a-9b70-c61c140820cb/targets/github%2Fsynthtool;config=default/tests;query=python-asset;failed=false).\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-asset/issues/57", "repository_url": "https://api.github.com/repos/googleapis/python-asset", "labels_url": "https://api.github.com/repos/googleapis/python-asset/issues/57/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-asset/issues/57/comments", "events_url": "https://api.github.com/repos/googleapis/python-asset/issues/57/events", "html_url": "https://github.com/googleapis/python-asset/issues/57", "id": 665892789, "node_id": "MDU6SXNzdWU2NjU4OTI3ODk=", "number": 57, "title": "Does this api support partial response? ", "user": {"login": "misabhishek", "id": 68303371, "node_id": "MDQ6VXNlcjY4MzAzMzcx", "avatar_url": "https://avatars0.githubusercontent.com/u/68303371?v=4", "gravatar_id": "", "url": "https://api.github.com/users/misabhishek", "html_url": "https://github.com/misabhishek", "followers_url": "https://api.github.com/users/misabhishek/followers", "following_url": "https://api.github.com/users/misabhishek/following{/other_user}", "gists_url": "https://api.github.com/users/misabhishek/gists{/gist_id}", "starred_url": "https://api.github.com/users/misabhishek/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/misabhishek/subscriptions", "organizations_url": "https://api.github.com/users/misabhishek/orgs", "repos_url": "https://api.github.com/users/misabhishek/repos", "events_url": "https://api.github.com/users/misabhishek/events{/privacy}", "received_events_url": "https://api.github.com/users/misabhishek/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814747206, "node_id": "MDU6TGFiZWwxODE0NzQ3MjA2", "url": "https://api.github.com/repos/googleapis/python-asset/labels/api:%20cloudasset", "name": "api: cloudasset", "color": "97ad3f", "default": false, "description": "Issues related to the Cloud Asset Inventory API."}, {"id": 1814748971, "node_id": "MDU6TGFiZWwxODE0NzQ4OTcx", "url": "https://api.github.com/repos/googleapis/python-asset/labels/type:%20question", "name": "type: question", "color": "c5def5", "default": false, "description": "Request for information or clarification. Not an issue."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2020-07-27T00:35:40Z", "updated_at": "2020-07-28T01:50:44Z", "closed_at": "2020-07-28T01:50:43Z", "author_association": "NONE", "active_lock_reason": null, "body": "I wanted to know if this api can provide partial response explained [here](https://github.com/googleapis/google-api-python-client/blob/master/docs/performance.md#partial-response-fields-parameter).\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-asset/issues/49", "repository_url": "https://api.github.com/repos/googleapis/python-asset", "labels_url": "https://api.github.com/repos/googleapis/python-asset/issues/49/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-asset/issues/49/comments", "events_url": "https://api.github.com/repos/googleapis/python-asset/issues/49/events", "html_url": "https://github.com/googleapis/python-asset/issues/49", "id": 644144947, "node_id": "MDU6SXNzdWU2NDQxNDQ5NDc=", "number": 49, "title": "Warning: a recent release failed", "user": {"login": "failure-checker[bot]", "id": 58094317, "node_id": "MDM6Qm90NTgwOTQzMTc=", "avatar_url": "https://avatars2.githubusercontent.com/in/47470?v=4", "gravatar_id": "", "url": "https://api.github.com/users/failure-checker%5Bbot%5D", "html_url": "https://github.com/apps/failure-checker", "followers_url": "https://api.github.com/users/failure-checker%5Bbot%5D/followers", "following_url": "https://api.github.com/users/failure-checker%5Bbot%5D/following{/other_user}", "gists_url": "https://api.github.com/users/failure-checker%5Bbot%5D/gists{/gist_id}", "starred_url": "https://api.github.com/users/failure-checker%5Bbot%5D/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/failure-checker%5Bbot%5D/subscriptions", "organizations_url": "https://api.github.com/users/failure-checker%5Bbot%5D/orgs", "repos_url": "https://api.github.com/users/failure-checker%5Bbot%5D/repos", "events_url": "https://api.github.com/users/failure-checker%5Bbot%5D/events{/privacy}", "received_events_url": "https://api.github.com/users/failure-checker%5Bbot%5D/received_events", "type": "Bot", "site_admin": false}, "labels": [{"id": 1814747206, "node_id": "MDU6TGFiZWwxODE0NzQ3MjA2", "url": "https://api.github.com/repos/googleapis/python-asset/labels/api:%20cloudasset", "name": "api: cloudasset", "color": "97ad3f", "default": false, "description": "Issues related to the Cloud Asset Inventory API."}, {"id": 1814748936, "node_id": "MDU6TGFiZWwxODE0NzQ4OTM2", "url": "https://api.github.com/repos/googleapis/python-asset/labels/type:%20process", "name": "type: process", "color": "c5def5", "default": false, "description": "A process-releated concern. May include testing, release, or the like."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-06-23T21:03:15Z", "updated_at": "2020-08-12T04:20:25Z", "closed_at": "2020-08-12T04:20:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "The release PR #46 is still in a pending state after several hours", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-asset/issues/42", "repository_url": "https://api.github.com/repos/googleapis/python-asset", "labels_url": "https://api.github.com/repos/googleapis/python-asset/issues/42/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-asset/issues/42/comments", "events_url": "https://api.github.com/repos/googleapis/python-asset/issues/42/events", "html_url": "https://github.com/googleapis/python-asset/issues/42", "id": 636409695, "node_id": "MDU6SXNzdWU2MzY0MDk2OTU=", "number": 42, "title": "Warning: a recent release failed", "user": {"login": "failure-checker[bot]", "id": 58094317, "node_id": "MDM6Qm90NTgwOTQzMTc=", "avatar_url": "https://avatars2.githubusercontent.com/in/47470?v=4", "gravatar_id": "", "url": "https://api.github.com/users/failure-checker%5Bbot%5D", "html_url": "https://github.com/apps/failure-checker", "followers_url": "https://api.github.com/users/failure-checker%5Bbot%5D/followers", "following_url": "https://api.github.com/users/failure-checker%5Bbot%5D/following{/other_user}", "gists_url": "https://api.github.com/users/failure-checker%5Bbot%5D/gists{/gist_id}", "starred_url": "https://api.github.com/users/failure-checker%5Bbot%5D/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/failure-checker%5Bbot%5D/subscriptions", "organizations_url": "https://api.github.com/users/failure-checker%5Bbot%5D/orgs", "repos_url": "https://api.github.com/users/failure-checker%5Bbot%5D/repos", "events_url": "https://api.github.com/users/failure-checker%5Bbot%5D/events{/privacy}", "received_events_url": "https://api.github.com/users/failure-checker%5Bbot%5D/received_events", "type": "Bot", "site_admin": false}, "labels": [{"id": 1814747206, "node_id": "MDU6TGFiZWwxODE0NzQ3MjA2", "url": "https://api.github.com/repos/googleapis/python-asset/labels/api:%20cloudasset", "name": "api: cloudasset", "color": "97ad3f", "default": false, "description": "Issues related to the Cloud Asset Inventory API."}, {"id": 1814748936, "node_id": "MDU6TGFiZWwxODE0NzQ4OTM2", "url": "https://api.github.com/repos/googleapis/python-asset/labels/type:%20process", "name": "type: process", "color": "c5def5", "default": false, "description": "A process-releated concern. May include testing, release, or the like."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2020-06-10T17:03:18Z", "updated_at": "2020-06-23T20:09:02Z", "closed_at": "2020-06-23T20:09:02Z", "author_association": "NONE", "active_lock_reason": null, "body": "The release PR #37 is still in a pending state after several hours", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-asset/issues/29", "repository_url": "https://api.github.com/repos/googleapis/python-asset", "labels_url": "https://api.github.com/repos/googleapis/python-asset/issues/29/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-asset/issues/29/comments", "events_url": "https://api.github.com/repos/googleapis/python-asset/issues/29/events", "html_url": "https://github.com/googleapis/python-asset/issues/29", "id": 614865116, "node_id": "MDU6SXNzdWU2MTQ4NjUxMTY=", "number": 29, "title": "Warning: a recent release failed", "user": {"login": "failure-checker[bot]", "id": 58094317, "node_id": "MDM6Qm90NTgwOTQzMTc=", "avatar_url": "https://avatars2.githubusercontent.com/in/47470?v=4", "gravatar_id": "", "url": "https://api.github.com/users/failure-checker%5Bbot%5D", "html_url": "https://github.com/apps/failure-checker", "followers_url": "https://api.github.com/users/failure-checker%5Bbot%5D/followers", "following_url": "https://api.github.com/users/failure-checker%5Bbot%5D/following{/other_user}", "gists_url": "https://api.github.com/users/failure-checker%5Bbot%5D/gists{/gist_id}", "starred_url": "https://api.github.com/users/failure-checker%5Bbot%5D/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/failure-checker%5Bbot%5D/subscriptions", "organizations_url": "https://api.github.com/users/failure-checker%5Bbot%5D/orgs", "repos_url": "https://api.github.com/users/failure-checker%5Bbot%5D/repos", "events_url": "https://api.github.com/users/failure-checker%5Bbot%5D/events{/privacy}", "received_events_url": "https://api.github.com/users/failure-checker%5Bbot%5D/received_events", "type": "Bot", "site_admin": false}, "labels": [{"id": 1814747206, "node_id": "MDU6TGFiZWwxODE0NzQ3MjA2", "url": "https://api.github.com/repos/googleapis/python-asset/labels/api:%20cloudasset", "name": "api: cloudasset", "color": "97ad3f", "default": false, "description": "Issues related to the Cloud Asset Inventory API."}, {"id": 1814748936, "node_id": "MDU6TGFiZWwxODE0NzQ4OTM2", "url": "https://api.github.com/repos/googleapis/python-asset/labels/type:%20process", "name": "type: process", "color": "c5def5", "default": false, "description": "A process-releated concern. May include testing, release, or the like."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-05-08T17:02:51Z", "updated_at": "2020-05-08T18:30:47Z", "closed_at": "2020-05-08T18:30:47Z", "author_association": "NONE", "active_lock_reason": null, "body": "The release PR #27 is still in a pending state after several hours", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-asset/issues/7", "repository_url": "https://api.github.com/repos/googleapis/python-asset", "labels_url": "https://api.github.com/repos/googleapis/python-asset/issues/7/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-asset/issues/7/comments", "events_url": "https://api.github.com/repos/googleapis/python-asset/issues/7/events", "html_url": "https://github.com/googleapis/python-asset/issues/7", "id": 563203968, "node_id": "MDU6SXNzdWU1NjMyMDM5Njg=", "number": 7, "title": "Synthesis failed for python-asset", "user": {"login": "yoshi-automation", "id": 44816363, "node_id": "MDQ6VXNlcjQ0ODE2MzYz", "avatar_url": "https://avatars1.githubusercontent.com/u/44816363?v=4", "gravatar_id": "", "url": "https://api.github.com/users/yoshi-automation", "html_url": "https://github.com/yoshi-automation", "followers_url": "https://api.github.com/users/yoshi-automation/followers", "following_url": "https://api.github.com/users/yoshi-automation/following{/other_user}", "gists_url": "https://api.github.com/users/yoshi-automation/gists{/gist_id}", "starred_url": "https://api.github.com/users/yoshi-automation/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/yoshi-automation/subscriptions", "organizations_url": "https://api.github.com/users/yoshi-automation/orgs", "repos_url": "https://api.github.com/users/yoshi-automation/repos", "events_url": "https://api.github.com/users/yoshi-automation/events{/privacy}", "received_events_url": "https://api.github.com/users/yoshi-automation/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814749144, "node_id": "MDU6TGFiZWwxODE0NzQ5MTQ0", "url": "https://api.github.com/repos/googleapis/python-asset/labels/:rotating_light:", "name": ":rotating_light:", "color": "FFFFFF", "default": false, "description": "This issue needs some love."}, {"id": 1840714553, "node_id": "MDU6TGFiZWwxODQwNzE0NTUz", "url": "https://api.github.com/repos/googleapis/python-asset/labels/autosynth%20failure", "name": "autosynth failure", "color": "ededed", "default": false, "description": null}, {"id": 1814749014, "node_id": "MDU6TGFiZWwxODE0NzQ5MDE0", "url": "https://api.github.com/repos/googleapis/python-asset/labels/priority:%20p1", "name": "priority: p1", "color": "ffa03e", "default": false, "description": "Medium priority. Will be fixed prior to next release."}, {"id": 1814748903, "node_id": "MDU6TGFiZWwxODE0NzQ4OTAz", "url": "https://api.github.com/repos/googleapis/python-asset/labels/type:%20bug", "name": "type: bug", "color": "db4437", "default": false, "description": "Error or flaw in code with unintended results or allowing sub-optimal usage patterns."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 14, "created_at": "2020-02-11T13:23:52Z", "updated_at": "2020-02-19T02:30:32Z", "closed_at": "2020-02-19T02:30:32Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Hello! Autosynth couldn't regenerate python-asset. :broken_heart:\n\nHere's the output from running `synth.py`:\n\n```\nCloning into 'working_repo'...\nSwitched to branch 'autosynth'\nRunning synthtool\n['/tmpfs/src/git/autosynth/env/bin/python3', '-m', 'synthtool', 'synth.py', '--']\nsynthtool > Executing /tmpfs/src/git/autosynth/working_repo/synth.py.\nsynthtool > Ensuring dependencies.\nsynthtool > Pulling artman image.\nlatest: Pulling from googleapis/artman\n0a01a72a686c: Pulling fs layer\ncc899a5544da: Pulling fs layer\n19197c550755: Pulling fs layer\n716d454e56b6: Pulling fs layer\n356bff9680f9: Pulling fs layer\ne9c3c22e42c0: Pulling fs layer\n942b7dc330dd: Pulling fs layer\n56709773ca4a: Pulling fs layer\n8170975fe908: Pulling fs layer\nd8b5c7fe7729: Pulling fs layer\ndccf1bbd0660: Pulling fs layer\n716d454e56b6: Waiting\n0f1049eb8f0b: Pulling fs layer\n356bff9680f9: Waiting\n0637b8e4edf2: Pulling fs layer\nfe441baf69db: Pulling fs layer\ne9c3c22e42c0: Waiting\n93bd4e7a0e34: Pulling fs layer\n69ac465d8b6d: Pulling fs layer\nff53b2ac7bd7: Pulling fs layer\n7c49755f75be: Pulling fs layer\n03847e8fcbe9: Pulling fs layer\n942b7dc330dd: Waiting\nb017baf7ee37: Pulling fs layer\nbfd64ffd417b: Pulling fs layer\n25de3dde113f: Pulling fs layer\n880ff89656a7: Pulling fs layer\n253833b214f0: Pulling fs layer\n6aff358b4b78: Pulling fs layer\nbdf245069246: Pulling fs layer\n5fa91c043e36: Pulling fs layer\na8dbf9c918af: Pulling fs layer\n56709773ca4a: Waiting\n7c49755f75be: Waiting\n8170975fe908: Waiting\n03847e8fcbe9: Waiting\nb017baf7ee37: Waiting\nbfd64ffd417b: Waiting\n25de3dde113f: Waiting\nd8b5c7fe7729: Waiting\n880ff89656a7: Waiting\ndccf1bbd0660: Waiting\n0f1049eb8f0b: Waiting\n253833b214f0: Waiting\n6aff358b4b78: Waiting\nbdf245069246: Waiting\n0637b8e4edf2: Waiting\n69ac465d8b6d: Waiting\nfe441baf69db: Waiting\nff53b2ac7bd7: Waiting\n5fa91c043e36: Waiting\na8dbf9c918af: Waiting\n93bd4e7a0e34: Waiting\ncc899a5544da: Verifying Checksum\ncc899a5544da: Download complete\n19197c550755: Verifying Checksum\n19197c550755: Download complete\n716d454e56b6: Download complete\n0a01a72a686c: Verifying Checksum\n0a01a72a686c: Download complete\n356bff9680f9: Verifying Checksum\n356bff9680f9: Download complete\n942b7dc330dd: Verifying Checksum\n942b7dc330dd: Download complete\n56709773ca4a: Verifying Checksum\n56709773ca4a: Download complete\n8170975fe908: Verifying Checksum\n8170975fe908: Download complete\nd8b5c7fe7729: Download complete\n0f1049eb8f0b: Verifying Checksum\n0f1049eb8f0b: Download complete\ndccf1bbd0660: Verifying Checksum\ndccf1bbd0660: Download complete\nfe441baf69db: Verifying Checksum\nfe441baf69db: Download complete\n0a01a72a686c: Pull complete\ne9c3c22e42c0: Verifying Checksum\ne9c3c22e42c0: Download complete\ncc899a5544da: Pull complete\n19197c550755: Pull complete\n716d454e56b6: Pull complete\n93bd4e7a0e34: Verifying Checksum\n93bd4e7a0e34: Download complete\n69ac465d8b6d: Verifying Checksum\n69ac465d8b6d: Download complete\n0637b8e4edf2: Verifying Checksum\n0637b8e4edf2: Download complete\nff53b2ac7bd7: Verifying Checksum\nff53b2ac7bd7: Download complete\n7c49755f75be: Verifying Checksum\n7c49755f75be: Download complete\nbfd64ffd417b: Verifying Checksum\nbfd64ffd417b: Download complete\n03847e8fcbe9: Verifying Checksum\n03847e8fcbe9: Download complete\n356bff9680f9: Pull complete\n880ff89656a7: Verifying Checksum\n880ff89656a7: Download complete\n253833b214f0: Verifying Checksum\n253833b214f0: Download complete\nb017baf7ee37: Verifying Checksum\nb017baf7ee37: Download complete\n6aff358b4b78: Verifying Checksum\n6aff358b4b78: Download complete\nbdf245069246: Verifying Checksum\nbdf245069246: Download complete\n5fa91c043e36: Verifying Checksum\n5fa91c043e36: Download complete\na8dbf9c918af: Download complete\n25de3dde113f: Verifying Checksum\n25de3dde113f: Download complete\ne9c3c22e42c0: Pull complete\n942b7dc330dd: Pull complete\n56709773ca4a: Pull complete\n8170975fe908: Pull complete\nd8b5c7fe7729: Pull complete\ndccf1bbd0660: Pull complete\n0f1049eb8f0b: Pull complete\n0637b8e4edf2: Pull complete\nfe441baf69db: Pull complete\n93bd4e7a0e34: Pull complete\n69ac465d8b6d: Pull complete\nff53b2ac7bd7: Pull complete\n7c49755f75be: Pull complete\n03847e8fcbe9: Pull complete\nb017baf7ee37: Pull complete\nbfd64ffd417b: Pull complete\n25de3dde113f: Pull complete\n880ff89656a7: Pull complete\n253833b214f0: Pull complete\n6aff358b4b78: Pull complete\nbdf245069246: Pull complete\n5fa91c043e36: Pull complete\na8dbf9c918af: Pull complete\nDigest: sha256:6aec9c34db0e4be221cdaf6faba27bdc07cfea846808b3d3b964dfce3a9a0f9b\nStatus: Downloaded newer image for googleapis/artman:latest\nsynthtool > Cloning googleapis.\nsynthtool > Running generator for google/cloud/asset/artman_cloudasset_v1beta1.yaml.\nsynthtool > Generated code into /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/asset-v1beta1.\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/cloud/asset/v1beta1/assets.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/asset-v1beta1/google/cloud/asset_v1beta1/proto/assets.proto\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/cloud/asset/v1beta1/asset_service.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/asset-v1beta1/google/cloud/asset_v1beta1/proto/asset_service.proto\nsynthtool > Placed proto files into /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/asset-v1beta1/google/cloud/asset_v1beta1/proto.\nsynthtool > Running generator for google/cloud/asset/artman_cloudasset_v1p2beta1.yaml.\nsynthtool > Generated code into /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/asset-v1p2beta1.\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/cloud/asset/v1p2beta1/assets.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/asset-v1p2beta1/google/cloud/asset_v1p2beta1/proto/assets.proto\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/cloud/asset/v1p2beta1/asset_service.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/asset-v1p2beta1/google/cloud/asset_v1p2beta1/proto/asset_service.proto\nsynthtool > Placed proto files into /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/asset-v1p2beta1/google/cloud/asset_v1p2beta1/proto.\nsynthtool > Running generator for google/cloud/asset/v1p1beta1/artman_cloudasset_v1p1beta1.yaml.\nsynthtool > Generated code into /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/asset-v1p1beta1.\nsynthtool > Placed proto files into /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/asset-v1p1beta1/google/cloud/asset_v1p1beta1/proto.\nsynthtool > Running generator for google/cloud/asset/artman_cloudasset_v1.yaml.\nsynthtool > Generated code into /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/asset-v1.\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/cloud/asset/v1/assets.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/asset-v1/google/cloud/asset_v1/proto/assets.proto\nsynthtool > Copy: /home/kbuilder/.cache/synthtool/googleapis/google/cloud/asset/v1/asset_service.proto to /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/asset-v1/google/cloud/asset_v1/proto/asset_service.proto\nsynthtool > Placed proto files into /home/kbuilder/.cache/synthtool/googleapis/artman-genfiles/python/asset-v1/google/cloud/asset_v1/proto.\nsynthtool > Replaced 'from google.iam.v1 import policy_pb2 as' in google/cloud/asset_v1beta1/proto/assets_pb2.py.\nsynthtool > Replaced 'from google.iam.v1 import policy_pb2 as' in google/cloud/asset_v1p2beta1/proto/assets_pb2.py.\nsynthtool > Replaced 'from google.iam.v1 import policy_pb2 as' in google/cloud/asset_v1p1beta1/proto/assets_pb2.py.\nsynthtool > Replaced 'from google.iam.v1 import policy_pb2 as' in google/cloud/asset_v1/proto/assets_pb2.py.\nsynthtool > Replaced 'from google.iam.v1 import iam_policy_pb2_grpc as google_dot_iam_dot_v1_dot_policy__pb2' in google/cloud/asset_v1beta1/proto/assets_pb2.py.\nsynthtool > Replaced 'from google.iam.v1 import iam_policy_pb2_grpc as google_dot_iam_dot_v1_dot_policy__pb2' in google/cloud/asset_v1p2beta1/proto/assets_pb2.py.\nsynthtool > Replaced 'from google.iam.v1 import iam_policy_pb2_grpc as google_dot_iam_dot_v1_dot_policy__pb2' in google/cloud/asset_v1p1beta1/proto/assets_pb2.py.\nsynthtool > Replaced 'from google.iam.v1 import iam_policy_pb2_grpc as google_dot_iam_dot_v1_dot_policy__pb2' in google/cloud/asset_v1/proto/assets_pb2.py.\nsynthtool > Replaced \"_ASSET\\\\.fields_by_name\\\\['iam_policy'\\\\]\\\\.message_type = google_dot_iam_dot_v1_dot_policy__pb2\\\\._POLICY\" in google/cloud/asset_v1beta1/proto/assets_pb2.py.\nsynthtool > Replaced \"_ASSET\\\\.fields_by_name\\\\['iam_policy'\\\\]\\\\.message_type = google_dot_iam_dot_v1_dot_policy__pb2\\\\._POLICY\" in google/cloud/asset_v1p2beta1/proto/assets_pb2.py.\nsynthtool > Replaced \"_ASSET\\\\.fields_by_name\\\\['iam_policy'\\\\]\\\\.message_type = google_dot_iam_dot_v1_dot_policy__pb2\\\\._POLICY\" in google/cloud/asset_v1/proto/assets_pb2.py.\nsynthtool > Replaced \"_IAMPOLICYSEARCHRESULT\\\\.fields_by_name\\\\['policy'\\\\]\\\\.message_type = google_dot_iam_dot_v1_dot_policy__pb2\\\\._POLICY\" in google/cloud/asset_v1p1beta1/proto/assets_pb2.py.\nsynthtool > Replaced '          The full name of the asset. For example: ``//compute.googleapi\\n          s.com/projects/my_project_123/zones/zone1/instances/instance1`\\n          `. See `Resource Names <https://cloud.google.com/apis/design/r\\n          esource_names#full_resource_name>`__ for more information.\\n' in google/cloud/asset_v1beta1/proto/assets_pb2.py.\nsynthtool > Replaced '          The full name of the asset. For example: ``//compute.googleapi\\n          s.com/projects/my_project_123/zones/zone1/instances/instance1`\\n          `. See `Resource Names <https://cloud.google.com/apis/design/r\\n          esource_names#full_resource_name>`__ for more information.\\n' in google/cloud/asset_v1p2beta1/proto/assets_pb2.py.\nsynthtool > Replaced '          The full name of the asset. For example: ``//compute.googleapi\\n          s.com/projects/my_project_123/zones/zone1/instances/instance1`\\n          `. See `Resource Names <https://cloud.google.com/apis/design/r\\n          esource_names#full_resource_name>`__ for more information.\\n' in google/cloud/asset_v1/proto/assets_pb2.py.\nsynthtool > No replacements made in google/cloud/**/asset_service_client.py for pattern google-cloud-cloudasset, maybe replacement is not longer needed?\nsynthtool > Replaced '__doc__\\\\s*=\\\\s*\"\"\"Attributes:' in google/cloud/asset_v1p2beta1/proto/asset_service_pb2.py.\nsynthtool > Replaced '__doc__\\\\s*=\\\\s*\"\"\"Attributes:' in google/cloud/asset_v1/proto/asset_service_pb2.py.\n.coveragerc\n.flake8\n.github/CONTRIBUTING.md\n.github/ISSUE_TEMPLATE/bug_report.md\n.github/ISSUE_TEMPLATE/feature_request.md\n.github/ISSUE_TEMPLATE/support_request.md\n.github/PULL_REQUEST_TEMPLATE.md\n.github/release-please.yml\n.gitignore\n.kokoro/build.sh\n.kokoro/continuous/common.cfg\n.kokoro/continuous/continuous.cfg\n.kokoro/docs/common.cfg\n.kokoro/docs/docs.cfg\n.kokoro/presubmit/common.cfg\n.kokoro/presubmit/presubmit.cfg\n.kokoro/publish-docs.sh\n.kokoro/release.sh\n.kokoro/release/common.cfg\n.kokoro/release/release.cfg\n.kokoro/trampoline.sh\nCODE_OF_CONDUCT.md\nCONTRIBUTING.rst\nLICENSE\nMANIFEST.in\ndocs/_static/custom.css\ndocs/_templates/layout.html\ndocs/conf.py.j2\nnoxfile.py.j2\nrenovate.json\nsetup.cfg\nRunning session blacken\nCreating virtual environment (virtualenv) using python3.6 in .nox/blacken\npip install black==19.3b0\nError: pip is not installed into the virtualenv, it is located at /tmpfs/src/git/autosynth/env/bin/pip. Pass external=True into run() to explicitly allow this.\nSession blacken failed.\nsynthtool > Failed executing nox -s blacken:\n\nNone\nsynthtool > Wrote metadata to synth.metadata.\nTraceback (most recent call last):\n  File \"/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/__main__.py\", line 99, in <module>\n    main()\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/__main__.py\", line 91, in main\n    spec.loader.exec_module(synth_module)  # type: ignore\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 205, in _call_with_frames_removed\n  File \"/tmpfs/src/git/autosynth/working_repo/synth.py\", line 115, in <module>\n    s.shell.run([\"nox\", \"-s\", \"blacken\"], hide_output=False)\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/shell.py\", line 39, in run\n    raise exc\n  File \"/tmpfs/src/git/autosynth/env/lib/python3.6/site-packages/synthtool/shell.py\", line 33, in run\n    encoding=\"utf-8\",\n  File \"/home/kbuilder/.pyenv/versions/3.6.1/lib/python3.6/subprocess.py\", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command '['nox', '-s', 'blacken']' returned non-zero exit status 1.\n\nSynthesis failed\n\n```\n\nGoogle internal developers can see the full log [here](https://sponge/0ad5873d-3057-4798-a0b0-db4db3218285).\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/googleapis/python-asset/issues/5", "repository_url": "https://api.github.com/repos/googleapis/python-asset", "labels_url": "https://api.github.com/repos/googleapis/python-asset/issues/5/labels{/name}", "comments_url": "https://api.github.com/repos/googleapis/python-asset/issues/5/comments", "events_url": "https://api.github.com/repos/googleapis/python-asset/issues/5/events", "html_url": "https://github.com/googleapis/python-asset/issues/5", "id": 561928880, "node_id": "MDU6SXNzdWU1NjE5Mjg4ODA=", "number": 5, "title": "System Tests Fail Due to Missing Local Dependencies", "user": {"login": "sid-dinesh94", "id": 9417605, "node_id": "MDQ6VXNlcjk0MTc2MDU=", "avatar_url": "https://avatars0.githubusercontent.com/u/9417605?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sid-dinesh94", "html_url": "https://github.com/sid-dinesh94", "followers_url": "https://api.github.com/users/sid-dinesh94/followers", "following_url": "https://api.github.com/users/sid-dinesh94/following{/other_user}", "gists_url": "https://api.github.com/users/sid-dinesh94/gists{/gist_id}", "starred_url": "https://api.github.com/users/sid-dinesh94/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sid-dinesh94/subscriptions", "organizations_url": "https://api.github.com/users/sid-dinesh94/orgs", "repos_url": "https://api.github.com/users/sid-dinesh94/repos", "events_url": "https://api.github.com/users/sid-dinesh94/events{/privacy}", "received_events_url": "https://api.github.com/users/sid-dinesh94/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1814747206, "node_id": "MDU6TGFiZWwxODE0NzQ3MjA2", "url": "https://api.github.com/repos/googleapis/python-asset/labels/api:%20cloudasset", "name": "api: cloudasset", "color": "97ad3f", "default": false, "description": "Issues related to the Cloud Asset Inventory API."}, {"id": 1814748923, "node_id": "MDU6TGFiZWwxODE0NzQ4OTIz", "url": "https://api.github.com/repos/googleapis/python-asset/labels/type:%20cleanup", "name": "type: cleanup", "color": "c5def5", "default": false, "description": "An internal cleanup or hygiene concern."}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-02-07T23:51:52Z", "updated_at": "2020-02-10T18:06:21Z", "closed_at": "2020-02-10T18:06:21Z", "author_association": "NONE", "active_lock_reason": null, "body": "This library was originally part of the google-cloud-python repository. The Noxfile has local dependencies such as '../api_core' . These need to be updated to point to their module names, I believe.\r\n\r\nWithout this, the System tests cannot build using Nox.", "performed_via_github_app": null, "score": 1.0}]}