{"total_count": 29, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/81", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/81/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/81/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/81/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/81", "id": 579116466, "node_id": "MDU6SXNzdWU1NzkxMTY0NjY=", "number": 81, "title": "execjs.RuntimeUnavailable: Could not find a JavaScript runtime", "user": {"login": "popmedd", "id": 26320024, "node_id": "MDQ6VXNlcjI2MzIwMDI0", "avatar_url": "https://avatars2.githubusercontent.com/u/26320024?v=4", "gravatar_id": "", "url": "https://api.github.com/users/popmedd", "html_url": "https://github.com/popmedd", "followers_url": "https://api.github.com/users/popmedd/followers", "following_url": "https://api.github.com/users/popmedd/following{/other_user}", "gists_url": "https://api.github.com/users/popmedd/gists{/gist_id}", "starred_url": "https://api.github.com/users/popmedd/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/popmedd/subscriptions", "organizations_url": "https://api.github.com/users/popmedd/orgs", "repos_url": "https://api.github.com/users/popmedd/repos", "events_url": "https://api.github.com/users/popmedd/events{/privacy}", "received_events_url": "https://api.github.com/users/popmedd/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-03-11T09:19:49Z", "updated_at": "2020-05-08T02:00:00Z", "closed_at": "2020-05-08T02:00:00Z", "author_association": "NONE", "active_lock_reason": null, "body": "File \"/usr/lib/python2.7/site-packages/PyExecJS-1.0.2-py2.7.egg/execjs/__init__.py\", line 121, in compile\r\n    return get().compile(source)\r\n  File \"/usr/lib/python2.7/site-packages/PyExecJS-1.0.2-py2.7.egg/execjs/__init__.py\", line 62, in get\r\n    return _auto_detect()\r\n  File \"/usr/lib/python2.7/site-packages/PyExecJS-1.0.2-py2.7.egg/execjs/__init__.py\", line 95, in _auto_detect\r\n    \"See https://github.com/sstephenson/execjs for a list of available runtimes.\")\r\nexecjs.RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/79", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/79/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/79/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/79/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/79", "id": 440394312, "node_id": "MDU6SXNzdWU0NDAzOTQzMTI=", "number": 79, "title": "why not support load remote JavaScript like Jquery or other website js", "user": {"login": "EchoShoot", "id": 18530670, "node_id": "MDQ6VXNlcjE4NTMwNjcw", "avatar_url": "https://avatars1.githubusercontent.com/u/18530670?v=4", "gravatar_id": "", "url": "https://api.github.com/users/EchoShoot", "html_url": "https://github.com/EchoShoot", "followers_url": "https://api.github.com/users/EchoShoot/followers", "following_url": "https://api.github.com/users/EchoShoot/following{/other_user}", "gists_url": "https://api.github.com/users/EchoShoot/gists{/gist_id}", "starred_url": "https://api.github.com/users/EchoShoot/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/EchoShoot/subscriptions", "organizations_url": "https://api.github.com/users/EchoShoot/orgs", "repos_url": "https://api.github.com/users/EchoShoot/repos", "events_url": "https://api.github.com/users/EchoShoot/events{/privacy}", "received_events_url": "https://api.github.com/users/EchoShoot/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2019-05-05T03:07:17Z", "updated_at": "2019-05-11T04:37:03Z", "closed_at": "2019-05-11T04:37:03Z", "author_association": "NONE", "active_lock_reason": null, "body": "just like:\r\nimport execjs\r\nxxx  = execjs.load('http://xxx.com/jquery-1.10.2.min.js')\r\n\r\nafter then we can use  \"$(\"#id\")\" easily to select element with jquery syntax", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/76", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/76/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/76/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/76/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/76", "id": 328114127, "node_id": "MDU6SXNzdWUzMjgxMTQxMjc=", "number": 76, "title": "unexpected token, a hard javascript to eval, how to solve this, thanks", "user": {"login": "sherry0429", "id": 11309831, "node_id": "MDQ6VXNlcjExMzA5ODMx", "avatar_url": "https://avatars2.githubusercontent.com/u/11309831?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sherry0429", "html_url": "https://github.com/sherry0429", "followers_url": "https://api.github.com/users/sherry0429/followers", "following_url": "https://api.github.com/users/sherry0429/following{/other_user}", "gists_url": "https://api.github.com/users/sherry0429/gists{/gist_id}", "starred_url": "https://api.github.com/users/sherry0429/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sherry0429/subscriptions", "organizations_url": "https://api.github.com/users/sherry0429/orgs", "repos_url": "https://api.github.com/users/sherry0429/repos", "events_url": "https://api.github.com/users/sherry0429/events{/privacy}", "received_events_url": "https://api.github.com/users/sherry0429/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-05-31T12:14:39Z", "updated_at": "2018-11-28T01:44:01Z", "closed_at": "2018-11-28T01:44:01Z", "author_association": "NONE", "active_lock_reason": null, "body": "thanks your nice work,\r\nnow i have a java script like this:\r\n`function test(){\r\nvar x = \"@window@May@pathname@__jsl_clearance@oM@Expires@toString@@q@length@search@@challenge@@1500@@RegExp@@@Array@else@D@@try@createElement@setTimeout@@@@31@Path@12@parseInt@captcha@https@match@@@a@@@g@Thu@fromCharCode@0xEDB88320@rOm9XFMtA3QKV7nYsPGT4lifyWwkq5vcjH2IdxUoCbhERLaz81DNB6@document@href@false@@cookie@@YI@new@split@2@41@join@B@@var@@@857@GMT@@return@@attachEvent@@@eval@1@if@36@e@onreadystatechange@d@f@@DOMContentLoaded@div@4@0xFF@charAt@@chars@while@catch@@@@charCodeAt@reverse@T@for@innerHTML@A@@DBZEYDM@@replace@18@8@toLowerCase@JgSe0upZ@46@addEventListener@@substr@@@function@0@@@@location@@@@@String@1527767201@firstChild@@7\".replace(/@*$/, \"\").split(\"@\"),\r\n    y = \"24 47=3r(){r('43.1k=43.4+43.c.3g(/[\\\\?|&]16-e/,\\\\'\\\\')',g);1j.1n='5=49.27|3s|'+(3r(){24 10=[3r(47){2a 47},3r(10){2a 10},3r(47){3a(24 10=3s;10<47.b;10++){47[10]=15(47[10]).8(2i)};2a 47.21('')}],47=[[-~[-~[]+2q]],((+!'')+1s+[[]][3s]),[-~!{}]+[~~{}],[-~!{}]+[-~[-~[]+2q]],[-~!{}]+(((+!'')<<(+!''))+[]+[]),[4c],[-~!{}]+[-~!{}],[-~!{}]+[4c],((-~[]+[~~!/!/])/[-~-~{}]+[]+[]),[-~!{}]+((+!'')+1s+[[]][3s]),[-~[((+!'')<<(+!''))-~(-~((-~{}|-~-~{})))]],(((+!'')<<(+!''))+((+!'')<<(+!''))+[]),[-~!{}]+[-~[((+!'')<<(+!''))-~(-~((-~{}|-~-~{})))]],(((+!'')<<(+!''))+[]+[]),[(+!'')+[(+[])]-((+!''))],[-~!{}]+[(+!'')+[(+[])]-((+!''))],[-~!{}]+((-~[]+[~~!/!/])/[-~-~{}]+[]+[]),[-~!{}],[-~!{}]+(((+!'')<<(+!''))+((+!'')<<(+!''))+[]),[~~{}]];3a(24 2b=3s;2b<47.b;2b++){47[2b]=10[[2g,1s,2g,3s,2g,1s,2g,1s,2g,1s,2g,1s,2g,1s,2g,1s,3s,2g,3s,2g][2b]](['n','3e%',[(((+!'')<<(+!''))+[]+[])+[~~{}]],[(((+!'')<<(+!''))+[]+[])+((-~[]+[~~!/!/])/[-~-~{}]+[]+[])],[(((+!'')<<(+!''))+[]+[])+[-~[((+!'')<<(+!''))-~(-~((-~{}|-~-~{})))]]],'3c','a',[[-~!{}]+[-~[-~[]+2q]]],'1p','22','6','4c','39',[(((+!'')<<(+!''))+[]+[])+(((+!'')<<(+!''))+((+!'')<<(+!''))+[])],((+!'')+1s+[[]][3s]),[~~{}],(((+!'')<<(+!''))+((+!'')<<(+!''))+[]),[[-~!{}]+((+!'')+1s+[[]][3s])],'4c',[[-~!{}]+[-~[((+!'')<<(+!''))-~(-~((-~{}|-~-~{})))]],(((+!'')<<(+!''))+[]+[])+[(+!'')+[(+[])]-((+!''))]]][47[2b]])};2a 47.21('')})()+';7=1f, 12-3-3h 14:3l:20 28;13=/;'};2h((3r(){p{2a !!2.3m;}33(2j){2a 1l;}})()){1j.3m('2o',47,1l)}m{1j.2c('2k',47)}\",\r\n    f = function(x, y) {\r\n        var a = 0,\r\n            b = 0,\r\n            c = 0;\r\n        x = x.split(\"\");\r\n        y = y || 99;\r\n        while ((a = x.shift()) && (b = a.charCodeAt(0) - 77.5)) c = (Math.abs(b) < 13 ? (b + 48.5) : parseInt(a, 36)) + y * c;\r\n        return c\r\n    },\r\n    z = f(y.match(/\\w/g).sort(function(x, y) {\r\n        return f(x) - f(y)\r\n    }).pop());\r\nwhile (z++) try {\r\n    y.replace(/\\b\\w+\\b/g, function(y) {\r\n        return x[f(y, z) - 1] || (\"_\" + y)\r\n    });\r\n    break\r\n} catch (_) {}\r\n}`\r\n\r\nyou can run it in chrome->develop tool->console, and it will output something,\r\n\r\ni use execjs like : execjs.eval(myjs)\r\n\r\nbut it raise exception: unexcept token var\r\n\r\nwhen i make this script like:\r\n\r\nfunction test(){\r\nscript above\r\n}\r\n\r\nit not raise exception anymore, but when i use execjs.eval or execjs.complie().call(), it output nothing.\r\n\r\ncan you tell me how to use execjs to execute a java script with variable and function ?\r\n\r\n\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/72", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/72/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/72/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/72/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/72", "id": 291118175, "node_id": "MDU6SXNzdWUyOTExMTgxNzU=", "number": 72, "title": "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)", "user": {"login": "steven7851", "id": 6252238, "node_id": "MDQ6VXNlcjYyNTIyMzg=", "avatar_url": "https://avatars1.githubusercontent.com/u/6252238?v=4", "gravatar_id": "", "url": "https://api.github.com/users/steven7851", "html_url": "https://github.com/steven7851", "followers_url": "https://api.github.com/users/steven7851/followers", "following_url": "https://api.github.com/users/steven7851/following{/other_user}", "gists_url": "https://api.github.com/users/steven7851/gists{/gist_id}", "starred_url": "https://api.github.com/users/steven7851/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/steven7851/subscriptions", "organizations_url": "https://api.github.com/users/steven7851/orgs", "repos_url": "https://api.github.com/users/steven7851/repos", "events_url": "https://api.github.com/users/steven7851/events{/privacy}", "received_events_url": "https://api.github.com/users/steven7851/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2018-01-24T08:12:26Z", "updated_at": "2018-01-25T02:59:07Z", "closed_at": "2018-01-25T02:59:07Z", "author_association": "NONE", "active_lock_reason": null, "body": "This js can run by node.js, but cannot run by PyExecJS with node.js.\r\n```python\r\nimport os\r\n\r\ntry:\r\n    import execjs\r\nexcept Exception as e:\r\n    print('PyExecJS import failed:', e)\r\n    exit()\r\n\r\nif execjs.get().name.lower().find('node.js') == -1:\r\n    print('node.js not found')\r\n    exit()\r\n\r\nos.environ['NODE_PATH'] = os.getcwd() + '/node_modules'\r\n#signer = execjs.compile(open(os.getcwd() + '/signer.js').read())\r\nsignerjs = '''\r\nfunction signer(roomId, time, did) {\r\n    const fs = require('fs')\r\n    const util = require('util')\r\n    const readFile = util.promisify(fs.readFile)\r\n    const FlashEmu = require('flash-emu')\r\n    FlashEmu.BUILTIN = 'node_modules/flash-emu/lib/builtin.abc'\r\n    FlashEmu.PLAYERGLOBAL = 'node_modules/flash-emu/lib/playerglobal.abc'\r\n    FlashEmu.setGlobalFlags({\r\n        enableDebug: false,\r\n        enableLog: false,\r\n        enableWarn: false,\r\n        enableError: false\r\n    })\r\n    const emu = new FlashEmu({\r\n        async readFile(filename) {\r\n            const buf = await readFile(filename)\r\n            return new Uint8Array(buf).buffer\r\n        }\r\n    })\r\n    const vm = emu.getVM()\r\n    emu.runSWF('douyu.swf', false).then(() => {\r\n        const vm = emu.getVM()\r\n        const CModule = vm.getProxy(emu.getProperty('sample.mp', 'CModule'))\r\n        const xx = vm.getProxy(emu.getPublicClass('mp'))\r\n        CModule.callProperty('startAsync')\r\n        console.log('sign', roomId, time, did)\r\n        let StreamSignDataPtr = CModule.callProperty('malloc', 4)\r\n        let outptr1 = CModule.callProperty('malloc', 4)\r\n        let datalen = xx.callProperty('sub_2', parseInt(roomId), parseInt(time), did.toString(), outptr1, StreamSignDataPtr)\r\n        let pSign = CModule.callProperty('read32', StreamSignDataPtr)\r\n        let sign = CModule.callProperty('readString', pSign, datalen)\r\n        let pOut = CModule.callProperty('read32', outptr1)\r\n        let out = CModule.callProperty('readString', pOut, 4)\r\n        CModule.callProperty('free', StreamSignDataPtr)\r\n        CModule.callProperty('free', outptr1)\r\n        console.log('sign result', sign, out)\r\n        return console.log('sign result', sign, out)\r\n    }).catch(e => console.error(e))\r\n}\r\n'''\r\nsigner = execjs.compile(signerjs)\r\nrid = '67373'\r\ntt = '25254787'\r\ndid = 'C509BCDFDD593B0082493A579FEE00AB'\r\nsigner.call('signer', rid, tt, did)\r\n\r\n```\r\n```\r\n$ python douyu.py\r\nTraceback (most recent call last):\r\n  File \"douyu.py\", line 60, in <module>\r\n    signer.call('signer', rid, tt, did)\r\n  File \"C:\\Users\\Tanjan\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\site-packages\\execjs\\_abstract_runtime_context.py\", line 37, in call\r\n    return self._call(name, *args)\r\n  File \"C:\\Users\\Tanjan\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\site-packages\\execjs\\_external_runtime.py\", line 92, in _call\r\n    return self._eval(\"{identifier}.apply(this, {args})\".format(identifier=identifier, args=args))\r\n  File \"C:\\Users\\Tanjan\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\site-packages\\execjs\\_external_runtime.py\", line 78, in _eval\r\n    return self.exec_(code)\r\n  File \"C:\\Users\\Tanjan\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\site-packages\\execjs\\_abstract_runtime_context.py\", line 18, in exec_\r\n    return self._exec_(source)\r\n  File \"C:\\Users\\Tanjan\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\site-packages\\execjs\\_external_runtime.py\", line 88, in _exec_\r\n    return self._extract_result(output)\r\n  File \"C:\\Users\\Tanjan\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\site-packages\\execjs\\_external_runtime.py\", line 159, in _extract_result\r\n    ret = json.loads(output_last_line)\r\n  File \"C:\\Users\\Tanjan\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\json\\__init__.py\", line 319, in loads\r\n    return _default_decoder.decode(s)\r\n  File \"C:\\Users\\Tanjan\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\json\\decoder.py\", line 339, in decode\r\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\r\n  File \"C:\\Users\\Tanjan\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\json\\decoder.py\", line 357, in raw_decode\r\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\r\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\r\n```\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/66", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/66/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/66/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/66/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/66", "id": 258454123, "node_id": "MDU6SXNzdWUyNTg0NTQxMjM=", "number": 66, "title": "Upgrade/unpin six", "user": {"login": "href", "id": 273163, "node_id": "MDQ6VXNlcjI3MzE2Mw==", "avatar_url": "https://avatars1.githubusercontent.com/u/273163?v=4", "gravatar_id": "", "url": "https://api.github.com/users/href", "html_url": "https://github.com/href", "followers_url": "https://api.github.com/users/href/followers", "following_url": "https://api.github.com/users/href/following{/other_user}", "gists_url": "https://api.github.com/users/href/gists{/gist_id}", "starred_url": "https://api.github.com/users/href/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/href/subscriptions", "organizations_url": "https://api.github.com/users/href/orgs", "repos_url": "https://api.github.com/users/href/repos", "events_url": "https://api.github.com/users/href/events{/privacy}", "received_events_url": "https://api.github.com/users/href/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-09-18T11:57:08Z", "updated_at": "2017-10-15T09:02:56Z", "closed_at": "2017-10-15T09:02:56Z", "author_association": "NONE", "active_lock_reason": null, "body": "[Six](https://pypi.python.org/pypi/six) released a new version (`1.11.0`). PyExecJS's version is pinned to the previous version (`1.10.0`). Is there a reason why it is pinned to this exact version?\r\n\r\nAs a result this package is incompatible with any package that requires a six version greater than `1.10.0`.\r\n\r\nWould it be possible to change the pin to something more forgiving, like `six>=1.10.0`?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/64", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/64/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/64/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/64/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/64", "id": 217805477, "node_id": "MDU6SXNzdWUyMTc4MDU0Nzc=", "number": 64, "title": "TypeError", "user": {"login": "whyname", "id": 8568144, "node_id": "MDQ6VXNlcjg1NjgxNDQ=", "avatar_url": "https://avatars3.githubusercontent.com/u/8568144?v=4", "gravatar_id": "", "url": "https://api.github.com/users/whyname", "html_url": "https://github.com/whyname", "followers_url": "https://api.github.com/users/whyname/followers", "following_url": "https://api.github.com/users/whyname/following{/other_user}", "gists_url": "https://api.github.com/users/whyname/gists{/gist_id}", "starred_url": "https://api.github.com/users/whyname/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/whyname/subscriptions", "organizations_url": "https://api.github.com/users/whyname/orgs", "repos_url": "https://api.github.com/users/whyname/repos", "events_url": "https://api.github.com/users/whyname/events{/privacy}", "received_events_url": "https://api.github.com/users/whyname/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2017-03-29T08:46:13Z", "updated_at": "2017-08-20T10:17:59Z", "closed_at": "2017-08-20T10:17:59Z", "author_association": "NONE", "active_lock_reason": null, "body": "execjs._exceptions.ProgramError: TypeError: \u5bf9\u8c61\u4e0d\u652f\u6301\u6b64\u5c5e\u6027\u6216\u65b9\u6cd5\r\npython2.7\uff0cwin7 ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/63", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/63/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/63/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/63/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/63", "id": 189498687, "node_id": "MDU6SXNzdWUxODk0OTg2ODc=", "number": 63, "title": "ProgramError: <exception str() failed> in cooperation with coffeescript", "user": {"login": "Timtam", "id": 1345878, "node_id": "MDQ6VXNlcjEzNDU4Nzg=", "avatar_url": "https://avatars2.githubusercontent.com/u/1345878?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Timtam", "html_url": "https://github.com/Timtam", "followers_url": "https://api.github.com/users/Timtam/followers", "following_url": "https://api.github.com/users/Timtam/following{/other_user}", "gists_url": "https://api.github.com/users/Timtam/gists{/gist_id}", "starred_url": "https://api.github.com/users/Timtam/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Timtam/subscriptions", "organizations_url": "https://api.github.com/users/Timtam/orgs", "repos_url": "https://api.github.com/users/Timtam/repos", "events_url": "https://api.github.com/users/Timtam/events{/privacy}", "received_events_url": "https://api.github.com/users/Timtam/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2016-11-15T20:31:06Z", "updated_at": "2017-09-17T02:48:47Z", "closed_at": "2017-09-17T02:48:47Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\r\n\r\nI wanted to use the coffeescript package, which uses this one in order to execute the coffeescript code, for compilation matters against my working coffee script files. They compile fine using the coffee tool via command line. But using coffeescript.compile() on them results in the following.\r\n\r\n>>> c2=coffeescript.compile(c)\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"C:\\Python27\\lib\\site-packages\\coffeescript\\__init__.py\", line 104, in compile\r\n    return _default_compiler().compile(script, bare=bare)\r\n  File \"C:\\Python27\\lib\\site-packages\\coffeescript\\__init__.py\", line 81, in compile\r\n    \"CoffeeScript.compile\", script, {'bare': bare})\r\n  File \"C:\\Python27\\lib\\site-packages\\execjs\\_abstract_runtime_context.py\", line 37, in call\r\n    return self._call(name, *args)\r\n  File \"C:\\Python27\\lib\\site-packages\\execjs\\_external_runtime.py\", line 87, in _call\r\n    return self._eval(\"{identifier}.apply(this, {args})\".format(identifier=identifier, args=args))\r\n  File \"C:\\Python27\\lib\\site-packages\\execjs\\_external_runtime.py\", line 73, in _eval\r\n    return self.exec_(code)\r\n  File \"C:\\Python27\\lib\\site-packages\\execjs\\_abstract_runtime_context.py\", line 18, in exec_\r\n    return self._exec_(source)\r\n  File \"C:\\Python27\\lib\\site-packages\\execjs\\_external_runtime.py\", line 83, in _exec_\r\n    return self._extract_result(output)\r\n  File \"C:\\Python27\\lib\\site-packages\\execjs\\_external_runtime.py\", line 165, in _extract_result\r\n    raise exceptions.ProgramError(value)\r\nexecjs._exceptions.ProgramError: <exception str() failed>\r\n\r\nI'm using Python 2.7.12 under Windows 10 Anniversary 64-bit. Since the problem occurs inside PyExecJS I thought it would match best here.\r\n\r\nAny idea where this comes from? If yes, any possibility to make these error messages kind of more informative? This doesn't tell me anything...\r\n\r\nBest Regards.\r\n\r\nToni", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/62", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/62/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/62/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/62/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/62", "id": 186885951, "node_id": "MDU6SXNzdWUxODY4ODU5NTE=", "number": 62, "title": "How do I capture console.log output?", "user": {"login": "dmr", "id": 128286, "node_id": "MDQ6VXNlcjEyODI4Ng==", "avatar_url": "https://avatars2.githubusercontent.com/u/128286?v=4", "gravatar_id": "", "url": "https://api.github.com/users/dmr", "html_url": "https://github.com/dmr", "followers_url": "https://api.github.com/users/dmr/followers", "following_url": "https://api.github.com/users/dmr/following{/other_user}", "gists_url": "https://api.github.com/users/dmr/gists{/gist_id}", "starred_url": "https://api.github.com/users/dmr/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dmr/subscriptions", "organizations_url": "https://api.github.com/users/dmr/orgs", "repos_url": "https://api.github.com/users/dmr/repos", "events_url": "https://api.github.com/users/dmr/events{/privacy}", "received_events_url": "https://api.github.com/users/dmr/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-11-02T18:38:13Z", "updated_at": "2017-09-17T02:45:44Z", "closed_at": "2017-09-17T02:45:44Z", "author_association": "NONE", "active_lock_reason": null, "body": "Is it possible to capture the output of a process?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/61", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/61/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/61/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/61/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/61", "id": 182617435, "node_id": "MDU6SXNzdWUxODI2MTc0MzU=", "number": 61, "title": "How do I include pyexecjs in a secure way?", "user": {"login": "dmr", "id": 128286, "node_id": "MDQ6VXNlcjEyODI4Ng==", "avatar_url": "https://avatars2.githubusercontent.com/u/128286?v=4", "gravatar_id": "", "url": "https://api.github.com/users/dmr", "html_url": "https://github.com/dmr", "followers_url": "https://api.github.com/users/dmr/followers", "following_url": "https://api.github.com/users/dmr/following{/other_user}", "gists_url": "https://api.github.com/users/dmr/gists{/gist_id}", "starred_url": "https://api.github.com/users/dmr/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/dmr/subscriptions", "organizations_url": "https://api.github.com/users/dmr/orgs", "repos_url": "https://api.github.com/users/dmr/repos", "events_url": "https://api.github.com/users/dmr/events{/privacy}", "received_events_url": "https://api.github.com/users/dmr/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2016-10-12T19:51:05Z", "updated_at": "2017-09-29T08:01:45Z", "closed_at": "2017-09-17T02:48:28Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm new to pyexecjs and want to use it to allow small user scripts.\n\nRight now I can use all the things my node environment offers me, i.e.\n\n```\nimport execjs\nctx = execjs.compile(\"const fs = require('fs'); const insecure = () => fs.readdirSync('.');\");\nctx.call(\"insecure\")\n```\n\nIs there a way to \"sandbox\" the node environment and only allow certain things?\n\nThank you for this project, it has been a pleasure to use so far :)\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/59", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/59/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/59/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/59/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/59", "id": 158554387, "node_id": "MDU6SXNzdWUxNTg1NTQzODc=", "number": 59, "title": "Cannot use custom node.js modules", "user": {"login": "hiviah", "id": 812173, "node_id": "MDQ6VXNlcjgxMjE3Mw==", "avatar_url": "https://avatars1.githubusercontent.com/u/812173?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hiviah", "html_url": "https://github.com/hiviah", "followers_url": "https://api.github.com/users/hiviah/followers", "following_url": "https://api.github.com/users/hiviah/following{/other_user}", "gists_url": "https://api.github.com/users/hiviah/gists{/gist_id}", "starred_url": "https://api.github.com/users/hiviah/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hiviah/subscriptions", "organizations_url": "https://api.github.com/users/hiviah/orgs", "repos_url": "https://api.github.com/users/hiviah/repos", "events_url": "https://api.github.com/users/hiviah/events{/privacy}", "received_events_url": "https://api.github.com/users/hiviah/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2016-06-05T13:27:49Z", "updated_at": "2017-09-16T08:29:23Z", "closed_at": "2017-09-16T08:29:23Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hope I am not overlooking something, but whenever I use \"require\" for some custom installed nodejs module, I get an exception `execjs._exceptions.ProgramError: Error: Cannot find module`. Is it for instance necessary to set paths somehow where modules would be searched?\n\nSimple test case with one module, [fastrpc](https://github.com/seznam/node-fastrpc):\n\nInstall the module `npm install fastrpc`\n\nTry this python code to invoke pyexecjs to invoke the module:\n\n```\n#!/usr/bin/env python\nimport execjs\nprint \"Engine name\", execjs.get().name\n\ncode = \"\"\"\nvar fastrpc = require('fastrpc');\n\nfunction frpc2json(string) {\n    var buffer = new Buffer(string, 'base64');\n    var bufferArray = new Uint8Array(buffer);\n    var decoded = fastrpc.parse(bufferArray);\n    return  JSON.stringify(decoded);\n}\n\"\"\"\n\nctx = execjs.compile(code)\nres = ctx.call(\"frpc2json\", 'yhECAWgRdXNlci5saXN0TWVzc2FnZXM7L1wfASAMbGFiZWwtaWQ6MjU4QAA4ZA==')\nprint res\n```\n\nResult:\n\n```\nEngine name Node.js (V8)\nTraceback (most recent call last):\n  File \"./cant_resolve_modules.py\", line 17, in <module>\n    res = ctx.call(\"frpc2json\", 'yhECAWgRdXNlci5saXN0TWVzc2FnZXM7L1wfASAMbGFiZWwtaWQ6MjU4QAA4ZA==')\n  File \"/home/ondro/.local/lib/python2.7/site-packages/execjs/_abstract_runtime_context.py\", line 37, in call\n    return self._call(name, *args)\n  File \"/home/ondro/.local/lib/python2.7/site-packages/execjs/_external_runtime.py\", line 87, in _call\n    return self._eval(\"{identifier}.apply(this, {args})\".format(identifier=identifier, args=args))\n  File \"/home/ondro/.local/lib/python2.7/site-packages/execjs/_external_runtime.py\", line 73, in _eval\n    return self.exec_(code)\n  File \"/home/ondro/.local/lib/python2.7/site-packages/execjs/_abstract_runtime_context.py\", line 18, in exec_\n    return self._exec_(source)\n  File \"/home/ondro/.local/lib/python2.7/site-packages/execjs/_external_runtime.py\", line 83, in _exec_\n    return self._extract_result(output)\n  File \"/home/ondro/.local/lib/python2.7/site-packages/execjs/_external_runtime.py\", line 165, in _extract_result\n    raise exceptions.ProgramError(value)\nexecjs._exceptions.ProgramError: Error: Cannot find module 'fastrpc'\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/58", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/58/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/58/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/58/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/58", "id": 156131017, "node_id": "MDU6SXNzdWUxNTYxMzEwMTc=", "number": 58, "title": "Send messages back to python.", "user": {"login": "BebeSparkelSparkel", "id": 10747532, "node_id": "MDQ6VXNlcjEwNzQ3NTMy", "avatar_url": "https://avatars2.githubusercontent.com/u/10747532?v=4", "gravatar_id": "", "url": "https://api.github.com/users/BebeSparkelSparkel", "html_url": "https://github.com/BebeSparkelSparkel", "followers_url": "https://api.github.com/users/BebeSparkelSparkel/followers", "following_url": "https://api.github.com/users/BebeSparkelSparkel/following{/other_user}", "gists_url": "https://api.github.com/users/BebeSparkelSparkel/gists{/gist_id}", "starred_url": "https://api.github.com/users/BebeSparkelSparkel/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/BebeSparkelSparkel/subscriptions", "organizations_url": "https://api.github.com/users/BebeSparkelSparkel/orgs", "repos_url": "https://api.github.com/users/BebeSparkelSparkel/repos", "events_url": "https://api.github.com/users/BebeSparkelSparkel/events{/privacy}", "received_events_url": "https://api.github.com/users/BebeSparkelSparkel/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2016-05-22T02:16:06Z", "updated_at": "2016-06-06T12:34:13Z", "closed_at": "2016-06-06T12:34:13Z", "author_association": "NONE", "active_lock_reason": null, "body": "Is it possible to receive messages from the js script like python-shell can https://github.com/extrabacon/python-shell?\nIt would be very helpful for debugging.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/49", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/49/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/49/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/49/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/49", "id": 150386676, "node_id": "MDU6SXNzdWUxNTAzODY2NzY=", "number": 49, "title": "import execjs fails with AttributeError", "user": {"login": "maxpmaxp", "id": 562792, "node_id": "MDQ6VXNlcjU2Mjc5Mg==", "avatar_url": "https://avatars2.githubusercontent.com/u/562792?v=4", "gravatar_id": "", "url": "https://api.github.com/users/maxpmaxp", "html_url": "https://github.com/maxpmaxp", "followers_url": "https://api.github.com/users/maxpmaxp/followers", "following_url": "https://api.github.com/users/maxpmaxp/following{/other_user}", "gists_url": "https://api.github.com/users/maxpmaxp/gists{/gist_id}", "starred_url": "https://api.github.com/users/maxpmaxp/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/maxpmaxp/subscriptions", "organizations_url": "https://api.github.com/users/maxpmaxp/orgs", "repos_url": "https://api.github.com/users/maxpmaxp/repos", "events_url": "https://api.github.com/users/maxpmaxp/events{/privacy}", "received_events_url": "https://api.github.com/users/maxpmaxp/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-04-22T14:39:59Z", "updated_at": "2016-05-08T04:17:50Z", "closed_at": "2016-05-08T04:17:50Z", "author_association": "NONE", "active_lock_reason": null, "body": "I have Python 2.7, PyExecJS-1.3.1, PhantomJS 2.1.1.\n\n```\n>>> import execjs\nTraceback (most recent call last):\n  File \"<console>\", line 1, in <module>\n  File \"/.../PyExecJS-1.3.1-py2.7.egg/execjs/__init__.py\", line 26, in <module>\n    import execjs._runtimes\n  File \"/...egg/execjs/_runtimes.py\", line 8, in <module>\n    import execjs._external_runtime as external_runtime\n  File \"/.../PyExecJS-1.3.1-py2.7.egg/execjs/_external_runtime.py\", line 15, in <module>\n    from execjs._abstract_runtime import AbstractRuntime\n  File \"/.../PyExecJS-1.3.1-py2.7.egg/execjs/_abstract_runtime.py\", line 6, in <module>\n    @six.add_metaclass(ABCMeta)\nAttributeError: 'module' object has no attribute 'add_metaclass'\n```\n\nIf I set `EXECJS_RUNTIME` explicitly to 'PhantomJS' the import fails with another `AttributeError`\n\n```\n>>> import os\n>>> os.environ[\"EXECJS_RUNTIME\"] = \"PhantomJS\"\n>>> import execjs\nTraceback (most recent call last):\n  File \"<console>\", line 1, in <module>\n  File \"/.../PyExecJS-1.3.1-py2.7.egg/execjs/__init__.py\", line 26, in <module>\n    import execjs._runtimes\n  File \"/.../execjs/_runtimes.py\", line 8, in <module>\n    import execjs._external_runtime as external_runtime\n  File \"/.../PyExecJS-1.3.1-py2.7.egg/execjs/_external_runtime.py\", line 12, in <module>\n    import execjs._json2 as _json2\nAttributeError: 'module' object has no attribute '_json2'\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/46", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/46/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/46/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/46/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/46", "id": 143307147, "node_id": "MDU6SXNzdWUxNDMzMDcxNDc=", "number": 46, "title": "module 'execjs' has no attribute 'RuntimeUnavailable'", "user": {"login": "criccomini", "id": 167569, "node_id": "MDQ6VXNlcjE2NzU2OQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/167569?v=4", "gravatar_id": "", "url": "https://api.github.com/users/criccomini", "html_url": "https://github.com/criccomini", "followers_url": "https://api.github.com/users/criccomini/followers", "following_url": "https://api.github.com/users/criccomini/following{/other_user}", "gists_url": "https://api.github.com/users/criccomini/gists{/gist_id}", "starred_url": "https://api.github.com/users/criccomini/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/criccomini/subscriptions", "organizations_url": "https://api.github.com/users/criccomini/orgs", "repos_url": "https://api.github.com/users/criccomini/repos", "events_url": "https://api.github.com/users/criccomini/events{/privacy}", "received_events_url": "https://api.github.com/users/criccomini/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-03-24T17:17:59Z", "updated_at": "2016-04-02T05:07:14Z", "closed_at": "2016-04-02T05:07:14Z", "author_association": "NONE", "active_lock_reason": null, "body": "Got this when running on a system that has no runtimes. Seems like the RuntimeUnavailable exception is missing.\n\n```\n[tests.udfs.test_el.TestElUdf.setup] Traceback (most recent call last):\n  File \"/usr/local/lib/python3.5/site-packages/nose/suite.py\", line 210, in run\n    self.setUp()\n  File \"/usr/local/lib/python3.5/site-packages/nose/suite.py\", line 293, in setUp\n    self.setupContext(ancestor)\n  File \"/usr/local/lib/python3.5/site-packages/nose/suite.py\", line 316, in setupContext\n    try_run(context, names)\n  File \"/usr/local/lib/python3.5/site-packages/nose/util.py\", line 471, in try_run\n    return func()\n  File \"/var/asdf/tests/udfs/test_el.py\", line 13, in setUpClass\n    cls.exact_row_match_udf = UdfTestHarness('el.js', 'exact_row_match')\n  File \"/var/asdf/tests/udfs/helper_udfs.py\", line 34, in __init__\n    self.udf = execjs.compile(self.udf_str)\n  File \"/usr/local/lib/python3.5/site-packages/execjs/__init__.py\", line 69, in compile\n    return get().compile(source)\n  File \"/usr/local/lib/python3.5/site-packages/execjs/_runtimes.py\", line 24, in get\n    return _auto_detect()\n  File \"/usr/local/lib/python3.5/site-packages/execjs/_runtimes.py\", line 56, in _auto_detect\n    raise execjs.RuntimeUnavailable(\"Could not find a JavaScript runtime.\")\nAttributeError: module 'execjs' has no attribute 'RuntimeUnavailable'\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/45", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/45/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/45/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/45/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/45", "id": 143304687, "node_id": "MDU6SXNzdWUxNDMzMDQ2ODc=", "number": 45, "title": "Print available runtimes doesn't work.", "user": {"login": "criccomini", "id": 167569, "node_id": "MDQ6VXNlcjE2NzU2OQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/167569?v=4", "gravatar_id": "", "url": "https://api.github.com/users/criccomini", "html_url": "https://github.com/criccomini", "followers_url": "https://api.github.com/users/criccomini/followers", "following_url": "https://api.github.com/users/criccomini/following{/other_user}", "gists_url": "https://api.github.com/users/criccomini/gists{/gist_id}", "starred_url": "https://api.github.com/users/criccomini/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/criccomini/subscriptions", "organizations_url": "https://api.github.com/users/criccomini/orgs", "repos_url": "https://api.github.com/users/criccomini/repos", "events_url": "https://api.github.com/users/criccomini/events{/privacy}", "received_events_url": "https://api.github.com/users/criccomini/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2016-03-24T17:09:31Z", "updated_at": "2016-03-26T08:06:00Z", "closed_at": "2016-03-26T08:06:00Z", "author_association": "NONE", "active_lock_reason": null, "body": "Print available runtimes doesn't work.\n\n```\n$ python --version\nPython 2.7.6\n\n$ python -m execjs --print-available-runtimes\nTraceback (most recent call last):\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 162, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/Users/chrisr/.virtual-env/asdf/lib/python2.7/site-packages/execjs/__main__.py\", line 57, in <module>\n    main()\n  File \"/Users/chrisr/.virtual-env/asdf/lib/python2.7/site-packages/execjs/__main__.py\", line 36, in main\n    opts = parser.parse_args()\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py\", line 1688, in parse_args\n    args, argv = self.parse_known_args(args, namespace)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py\", line 1720, in parse_known_args\n    namespace, args = self._parse_known_args(args, namespace)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py\", line 1926, in _parse_known_args\n    start_index = consume_optional(start_index)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py\", line 1866, in consume_optional\n    take_action(action, args, option_string)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.py\", line 1794, in take_action\n    action(self, namespace, argument_values, option_string)\n  File \"/Users/chrisr/.virtual-env/asdf/lib/python2.7/site-packages/execjs/__main__.py\", line 24, in __call__\n    buffer.write(name + \"\\n\")\nTypeError: unicode argument expected, got 'str'\n\n$ pip freeze | grep PyExec\nYou are using pip version 7.1.2, however version 8.1.1 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\nPyExecJS==1.3.0\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/41", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/41/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/41/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/41/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/41", "id": 141125598, "node_id": "MDU6SXNzdWUxNDExMjU1OTg=", "number": 41, "title": "Tests fail with spidermonkey==24.2.0-r3", "user": {"login": "jamesbroadhead", "id": 1382141, "node_id": "MDQ6VXNlcjEzODIxNDE=", "avatar_url": "https://avatars3.githubusercontent.com/u/1382141?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jamesbroadhead", "html_url": "https://github.com/jamesbroadhead", "followers_url": "https://api.github.com/users/jamesbroadhead/followers", "following_url": "https://api.github.com/users/jamesbroadhead/following{/other_user}", "gists_url": "https://api.github.com/users/jamesbroadhead/gists{/gist_id}", "starred_url": "https://api.github.com/users/jamesbroadhead/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jamesbroadhead/subscriptions", "organizations_url": "https://api.github.com/users/jamesbroadhead/orgs", "repos_url": "https://api.github.com/users/jamesbroadhead/repos", "events_url": "https://api.github.com/users/jamesbroadhead/events{/privacy}", "received_events_url": "https://api.github.com/users/jamesbroadhead/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2016-03-15T23:15:50Z", "updated_at": "2017-08-20T10:15:04Z", "closed_at": "2017-08-20T10:15:04Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "```\n$ python2.7 -V\nPython 2.7.10\n\n$ python2.7 test_execjs.py\n.............................FE....\n======================================================================\nERROR: test_exec (__main__.SpidermonkeyRuntimeTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"test_execjs.py\", line 41, in test_exec\n    self.assertEqual(\"\\u3042\", self.runtime.exec_('return \"\\u3042\"'))   # unicode char\n  File \"/home/jbo/checkouts/github/PyExecJS/execjs/_abstract_runtime.py\", line 8, in exec_\n    return self._exec_(source, cwd=cwd)\n  File \"/home/jbo/checkouts/github/PyExecJS/execjs/_external_runtime.py\", line 47, in _exec_\n    return self.Context(self, cwd=cwd).exec_(source)\n  File \"/home/jbo/checkouts/github/PyExecJS/execjs/_external_runtime.py\", line 92, in exec_\n    return self._extract_result(output)\n  File \"/home/jbo/checkouts/github/PyExecJS/execjs/_external_runtime.py\", line 137, in _extract_result\n    output = output.decode(self._runtime._encoding)\n  File \"/usr/lib64/python2.7/encodings/utf_8.py\", line 16, in decode\n    return codecs.utf_8_decode(input, errors, True)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0xe3 in position 8: invalid continuation byte\n\n======================================================================\nFAIL: test_eval (__main__.SpidermonkeyRuntimeTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"test_execjs.py\", line 58, in test_eval\n    self.assertEqual(\"\\u3042\", self.runtime.eval('\"\\u3042\"'))\nAssertionError: u'\\u3042' != u'B'\n- \\u3042\n+ B\n\n\n----------------------------------------------------------------------\nRan 35 tests in 2.629s\n\nFAILED (failures=1, errors=1)\n```\n\n```\n$ python -V\nPython 3.4.3\n\n$ python test_execjs.py\n.............................FE.....\n======================================================================\nERROR: test_exec (__main__.SpidermonkeyRuntimeTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"test_execjs.py\", line 41, in test_exec\n    self.assertEqual(\"\\u3042\", self.runtime.exec_('return \"\\u3042\"'))   # unicode char\n  File \"/home/jbo/checkouts/github/PyExecJS/execjs/_abstract_runtime.py\", line 8, in exec_\n    return self._exec_(source, cwd=cwd)\n  File \"/home/jbo/checkouts/github/PyExecJS/execjs/_external_runtime.py\", line 47, in _exec_\n    return self.Context(self, cwd=cwd).exec_(source)\n  File \"/home/jbo/checkouts/github/PyExecJS/execjs/_external_runtime.py\", line 92, in exec_\n    return self._extract_result(output)\n  File \"/home/jbo/checkouts/github/PyExecJS/execjs/_external_runtime.py\", line 137, in _extract_result\n    output = output.decode(self._runtime._encoding)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 8: invalid continuation byte\n\n======================================================================\nFAIL: test_eval (__main__.SpidermonkeyRuntimeTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"test_execjs.py\", line 58, in test_eval\n    self.assertEqual(\"\\u3042\", self.runtime.eval('\"\\u3042\"'))\nAssertionError: '\u3042' != 'B'\n- \u3042\n+ B\n\n\n----------------------------------------------------------------------\nRan 36 tests in 2.692s\n\nFAILED (failures=1, errors=1)\n```\n\n```\n\n[I] dev-lang/spidermonkey\n     Available versions:\n     (0)    1.7.0-r3(0/js) 1.8.5-r4(0/mozjs185) ~1.8.5-r5(0/mozjs185)\n     (17)   17.0.0-r4^t\n     (24)   24.2.0-r3^t\n       {debug icu jit minimal static-libs +system-icu test threadsafe unicode}\n     Installed versions:  1.8.5-r4(13:20:01 09/12/15)(-debug -minimal -static-libs -test) 24.2.0-r3(24)(14:46:00 10/12/15)(system-icu -debug -icu -jit -minimal -static-libs -test)\n     Homepage:            http://www.mozilla.org/js/spidermonkey/\n     Description:         Stand-alone JavaScript C library\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/34", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/34/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/34/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/34/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/34", "id": 120600583, "node_id": "MDU6SXNzdWUxMjA2MDA1ODM=", "number": 34, "title": "Use Js2Py as a fallback", "user": {"login": "sametmax", "id": 1673950, "node_id": "MDQ6VXNlcjE2NzM5NTA=", "avatar_url": "https://avatars2.githubusercontent.com/u/1673950?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sametmax", "html_url": "https://github.com/sametmax", "followers_url": "https://api.github.com/users/sametmax/followers", "following_url": "https://api.github.com/users/sametmax/following{/other_user}", "gists_url": "https://api.github.com/users/sametmax/gists{/gist_id}", "starred_url": "https://api.github.com/users/sametmax/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sametmax/subscriptions", "organizations_url": "https://api.github.com/users/sametmax/orgs", "repos_url": "https://api.github.com/users/sametmax/repos", "events_url": "https://api.github.com/users/sametmax/events{/privacy}", "received_events_url": "https://api.github.com/users/sametmax/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2015-12-06T01:29:18Z", "updated_at": "2016-03-25T08:10:14Z", "closed_at": "2016-03-25T08:09:08Z", "author_association": "NONE", "active_lock_reason": null, "body": "When no native JS VM is available, it's better than nothing to use a pure Python implementation: https://github.com/PiotrDabkowski/Js2Py\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/33", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/33/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/33/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/33/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/33", "id": 118540091, "node_id": "MDU6SXNzdWUxMTg1NDAwOTE=", "number": 33, "title": "can pyexecjs load js file", "user": {"login": "hlee13", "id": 4981187, "node_id": "MDQ6VXNlcjQ5ODExODc=", "avatar_url": "https://avatars0.githubusercontent.com/u/4981187?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hlee13", "html_url": "https://github.com/hlee13", "followers_url": "https://api.github.com/users/hlee13/followers", "following_url": "https://api.github.com/users/hlee13/following{/other_user}", "gists_url": "https://api.github.com/users/hlee13/gists{/gist_id}", "starred_url": "https://api.github.com/users/hlee13/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hlee13/subscriptions", "organizations_url": "https://api.github.com/users/hlee13/orgs", "repos_url": "https://api.github.com/users/hlee13/repos", "events_url": "https://api.github.com/users/hlee13/events{/privacy}", "received_events_url": "https://api.github.com/users/hlee13/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-11-24T06:21:01Z", "updated_at": "2016-03-13T12:29:26Z", "closed_at": "2016-03-13T12:29:26Z", "author_association": "NONE", "active_lock_reason": null, "body": "can pyexecjs load js file\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/31", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/31/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/31/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/31/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/31", "id": 105678483, "node_id": "MDU6SXNzdWUxMDU2Nzg0ODM=", "number": 31, "title": "Node should be added to the requirements and note that it is the only runtime that works for Windows 7.", "user": {"login": "CookieOfFortune", "id": 241900, "node_id": "MDQ6VXNlcjI0MTkwMA==", "avatar_url": "https://avatars3.githubusercontent.com/u/241900?v=4", "gravatar_id": "", "url": "https://api.github.com/users/CookieOfFortune", "html_url": "https://github.com/CookieOfFortune", "followers_url": "https://api.github.com/users/CookieOfFortune/followers", "following_url": "https://api.github.com/users/CookieOfFortune/following{/other_user}", "gists_url": "https://api.github.com/users/CookieOfFortune/gists{/gist_id}", "starred_url": "https://api.github.com/users/CookieOfFortune/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/CookieOfFortune/subscriptions", "organizations_url": "https://api.github.com/users/CookieOfFortune/orgs", "repos_url": "https://api.github.com/users/CookieOfFortune/repos", "events_url": "https://api.github.com/users/CookieOfFortune/events{/privacy}", "received_events_url": "https://api.github.com/users/CookieOfFortune/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-09-09T20:31:13Z", "updated_at": "2015-09-11T01:04:48Z", "closed_at": "2015-09-11T01:04:48Z", "author_association": "NONE", "active_lock_reason": null, "body": "Windows 7 64-bit\npyexecjs 1.1.0\npyv8 1.0\nNodeJS 4.0.0\n\nUsing execjs with pyv8 (it seems that PyV8 takes precedence):\n\n``` Python\nimport execjs\n\nexecjs.get().name\nOut[2]: u'PyV8'\n\nfrom react import jsx\njsx.transform('helloworld.jsx')\nTraceback (most recent call last):\n\n  File \"<ipython-input-4-ba80c49e788e>\", line 1, in <module>\n    jsx.transform('helloworld.jsx')\n\n  File \"C:\\Python27\\python-2.7.6.amd64\\lib\\site-packages\\react\\jsx.py\", line 64, in transform\n    return JSXTransformer().transform(jsx_path, **opts)\n\n  File \"C:\\Python27\\python-2.7.6.amd64\\lib\\site-packages\\react\\jsx.py\", line 51, in transform\n    js = self.transform_string(i.read(), **kwargs)\n\n  File \"C:\\Python27\\python-2.7.6.amd64\\lib\\site-packages\\react\\jsx.py\", line 45, in transform_string\n    raise TransformError(e.message[7:])\n\nTransformError: ()\n```\n\n'JScript' was my original runtime:\n\n``` Python\nimport os\nos.environ['EXECJS_RUNTIME'] = 'JScript'\njsx.transform('helloworld.jsx')\nTraceback (most recent call last):\n\n  File \"<ipython-input-7-ba80c49e788e>\", line 1, in <module>\n    jsx.transform(helloworld.jsx')\n\n  File \"C:\\Python27\\python-2.7.6.amd64\\lib\\site-packages\\react\\jsx.py\", line 64, in transform\n    return JSXTransformer().transform(jsx_path, **opts)\n\n  File \"C:\\Python27\\python-2.7.6.amd64\\lib\\site-packages\\react\\jsx.py\", line 51, in transform\n    js = self.transform_string(i.read(), **kwargs)\n\n  File \"C:\\Python27\\python-2.7.6.amd64\\lib\\site-packages\\react\\jsx.py\", line 45, in transform_string\n    raise TransformError(e.message[7:])\n\nTransformError: or: 'undefined' is null or not an object\n```\n\nBut installing NodeJS and using it as the runtime works:\n\n``` Python\nos.environ['EXECJS_RUNTIME'] = 'Node'\n\nIn [9]: jsx.transform('helloworld.jsx')\nOut[9]: u'var HelloMessage = React.createClass({displayName: \\'HelloMessage\\',\\n  render: function() {\\n    return React.createElement(\"div\", null, \"Hello \", this.props.name);\\n  }\\n});\\n\\nReact.render(React.createElement(HelloMessage, {name: \"John\"}), mountNode);'\n```\n\nSo I guess that should be added to the readme. I have uninstalled PyV8 and now Node is the default runtime under execjs.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/30", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/30/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/30/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/30/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/30", "id": 97231110, "node_id": "MDU6SXNzdWU5NzIzMTExMA==", "number": 30, "title": "PyExecJS and Web Sockets", "user": {"login": "DenisDollfus", "id": 1465173, "node_id": "MDQ6VXNlcjE0NjUxNzM=", "avatar_url": "https://avatars3.githubusercontent.com/u/1465173?v=4", "gravatar_id": "", "url": "https://api.github.com/users/DenisDollfus", "html_url": "https://github.com/DenisDollfus", "followers_url": "https://api.github.com/users/DenisDollfus/followers", "following_url": "https://api.github.com/users/DenisDollfus/following{/other_user}", "gists_url": "https://api.github.com/users/DenisDollfus/gists{/gist_id}", "starred_url": "https://api.github.com/users/DenisDollfus/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/DenisDollfus/subscriptions", "organizations_url": "https://api.github.com/users/DenisDollfus/orgs", "repos_url": "https://api.github.com/users/DenisDollfus/repos", "events_url": "https://api.github.com/users/DenisDollfus/events{/privacy}", "received_events_url": "https://api.github.com/users/DenisDollfus/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-07-25T14:45:45Z", "updated_at": "2015-12-15T09:24:04Z", "closed_at": "2015-12-15T09:24:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\n\nIs it possible to use PyExecJS to load some JS that initiates a Web Socket connection and then asynchronously calls back from JS to Python? \n\nAs per another question about async JavaScript I assume it's not possible today. Do you confirm?\n\nThanks.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/25", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/25/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/25/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/25/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/25", "id": 65954057, "node_id": "MDU6SXNzdWU2NTk1NDA1Nw==", "number": 25, "title": "Support for custom JSON encoder", "user": {"login": "grivescorbett", "id": 395660, "node_id": "MDQ6VXNlcjM5NTY2MA==", "avatar_url": "https://avatars0.githubusercontent.com/u/395660?v=4", "gravatar_id": "", "url": "https://api.github.com/users/grivescorbett", "html_url": "https://github.com/grivescorbett", "followers_url": "https://api.github.com/users/grivescorbett/followers", "following_url": "https://api.github.com/users/grivescorbett/following{/other_user}", "gists_url": "https://api.github.com/users/grivescorbett/gists{/gist_id}", "starred_url": "https://api.github.com/users/grivescorbett/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/grivescorbett/subscriptions", "organizations_url": "https://api.github.com/users/grivescorbett/orgs", "repos_url": "https://api.github.com/users/grivescorbett/repos", "events_url": "https://api.github.com/users/grivescorbett/events{/privacy}", "received_events_url": "https://api.github.com/users/grivescorbett/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-04-02T15:40:10Z", "updated_at": "2016-03-13T12:54:08Z", "closed_at": "2016-03-13T12:54:08Z", "author_association": "NONE", "active_lock_reason": null, "body": "Use case is dict contains bson ObjectIDs which need to be serialized to strings.  I have a PR for this as well, will submit all of them next week once everything is approved.  \n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/24", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/24/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/24/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/24/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/24", "id": 65717592, "node_id": "MDU6SXNzdWU2NTcxNzU5Mg==", "number": 24, "title": "Support runtime with raw result.", "user": {"login": "grivescorbett", "id": 395660, "node_id": "MDQ6VXNlcjM5NTY2MA==", "avatar_url": "https://avatars0.githubusercontent.com/u/395660?v=4", "gravatar_id": "", "url": "https://api.github.com/users/grivescorbett", "html_url": "https://github.com/grivescorbett", "followers_url": "https://api.github.com/users/grivescorbett/followers", "following_url": "https://api.github.com/users/grivescorbett/following{/other_user}", "gists_url": "https://api.github.com/users/grivescorbett/gists{/gist_id}", "starred_url": "https://api.github.com/users/grivescorbett/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/grivescorbett/subscriptions", "organizations_url": "https://api.github.com/users/grivescorbett/orgs", "repos_url": "https://api.github.com/users/grivescorbett/repos", "events_url": "https://api.github.com/users/grivescorbett/events{/privacy}", "received_events_url": "https://api.github.com/users/grivescorbett/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-04-01T15:56:47Z", "updated_at": "2016-03-13T12:55:16Z", "closed_at": "2016-03-13T12:55:16Z", "author_association": "NONE", "active_lock_reason": null, "body": "Use case is phantomjs renders a page as PDF to stdout, I don't want that output to be passed through the decoding and extract result process.  I have a PR for this if it's wanted.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/22", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/22/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/22/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/22/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/22", "id": 57875801, "node_id": "MDU6SXNzdWU1Nzg3NTgwMQ==", "number": 22, "title": "Make it possible to `require` external libraries.", "user": {"login": "doloopwhile", "id": 1269088, "node_id": "MDQ6VXNlcjEyNjkwODg=", "avatar_url": "https://avatars3.githubusercontent.com/u/1269088?v=4", "gravatar_id": "", "url": "https://api.github.com/users/doloopwhile", "html_url": "https://github.com/doloopwhile", "followers_url": "https://api.github.com/users/doloopwhile/followers", "following_url": "https://api.github.com/users/doloopwhile/following{/other_user}", "gists_url": "https://api.github.com/users/doloopwhile/gists{/gist_id}", "starred_url": "https://api.github.com/users/doloopwhile/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/doloopwhile/subscriptions", "organizations_url": "https://api.github.com/users/doloopwhile/orgs", "repos_url": "https://api.github.com/users/doloopwhile/repos", "events_url": "https://api.github.com/users/doloopwhile/events{/privacy}", "received_events_url": "https://api.github.com/users/doloopwhile/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2015-02-17T02:23:35Z", "updated_at": "2016-03-14T08:45:04Z", "closed_at": "2016-03-14T08:45:04Z", "author_association": "OWNER", "active_lock_reason": null, "body": "Currently, one can not `require` external libraries in JS script.\n\nExample: https://gist.github.com/brandonwoo/823856a82145c9c76f8b\n\nOne of solution is adding parameter of directory to `execjs.exec_` and other methods.\nHowever, the solution depends spec of `nodejs`.\n\nWhere should be specify working directory? (or not specify working directory).\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/20", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/20/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/20/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/20/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/20", "id": 56711221, "node_id": "MDU6SXNzdWU1NjcxMTIyMQ==", "number": 20, "title": "Plans to support asynchronous javascript?", "user": {"login": "ariutta", "id": 1296771, "node_id": "MDQ6VXNlcjEyOTY3NzE=", "avatar_url": "https://avatars0.githubusercontent.com/u/1296771?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ariutta", "html_url": "https://github.com/ariutta", "followers_url": "https://api.github.com/users/ariutta/followers", "following_url": "https://api.github.com/users/ariutta/following{/other_user}", "gists_url": "https://api.github.com/users/ariutta/gists{/gist_id}", "starred_url": "https://api.github.com/users/ariutta/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ariutta/subscriptions", "organizations_url": "https://api.github.com/users/ariutta/orgs", "repos_url": "https://api.github.com/users/ariutta/repos", "events_url": "https://api.github.com/users/ariutta/events{/privacy}", "received_events_url": "https://api.github.com/users/ariutta/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-02-05T18:44:08Z", "updated_at": "2016-03-13T12:55:24Z", "closed_at": "2016-03-13T12:55:24Z", "author_association": "NONE", "active_lock_reason": null, "body": "Any plans to add support for asynchronous javascript? There's a Ruby project, [ExecJS Async](https://github.com/ericallam/execjs-async), that does this with Node.js:\n\n\"ExecJS lets you run JavaScript code from Ruby. ExecJS Async allows you to execute, and receive results from, asynchronous javascript.\"\n\nThanks!\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/14", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/14/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/14/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/14/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/14", "id": 48040981, "node_id": "MDU6SXNzdWU0ODA0MDk4MQ==", "number": 14, "title": "Upgrade to 1.0.5 breaks PyReact + nodejs JSXTransformer", "user": {"login": "MattFisher", "id": 70594, "node_id": "MDQ6VXNlcjcwNTk0", "avatar_url": "https://avatars0.githubusercontent.com/u/70594?v=4", "gravatar_id": "", "url": "https://api.github.com/users/MattFisher", "html_url": "https://github.com/MattFisher", "followers_url": "https://api.github.com/users/MattFisher/followers", "following_url": "https://api.github.com/users/MattFisher/following{/other_user}", "gists_url": "https://api.github.com/users/MattFisher/gists{/gist_id}", "starred_url": "https://api.github.com/users/MattFisher/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/MattFisher/subscriptions", "organizations_url": "https://api.github.com/users/MattFisher/orgs", "repos_url": "https://api.github.com/users/MattFisher/repos", "events_url": "https://api.github.com/users/MattFisher/events{/privacy}", "received_events_url": "https://api.github.com/users/MattFisher/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2014-11-07T02:28:54Z", "updated_at": "2014-11-25T04:47:52Z", "closed_at": "2014-11-25T04:47:52Z", "author_association": "NONE", "active_lock_reason": null, "body": "I am using django 1.6.5, django-pipeline 1.3.26, and PyReact 0.4.1, and upgrading from PyExecJS 1.0.4 to 1.0.5 breaks the pipeline jsx compilation with the cryptic message `ce Error: JSXTransformer is not defined`.\nLooking deeper, I ran the commands that were actually being called behind the scenes, eg `/usr/bin/nodejs /tmp/execjsJ9PCNo.js` and found the actual output was `[\"err\",\"ReferenceError: JSXTransformer is not defined\"]`\n\nDowngrading to 1.0.4 I tried compiling the same file again, and diffed the results.  The only difference was in the first line, where 1.0.5 produced:\n\n```\n(function(program, execJS) { execJS(program) })(function(module, exports, require) { /**\n * JSXTransformer v0.11.2\n */\n...\n```\n\nand 1.0.4 produced:\n\n```\n(function(program, execJS) { execJS(program) })(function() { /**\n * JSXTransformer v0.11.2\n */\n...\n```\n\nThe output from trying to run these files with node was as follows (files renamed for clarity):\n\n```\n$ nodejs PyReact-0.4.1_PyExecJS-1.0.4.js\n\n[\"ok\",{\"code\":\"/** @jsx React.DOM */\\n'use strict';\\n\\nvar Test = React.createClass({displayName: 'Test',\\n  render: function () {\\n    return (\\n      React.DOM.span(null, \\\"Hello\\\")\\n    );\\n  }\\n});\\n\",\"extra\":{},\"sourceMap\":{\"version\":3,\"file\":\"transformed.js\",\"sources\":[\"source.js\"],\"names\":[],\"mappings\":\"AAAA,qBAAqB;AACrB,YAAY,CAAC;;AAEb,IAAI,0BAA0B,oBAAA;EAC5B,MAAM,EAAE,YAAY;IAClB;MACE,cAAK,CAAA,IAAC,EAAA,OAAY,CAAA;MAClB;GACH;CACF,CAAC,CAAC\"},\"sourceMapFilename\":\"source.js\"}]\n\n$ nodejs PyReact-0.4.1_PyExecJS-1.0.5.js\n[\"err\",\"ReferenceError: JSXTransformer is not defined\"]\n\n$ \n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/13", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/13/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/13/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/13/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/13", "id": 47768725, "node_id": "MDU6SXNzdWU0Nzc2ODcyNQ==", "number": 13, "title": "Problem with passenger", "user": {"login": "stopiccot", "id": 24836, "node_id": "MDQ6VXNlcjI0ODM2", "avatar_url": "https://avatars3.githubusercontent.com/u/24836?v=4", "gravatar_id": "", "url": "https://api.github.com/users/stopiccot", "html_url": "https://github.com/stopiccot", "followers_url": "https://api.github.com/users/stopiccot/followers", "following_url": "https://api.github.com/users/stopiccot/following{/other_user}", "gists_url": "https://api.github.com/users/stopiccot/gists{/gist_id}", "starred_url": "https://api.github.com/users/stopiccot/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/stopiccot/subscriptions", "organizations_url": "https://api.github.com/users/stopiccot/orgs", "repos_url": "https://api.github.com/users/stopiccot/repos", "events_url": "https://api.github.com/users/stopiccot/events{/privacy}", "received_events_url": "https://api.github.com/users/stopiccot/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2014-11-04T21:37:33Z", "updated_at": "2014-11-06T10:27:19Z", "closed_at": "2014-11-06T10:27:19Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm getting such error when trying to run my wsgi app using passenger-nginx-4.0:\n\nApp 1163 stderr: Traceback (most recent call last):\nApp 1163 stderr:   File \"/usr/share/passenger/helper-scripts/wsgi-loader.py\", line 320, in <module>\nApp 1163 stderr:     app_module = load_app()\nApp 1163 stderr:   File \"/usr/share/passenger/helper-scripts/wsgi-loader.py\", line 61, in load_app\nApp 1163 stderr:     return imp.load_source('passenger_wsgi', startup_file)\nApp 1163 stderr:   File \"passenger_wsgi.py\", line 4, in <module>\nApp 1163 stderr:     from app import app as application\nApp 1163 stderr:   File \"/webapps/webgl-py/app.py\", line 5, in <module>\nApp 1163 stderr:     import coffeescript, flask\nApp 1163 stderr:   File \"/usr/local/lib/python2.7/dist-packages/coffeescript/**init**.py\", line 52, in <module>\nApp 1163 stderr:     import execjs\nApp 1163 stderr:   File \"/usr/local/lib/python2.7/dist-packages/execjs/**init**.py\", line 431, in <module>\nApp 1163 stderr:     if runtime.is_available():\nApp 1163 stderr:   File \"/usr/local/lib/python2.7/dist-packages/execjs/**init**.py\", line 204, in is_available\nApp 1163 stderr:     return self._binary() is not None\nApp 1163 stderr:   File \"/usr/local/lib/python2.7/dist-packages/execjs/__init__.py\", line 212, in _binary\nApp 1163 stderr:     self._binary_cache = _which(self._command)\nApp 1163 stderr:   File \"/usr/local/lib/python2.7/dist-packages/execjs/__init__.py\", line 162, in _which\nApp 1163 stderr:     path = _find_executable(name)\nApp 1163 stderr:   File \"/usr/local/lib/python2.7/dist-packages/execjs/__init__.py\", line 138, in _find_executable\nApp 1163 stderr:     pathlist = os.environ['PATH'].split(os.pathsep)\nApp 1163 stderr:   File \"/usr/lib/python2.7/UserDict.py\", line 23, in __getitem__\nApp 1163 stderr:     raise KeyError(key)\nApp 1163 stderr: KeyError: u'PATH'\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/7", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/7/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/7/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/7/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/7", "id": 12012856, "node_id": "MDU6SXNzdWUxMjAxMjg1Ng==", "number": 7, "title": "execjs.RuntimeError when compile simple coffee script", "user": {"login": "ovodopyan", "id": 1096377, "node_id": "MDQ6VXNlcjEwOTYzNzc=", "avatar_url": "https://avatars2.githubusercontent.com/u/1096377?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ovodopyan", "html_url": "https://github.com/ovodopyan", "followers_url": "https://api.github.com/users/ovodopyan/followers", "following_url": "https://api.github.com/users/ovodopyan/following{/other_user}", "gists_url": "https://api.github.com/users/ovodopyan/gists{/gist_id}", "starred_url": "https://api.github.com/users/ovodopyan/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ovodopyan/subscriptions", "organizations_url": "https://api.github.com/users/ovodopyan/orgs", "repos_url": "https://api.github.com/users/ovodopyan/repos", "events_url": "https://api.github.com/users/ovodopyan/events{/privacy}", "received_events_url": "https://api.github.com/users/ovodopyan/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2013-03-14T10:34:35Z", "updated_at": "2014-08-07T05:34:54Z", "closed_at": "2014-08-07T05:34:54Z", "author_association": "NONE", "active_lock_reason": null, "body": "# python\n\nPython 2.6.4 (r264:75706, Jun 26 2010, 14:53:53)\n[GCC 4.2.1 20070719  [FreeBSD]] on freebsd8\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n\n> import coffeescript\n> coffeescript.compile('a = 5')\n> Traceback (most recent call last):\n>   File \"<stdin>\", line 1, in <module>\n>   File \"/usr/local/lib/python2.6/site-packages/coffeescript/**init**.py\", line 104, in compile\n>     return _default_compiler().compile(script, bare=bare)\n>   File \"/usr/local/lib/python2.6/site-packages/coffeescript/__init__.py\", line 81, in compile\n>     \"CoffeeScript.compile\", script, {'bare': bare})\n>   File \"/usr/local/lib/python2.6/site-packages/execjs/**init**.py\", line 260, in call\n>     return self.eval(\"{identifier}.apply(this, {args})\".format(identifier=identifier, args=args))\n>   File \"/usr/local/lib/python2.6/site-packages/execjs/**init**.py\", line 239, in eval\n>     return self.exec_(code, options=options)\n>   File \"/usr/local/lib/python2.6/site-packages/execjs/**init**.py\", line 250, in exec_\n>     output = self._runtime._execfile(filename)\n>   File \"/usr/local/lib/python2.6/site-packages/execjs/__init__.py\", line 225, in _execfile\n>     raise RuntimeError(stdoutdata)\n> execjs.RuntimeError:\n> [\"ok\",\"(function() {\\n  var a;\\n\\n  a = 5;\\n\\n}).call(this);\\n\"]\n\nbug, incompatible python version or how fix this?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/4", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/4/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/4/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/4/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/4", "id": 3591284, "node_id": "MDU6SXNzdWUzNTkxMjg0", "number": 4, "title": "support folder missing from PyPi", "user": {"login": "mattjmorrison", "id": 150277, "node_id": "MDQ6VXNlcjE1MDI3Nw==", "avatar_url": "https://avatars3.githubusercontent.com/u/150277?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mattjmorrison", "html_url": "https://github.com/mattjmorrison", "followers_url": "https://api.github.com/users/mattjmorrison/followers", "following_url": "https://api.github.com/users/mattjmorrison/following{/other_user}", "gists_url": "https://api.github.com/users/mattjmorrison/gists{/gist_id}", "starred_url": "https://api.github.com/users/mattjmorrison/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mattjmorrison/subscriptions", "organizations_url": "https://api.github.com/users/mattjmorrison/orgs", "repos_url": "https://api.github.com/users/mattjmorrison/repos", "events_url": "https://api.github.com/users/mattjmorrison/events{/privacy}", "received_events_url": "https://api.github.com/users/mattjmorrison/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2012-03-09T23:03:07Z", "updated_at": "2012-12-07T06:52:12Z", "closed_at": "2012-12-07T06:52:12Z", "author_association": "NONE", "active_lock_reason": null, "body": "It looks like the zip file on PyPi is missing the support folder and all of the .js files. I ran \"python setup.py build\" on my local system and it appears to include everything properly, so I'm not sure why it is missing from PyPi.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/3", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/3/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/3/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/3/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/3", "id": 3557577, "node_id": "MDU6SXNzdWUzNTU3NTc3", "number": 3, "title": "No Runtime Error", "user": {"login": "knarfytrebil", "id": 616757, "node_id": "MDQ6VXNlcjYxNjc1Nw==", "avatar_url": "https://avatars1.githubusercontent.com/u/616757?v=4", "gravatar_id": "", "url": "https://api.github.com/users/knarfytrebil", "html_url": "https://github.com/knarfytrebil", "followers_url": "https://api.github.com/users/knarfytrebil/followers", "following_url": "https://api.github.com/users/knarfytrebil/following{/other_user}", "gists_url": "https://api.github.com/users/knarfytrebil/gists{/gist_id}", "starred_url": "https://api.github.com/users/knarfytrebil/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/knarfytrebil/subscriptions", "organizations_url": "https://api.github.com/users/knarfytrebil/orgs", "repos_url": "https://api.github.com/users/knarfytrebil/repos", "events_url": "https://api.github.com/users/knarfytrebil/events{/privacy}", "received_events_url": "https://api.github.com/users/knarfytrebil/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2012-03-08T08:21:16Z", "updated_at": "2012-12-07T06:52:26Z", "closed_at": "2012-12-07T06:52:26Z", "author_association": "NONE", "active_lock_reason": null, "body": "execjs.RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes.\n\nI got this right after I installed PyExecJs. I have no idea what the cause is. I have node and nodejs installed in the system.\n\nOS: Linux Mint\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/2", "repository_url": "https://api.github.com/repos/doloopwhile/PyExecJS", "labels_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/2/labels{/name}", "comments_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/2/comments", "events_url": "https://api.github.com/repos/doloopwhile/PyExecJS/issues/2/events", "html_url": "https://github.com/doloopwhile/PyExecJS/issues/2", "id": 3009475, "node_id": "MDU6SXNzdWUzMDA5NDc1", "number": 2, "title": "Invalid syntax error using easy_install", "user": {"login": "christopherliu", "id": 519376, "node_id": "MDQ6VXNlcjUxOTM3Ng==", "avatar_url": "https://avatars2.githubusercontent.com/u/519376?v=4", "gravatar_id": "", "url": "https://api.github.com/users/christopherliu", "html_url": "https://github.com/christopherliu", "followers_url": "https://api.github.com/users/christopherliu/followers", "following_url": "https://api.github.com/users/christopherliu/following{/other_user}", "gists_url": "https://api.github.com/users/christopherliu/gists{/gist_id}", "starred_url": "https://api.github.com/users/christopherliu/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/christopherliu/subscriptions", "organizations_url": "https://api.github.com/users/christopherliu/orgs", "repos_url": "https://api.github.com/users/christopherliu/repos", "events_url": "https://api.github.com/users/christopherliu/events{/privacy}", "received_events_url": "https://api.github.com/users/christopherliu/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2012-01-29T02:30:30Z", "updated_at": "2012-02-07T05:20:43Z", "closed_at": "2012-02-06T11:37:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "Python 2.7 has support for set comprehensions, which I believe is breaking Python 2.6 support for PyExecJS.\n\n:~# easy_install PyExecJS\n/usr/lib/python2.6/dist-packages/setuptools/package_index.py:156: UserWarning: Unbuilt egg for setuptools [unknown version](/usr/lib/python2.6/dist-packages)\n  Environment.**init**(self,_args,_*kw)\n\nBest match: PyExecJS 1.0.1\nDownloading http://pypi.python.org/packages/source/P/PyExecJS/PyExecJS-1.0.1.zip#md5=9d7b4d6d5b3a43bd76f3754d7031a71c\nProcessing PyExecJS-1.0.1.zip\nRunning PyExecJS-1.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-iet2Gt/PyExecJS-1.0.1/egg-dist-tmp-028w8Y\nTraceback (most recent call last):\n...\n  File \"setup.py\", line 11, in <module>\n  File \"/tmp/easy_install-iet2Gt/PyExecJS-1.0.1/execjs/**init**.py\", line 78\n    return {name:runtime for name, runtime in _runtimes.items() if runtime.is_available()}\n                           ^\nSyntaxError: invalid syntax\n", "performed_via_github_app": null, "score": 1.0}]}