{"total_count": 20, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/takluyver/entrypoints/issues/31", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/31/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/31/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/31/events", "html_url": "https://github.com/takluyver/entrypoints/issues/31", "id": 424824251, "node_id": "MDU6SXNzdWU0MjQ4MjQyNTE=", "number": 31, "title": "support egg links", "user": {"login": "gaborbernat", "id": 690238, "node_id": "MDQ6VXNlcjY5MDIzOA==", "avatar_url": "https://avatars1.githubusercontent.com/u/690238?v=4", "gravatar_id": "", "url": "https://api.github.com/users/gaborbernat", "html_url": "https://github.com/gaborbernat", "followers_url": "https://api.github.com/users/gaborbernat/followers", "following_url": "https://api.github.com/users/gaborbernat/following{/other_user}", "gists_url": "https://api.github.com/users/gaborbernat/gists{/gist_id}", "starred_url": "https://api.github.com/users/gaborbernat/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/gaborbernat/subscriptions", "organizations_url": "https://api.github.com/users/gaborbernat/orgs", "repos_url": "https://api.github.com/users/gaborbernat/repos", "events_url": "https://api.github.com/users/gaborbernat/events{/privacy}", "received_events_url": "https://api.github.com/users/gaborbernat/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2019-03-25T10:25:46Z", "updated_at": "2019-03-25T11:04:56Z", "closed_at": "2019-03-25T10:41:27Z", "author_association": "NONE", "active_lock_reason": null, "body": "We should detect egg links and discover egg-info at targets they point too \ud83d\udc4d ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/29", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/29/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/29/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/29/events", "html_url": "https://github.com/takluyver/entrypoints/issues/29", "id": 410453851, "node_id": "MDU6SXNzdWU0MTA0NTM4NTE=", "number": 29, "title": "Anchor link in README is dead", "user": {"login": "pganssle", "id": 1377457, "node_id": "MDQ6VXNlcjEzNzc0NTc=", "avatar_url": "https://avatars0.githubusercontent.com/u/1377457?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pganssle", "html_url": "https://github.com/pganssle", "followers_url": "https://api.github.com/users/pganssle/followers", "following_url": "https://api.github.com/users/pganssle/following{/other_user}", "gists_url": "https://api.github.com/users/pganssle/gists{/gist_id}", "starred_url": "https://api.github.com/users/pganssle/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pganssle/subscriptions", "organizations_url": "https://api.github.com/users/pganssle/orgs", "repos_url": "https://api.github.com/users/pganssle/repos", "events_url": "https://api.github.com/users/pganssle/events{/privacy}", "received_events_url": "https://api.github.com/users/pganssle/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2019-02-14T19:25:30Z", "updated_at": "2019-04-25T09:58:26Z", "closed_at": "2019-04-25T09:46:15Z", "author_association": "NONE", "active_lock_reason": null, "body": "The documentation and README seems to largely outsource the discussion of how to actually use this library to the Python Packaging documentation using this link: https://packaging.python.org/en/latest/distributing.html#entry-points\r\n\r\nThe problem is that it seems that that page has changed, the anchor link is dead and Ctrl+F for \"entry\" gives nothing. Is there a new link where this information is kept? Might it be a good idea to mirror that in the documentation in some minor way?\r\n\r\nI am not really sure how this project relates to the `entry_points` argument in `setuptools.setup`, I was hoping the link might clarify that.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/27", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/27/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/27/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/27/events", "html_url": "https://github.com/takluyver/entrypoints/issues/27", "id": 409434169, "node_id": "MDU6SXNzdWU0MDk0MzQxNjk=", "number": 27, "title": "Multiple versions of entry points", "user": {"login": "lowell80", "id": 7256578, "node_id": "MDQ6VXNlcjcyNTY1Nzg=", "avatar_url": "https://avatars3.githubusercontent.com/u/7256578?v=4", "gravatar_id": "", "url": "https://api.github.com/users/lowell80", "html_url": "https://github.com/lowell80", "followers_url": "https://api.github.com/users/lowell80/followers", "following_url": "https://api.github.com/users/lowell80/following{/other_user}", "gists_url": "https://api.github.com/users/lowell80/gists{/gist_id}", "starred_url": "https://api.github.com/users/lowell80/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/lowell80/subscriptions", "organizations_url": "https://api.github.com/users/lowell80/orgs", "repos_url": "https://api.github.com/users/lowell80/repos", "events_url": "https://api.github.com/users/lowell80/events{/privacy}", "received_events_url": "https://api.github.com/users/lowell80/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2019-02-12T18:15:02Z", "updated_at": "2019-02-13T18:48:05Z", "closed_at": "2019-02-13T18:48:05Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Should the entrypoint module handle multiple versions of a single package?\r\n\r\nAfter upgrading a package, it seems that old `.dist-info` folders are hanging around.  Now I'm experience this 2 places,  (1) where I'm doing local development on a package (and the package version is updated after every commit:   e.g,`0.6.2.dev2+f0b8738.dirty` meaning 2 revisions past the 0.6.2 tag, and that my local copy has changes).  So this means *more* packages which exaggerates my issue a bit.  And (2), I'm also seeing this when I'm doing some unusual package installation stuff  `pip install PKG -t INSTALL_DIR`.  So I fully understand why duplicate dist-info folders exist in that case.\r\n\r\nWhat's unclear to me is what should be the normal behavior.  I apologize for \"packaging\" question here, but the reason why I bring it up is that I do see different results between say:\r\n\r\n    list( pkg_resources.iter_entry_points(\"ksconf_cmd\") )\r\n\r\nand \r\n\r\n    entrypoints.get_group_all(\"ksconf_cmd\")\r\n\r\nBased on a quick test, pkg_resources seems to be pulling in the most recent version, where as entrypoints seems to be pulling in the older version.  (I suppose there could also be a lexicographical sort or internal directory listing order factor in here too.  Haven't dug that deep.)\r\n\r\nSo 2 questions:\r\n\r\n1.)  Is the assumption that `pip` (or whatever installer tool) is already taking are of duplicate `.dist-info` folders and only keeping the most recently installed one.\r\n2.)  If not, is there a way to get visibility into the multiple distributions using entrypoints?\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/24", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/24/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/24/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/24/events", "html_url": "https://github.com/takluyver/entrypoints/issues/24", "id": 376846367, "node_id": "MDU6SXNzdWUzNzY4NDYzNjc=", "number": 24, "title": "Support loading of entrypoints from importable wheels", "user": {"login": "jaraco", "id": 308610, "node_id": "MDQ6VXNlcjMwODYxMA==", "avatar_url": "https://avatars2.githubusercontent.com/u/308610?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jaraco", "html_url": "https://github.com/jaraco", "followers_url": "https://api.github.com/users/jaraco/followers", "following_url": "https://api.github.com/users/jaraco/following{/other_user}", "gists_url": "https://api.github.com/users/jaraco/gists{/gist_id}", "starred_url": "https://api.github.com/users/jaraco/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jaraco/subscriptions", "organizations_url": "https://api.github.com/users/jaraco/orgs", "repos_url": "https://api.github.com/users/jaraco/repos", "events_url": "https://api.github.com/users/jaraco/events{/privacy}", "received_events_url": "https://api.github.com/users/jaraco/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2018-11-02T15:02:10Z", "updated_at": "2019-02-04T18:52:44Z", "closed_at": "2019-01-07T17:01:17Z", "author_association": "NONE", "active_lock_reason": null, "body": "One use-case that the import ecosystem intends to support is importable wheels - wheels that much like zip eggs of the past can be added to sys.path and imported. Consider this environment:\r\n\r\n```\r\ndraft $ python -m venv env\r\ndraft $ env/bin/pip install -q -U pip importlib_metadata\r\ndraft $ env/bin/pip download --no-deps keyring\r\nCollecting keyring\r\n  Using cached https://files.pythonhosted.org/packages/85/25/55798660a50bd2fd7a8ef58a4394fd4fbb474e6b87d55a8d3e49e300d2a4/keyring-16.0.0-py2.py3-none-any.whl\r\n  Saved ./keyring-16.0.0-py2.py3-none-any.whl\r\ndraft $ env/bin/pip install entrypoints\r\nCollecting entrypoints\r\n  Using cached https://files.pythonhosted.org/packages/cc/8b/4eefa9b47f1910b3d2081da67726b066e379b04ca897acfe9f92bac56147/entrypoints-0.2.3-py2.py3-none-any.whl\r\nInstalling collected packages: entrypoints\r\nSuccessfully installed entrypoints-0.2.3\r\n```\r\n\r\nkeyring (which has entry points) is present as an importable wheel but isn't on sys.path (by default).\r\n\r\nOne can readily see that the entry points are visible using importlib_metadata.\r\n\r\n```\r\ndraft $ env PYTHONPATH=./keyring-16.0.0-py2.py3-none-any.whl env/bin/python\r\nPython 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28)\r\n[Clang 6.0 (clang-600.0.57)] on darwin\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> import importlib_metadata\r\n>>> list(importlib_metadata.entry_points('keyring')['keyring.backends'])\r\n['kwallet', 'secretservice', 'windows', 'macos']\r\n```\r\n\r\nBut with entrypoints, the metadata is missing even though keyring is importable:\r\n\r\n```\r\ndraft $ env PYTHONPATH=./keyring-16.0.0-py2.py3-none-any.whl env/bin/python\r\nPython 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28)\r\n[Clang 6.0 (clang-600.0.57)] on darwin\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> import keyring\r\n>>> import entrypoints\r\n>>> entrypoints.get_group_all('keyring.backends')\r\n[]\r\n```\r\n\r\nI suggest entrypoints should support loading of entrypoints from importable wheels in addition to eggs.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/23", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/23/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/23/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/23/events", "html_url": "https://github.com/takluyver/entrypoints/issues/23", "id": 375457722, "node_id": "MDU6SXNzdWUzNzU0NTc3MjI=", "number": 23, "title": "Test failure with python2 and pytest 3.9.2", "user": {"login": "timokau", "id": 3799330, "node_id": "MDQ6VXNlcjM3OTkzMzA=", "avatar_url": "https://avatars0.githubusercontent.com/u/3799330?v=4", "gravatar_id": "", "url": "https://api.github.com/users/timokau", "html_url": "https://github.com/timokau", "followers_url": "https://api.github.com/users/timokau/followers", "following_url": "https://api.github.com/users/timokau/following{/other_user}", "gists_url": "https://api.github.com/users/timokau/gists{/gist_id}", "starred_url": "https://api.github.com/users/timokau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/timokau/subscriptions", "organizations_url": "https://api.github.com/users/timokau/orgs", "repos_url": "https://api.github.com/users/timokau/repos", "events_url": "https://api.github.com/users/timokau/events{/privacy}", "received_events_url": "https://api.github.com/users/timokau/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2018-10-30T12:12:32Z", "updated_at": "2019-01-07T19:08:54Z", "closed_at": "2019-01-07T19:08:54Z", "author_association": "NONE", "active_lock_reason": null, "body": "The test_bad test fails because apparently the pytest upgrade added some warning (didn't happen with older pytest versions, doesn't happen with python3):\r\n\r\n```\r\n=================================== FAILURES ===================================\r\n___________________________________ test_bad ___________________________________\r\n\r\n    def test_bad():\r\n        bad_path = [osp.join(samples_dir, 'packages3')]\r\n\r\n        with warnings.catch_warnings(record=True) as w:\r\n            group = entrypoints.get_group_named('entrypoints.test1', bad_path)\r\n\r\n        assert 'bad' not in group\r\n>       assert len(w) == 1\r\nE       assert 2 == 1\r\nE        +  where 2 = len([<warnings.WarningMessage object at 0x7ffff17852d0>, <warnings.WarningMessage object at 0x7ffff1766f10>])\r\n\r\ntests/test_entrypoints.py:70: AssertionError\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/18", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/18/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/18/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/18/events", "html_url": "https://github.com/takluyver/entrypoints/issues/18", "id": 308893611, "node_id": "MDU6SXNzdWUzMDg4OTM2MTE=", "number": 18, "title": "useless warnings triggered by configparser usage ", "user": {"login": "RonnyPfannschmidt", "id": 156838, "node_id": "MDQ6VXNlcjE1NjgzOA==", "avatar_url": "https://avatars1.githubusercontent.com/u/156838?v=4", "gravatar_id": "", "url": "https://api.github.com/users/RonnyPfannschmidt", "html_url": "https://github.com/RonnyPfannschmidt", "followers_url": "https://api.github.com/users/RonnyPfannschmidt/followers", "following_url": "https://api.github.com/users/RonnyPfannschmidt/following{/other_user}", "gists_url": "https://api.github.com/users/RonnyPfannschmidt/gists{/gist_id}", "starred_url": "https://api.github.com/users/RonnyPfannschmidt/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/RonnyPfannschmidt/subscriptions", "organizations_url": "https://api.github.com/users/RonnyPfannschmidt/orgs", "repos_url": "https://api.github.com/users/RonnyPfannschmidt/repos", "events_url": "https://api.github.com/users/RonnyPfannschmidt/events{/privacy}", "received_events_url": "https://api.github.com/users/RonnyPfannschmidt/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2018-03-27T09:38:04Z", "updated_at": "2019-01-07T19:12:36Z", "closed_at": "2018-04-09T12:10:28Z", "author_association": "NONE", "active_lock_reason": null, "body": "```\r\n/lib/python2.7/site-packages/entrypoints.py:168: DeprecationWarning: You passed a bytestring as `filenames`. This will not work on Python 3. Use `cp.read_file()` or switch to using Unicode strings across the board.\r\n  cp.read(path)\r\n```\r\n\r\non current master its in https://github.com/takluyver/entrypoints/blob/master/entrypoints.py#L171", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/15", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/15/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/15/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/15/events", "html_url": "https://github.com/takluyver/entrypoints/issues/15", "id": 211132234, "node_id": "MDU6SXNzdWUyMTExMzIyMzQ=", "number": 15, "title": "entrypoints unavailable for python 3.6?", "user": {"login": "blaiseli", "id": 3380503, "node_id": "MDQ6VXNlcjMzODA1MDM=", "avatar_url": "https://avatars2.githubusercontent.com/u/3380503?v=4", "gravatar_id": "", "url": "https://api.github.com/users/blaiseli", "html_url": "https://github.com/blaiseli", "followers_url": "https://api.github.com/users/blaiseli/followers", "following_url": "https://api.github.com/users/blaiseli/following{/other_user}", "gists_url": "https://api.github.com/users/blaiseli/gists{/gist_id}", "starred_url": "https://api.github.com/users/blaiseli/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/blaiseli/subscriptions", "organizations_url": "https://api.github.com/users/blaiseli/orgs", "repos_url": "https://api.github.com/users/blaiseli/repos", "events_url": "https://api.github.com/users/blaiseli/events{/privacy}", "received_events_url": "https://api.github.com/users/blaiseli/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2017-03-01T16:22:17Z", "updated_at": "2017-03-01T17:55:18Z", "closed_at": "2017-03-01T17:24:26Z", "author_association": "NONE", "active_lock_reason": null, "body": "I fail to install ipywidgets with pip under python 3.6 on Xubuntu 16.04 with the following message:\r\n\r\n```\r\nCollecting entrypoints>=0.2.2 (from nbconvert->notebook>=4.4.1->widgetsnbextension~=2.0.0->ipywidgets)\r\n  Could not find a version that satisfies the requirement entrypoints>=0.2.2 (from nbconvert->notebook>=4.4.1->widgetsnbextension~=2.0.0->ipywidgets) (from versions: )\r\nNo matching distribution found for entrypoints>=0.2.2 (from nbconvert->notebook>=4.4.1->widgetsnbextension~=2.0.0->ipywidgets)\r\n```\r\n\r\nIf I try to install entrypoints alone:\r\n\r\n    $ pip3.6 install entrypoints\r\n    Collecting entrypoints\r\n      Could not find a version that satisfies the requirement entrypoints (from versions: )\r\n    No matching distribution found for entrypoints\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/14", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/14/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/14/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/14/events", "html_url": "https://github.com/takluyver/entrypoints/issues/14", "id": 196417782, "node_id": "MDU6SXNzdWUxOTY0MTc3ODI=", "number": 14, "title": "source archive upload on pypi", "user": {"login": "fdiary", "id": 378621, "node_id": "MDQ6VXNlcjM3ODYyMQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/378621?v=4", "gravatar_id": "", "url": "https://api.github.com/users/fdiary", "html_url": "https://github.com/fdiary", "followers_url": "https://api.github.com/users/fdiary/followers", "following_url": "https://api.github.com/users/fdiary/following{/other_user}", "gists_url": "https://api.github.com/users/fdiary/gists{/gist_id}", "starred_url": "https://api.github.com/users/fdiary/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/fdiary/subscriptions", "organizations_url": "https://api.github.com/users/fdiary/orgs", "repos_url": "https://api.github.com/users/fdiary/repos", "events_url": "https://api.github.com/users/fdiary/events{/privacy}", "received_events_url": "https://api.github.com/users/fdiary/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2016-12-19T13:49:18Z", "updated_at": "2017-06-08T16:57:32Z", "closed_at": "2016-12-19T15:01:12Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello,\r\n\r\nCould you please consider uploading sorce archive (i.e. *.tar.gz or *.zip) on pypi, so that \"entrypoints\" can be installed as an egg ? I am using buildout to install \"ipython\" that requires \"nbconvert\" and recent \"nbconvert\" requires \"entrypoints\".\r\n\r\nThanks in advance !", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/12", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/12/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/12/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/12/events", "html_url": "https://github.com/takluyver/entrypoints/issues/12", "id": 187652633, "node_id": "MDU6SXNzdWUxODc2NTI2MzM=", "number": 12, "title": "No source package available on PyPI", "user": {"login": "ProgVal", "id": 406946, "node_id": "MDQ6VXNlcjQwNjk0Ng==", "avatar_url": "https://avatars3.githubusercontent.com/u/406946?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ProgVal", "html_url": "https://github.com/ProgVal", "followers_url": "https://api.github.com/users/ProgVal/followers", "following_url": "https://api.github.com/users/ProgVal/following{/other_user}", "gists_url": "https://api.github.com/users/ProgVal/gists{/gist_id}", "starred_url": "https://api.github.com/users/ProgVal/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ProgVal/subscriptions", "organizations_url": "https://api.github.com/users/ProgVal/orgs", "repos_url": "https://api.github.com/users/ProgVal/repos", "events_url": "https://api.github.com/users/ProgVal/events{/privacy}", "received_events_url": "https://api.github.com/users/ProgVal/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-11-07T08:38:26Z", "updated_at": "2016-11-07T08:41:59Z", "closed_at": "2016-11-07T08:41:59Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\r\n\r\nCould you upload a source package of `entrypoints` to PyPI?\r\nThere is currently only the wheel (binary) package.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/11", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/11/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/11/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/11/events", "html_url": "https://github.com/takluyver/entrypoints/issues/11", "id": 185239950, "node_id": "MDU6SXNzdWUxODUyMzk5NTA=", "number": 11, "title": "Publishing tar.gz to pypi", "user": {"login": "bringhurst", "id": 143694, "node_id": "MDQ6VXNlcjE0MzY5NA==", "avatar_url": "https://avatars0.githubusercontent.com/u/143694?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bringhurst", "html_url": "https://github.com/bringhurst", "followers_url": "https://api.github.com/users/bringhurst/followers", "following_url": "https://api.github.com/users/bringhurst/following{/other_user}", "gists_url": "https://api.github.com/users/bringhurst/gists{/gist_id}", "starred_url": "https://api.github.com/users/bringhurst/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bringhurst/subscriptions", "organizations_url": "https://api.github.com/users/bringhurst/orgs", "repos_url": "https://api.github.com/users/bringhurst/repos", "events_url": "https://api.github.com/users/bringhurst/events{/privacy}", "received_events_url": "https://api.github.com/users/bringhurst/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2016-10-25T21:33:09Z", "updated_at": "2016-12-10T20:11:16Z", "closed_at": "2016-10-25T21:35:42Z", "author_association": "NONE", "active_lock_reason": null, "body": "If it's not too much trouble, would you be able to publish a tar.gz to pypi? We have some old tooling which is having trouble with whls at the moment.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/10", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/10/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/10/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/10/events", "html_url": "https://github.com/takluyver/entrypoints/issues/10", "id": 180539526, "node_id": "MDU6SXNzdWUxODA1Mzk1MjY=", "number": 10, "title": "license clarification", "user": {"login": "nonamedotc", "id": 1994161, "node_id": "MDQ6VXNlcjE5OTQxNjE=", "avatar_url": "https://avatars1.githubusercontent.com/u/1994161?v=4", "gravatar_id": "", "url": "https://api.github.com/users/nonamedotc", "html_url": "https://github.com/nonamedotc", "followers_url": "https://api.github.com/users/nonamedotc/followers", "following_url": "https://api.github.com/users/nonamedotc/following{/other_user}", "gists_url": "https://api.github.com/users/nonamedotc/gists{/gist_id}", "starred_url": "https://api.github.com/users/nonamedotc/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/nonamedotc/subscriptions", "organizations_url": "https://api.github.com/users/nonamedotc/orgs", "repos_url": "https://api.github.com/users/nonamedotc/repos", "events_url": "https://api.github.com/users/nonamedotc/events{/privacy}", "received_events_url": "https://api.github.com/users/nonamedotc/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2016-10-02T22:24:43Z", "updated_at": "2016-10-03T23:18:09Z", "closed_at": "2016-10-03T08:58:07Z", "author_association": "NONE", "active_lock_reason": null, "body": "Greetings!\n\nAlthough the project includes license text (MIT) , the source files have no license headers. Can you please clarify the license for all the files?\n\nThis is in connection with including entrypoints in Fedora (this clarification request originally came up in Fedora package review) [1].\n\nThank you! \n\n[1] https://bugzilla.redhat.com/show_bug.cgi?id=1379095\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/9", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/9/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/9/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/9/events", "html_url": "https://github.com/takluyver/entrypoints/issues/9", "id": 176899716, "node_id": "MDU6SXNzdWUxNzY4OTk3MTY=", "number": 9, "title": "Getting a `configparser.DuplicateOptionError` when calling nbconvert", "user": {"login": "ocefpaf", "id": 950575, "node_id": "MDQ6VXNlcjk1MDU3NQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/950575?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ocefpaf", "html_url": "https://github.com/ocefpaf", "followers_url": "https://api.github.com/users/ocefpaf/followers", "following_url": "https://api.github.com/users/ocefpaf/following{/other_user}", "gists_url": "https://api.github.com/users/ocefpaf/gists{/gist_id}", "starred_url": "https://api.github.com/users/ocefpaf/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ocefpaf/subscriptions", "organizations_url": "https://api.github.com/users/ocefpaf/orgs", "repos_url": "https://api.github.com/users/ocefpaf/repos", "events_url": "https://api.github.com/users/ocefpaf/events{/privacy}", "received_events_url": "https://api.github.com/users/ocefpaf/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2016-09-14T12:55:06Z", "updated_at": "2016-09-14T13:04:27Z", "closed_at": "2016-09-14T13:04:27Z", "author_association": "NONE", "active_lock_reason": null, "body": "I am seeing a similar problem as https://github.com/jupyter/nbconvert/issues/298 but I am using the latest `entrypoints 0.2.2`. One can reproduce the error below by installing `jupyter` and `compliance-checker` together and then issuing: `entrypoints.get_single('nbconvert.exporters', 'python').load()`\n\n```\nTraceback (most recent call last):\n  File \"/home/travis/miniconda/envs/IOOS/bin/jupyter-nbconvert\", line 4, in <module>\n    from nbconvert.nbconvertapp import main\n  File \"/home/travis/miniconda/envs/IOOS/lib/python3.5/site-packages/nbconvert/nbconvertapp.py\", line 99, in <module>\n    class NbConvertApp(JupyterApp):\n  File \"/home/travis/miniconda/envs/IOOS/lib/python3.5/site-packages/nbconvert/nbconvertapp.py\", line 179, in NbConvertApp\n    \"\"\".format(get_export_names()))\n  File \"/home/travis/miniconda/envs/IOOS/lib/python3.5/site-packages/nbconvert/exporters/export.py\", line 210, in get_export_names\n    sorted(entrypoints.get_group_named('nbconvert.exporters'))\n  File \"/home/travis/miniconda/envs/IOOS/lib/python3.5/site-packages/entrypoints.py\", line 191, in get_group_named\n    for ep in get_group_all(group, path=path):\n  File \"/home/travis/miniconda/envs/IOOS/lib/python3.5/site-packages/entrypoints.py\", line 202, in get_group_all\n    for config, distro in iter_files_distros(path=path):\n  File \"/home/travis/miniconda/envs/IOOS/lib/python3.5/site-packages/entrypoints.py\", line 168, in iter_files_distros\n    cp.read(path)\n  File \"/home/travis/miniconda/envs/IOOS/lib/python3.5/configparser.py\", line 696, in read\n    self._read(fp, filename)\n  File \"/home/travis/miniconda/envs/IOOS/lib/python3.5/configparser.py\", line 1089, in _read\n    fpname, lineno)\nconfigparser.DuplicateOptionError: While reading from '/home/travis/miniconda/envs/IOOS/lib/python3.5/site-packages/compliance_checker-2.2.0-py3.5.egg-info/entry_points.txt' [line  3]: option 'acdd' in section 'compliance_checker.suites' already exists\n```\n\nNot sure how to fix that...\n\nxref: https://github.com/ioos/compliance-checker/issues/300\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/8", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/8/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/8/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/8/events", "html_url": "https://github.com/takluyver/entrypoints/issues/8", "id": 171606119, "node_id": "MDU6SXNzdWUxNzE2MDYxMTk=", "number": 8, "title": "Cannot install from sources", "user": {"login": "jdemeyer", "id": 3625785, "node_id": "MDQ6VXNlcjM2MjU3ODU=", "avatar_url": "https://avatars0.githubusercontent.com/u/3625785?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jdemeyer", "html_url": "https://github.com/jdemeyer", "followers_url": "https://api.github.com/users/jdemeyer/followers", "following_url": "https://api.github.com/users/jdemeyer/following{/other_user}", "gists_url": "https://api.github.com/users/jdemeyer/gists{/gist_id}", "starred_url": "https://api.github.com/users/jdemeyer/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jdemeyer/subscriptions", "organizations_url": "https://api.github.com/users/jdemeyer/orgs", "repos_url": "https://api.github.com/users/jdemeyer/repos", "events_url": "https://api.github.com/users/jdemeyer/events{/privacy}", "received_events_url": "https://api.github.com/users/jdemeyer/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2016-08-17T08:51:37Z", "updated_at": "2016-08-17T12:51:55Z", "closed_at": "2016-08-17T08:57:27Z", "author_association": "NONE", "active_lock_reason": null, "body": "This repository is missing a `setup.py` file. Unless I am missing something, this means that it cannot be installed from source.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/7", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/7/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/7/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/7/events", "html_url": "https://github.com/takluyver/entrypoints/issues/7", "id": 159393767, "node_id": "MDU6SXNzdWUxNTkzOTM3Njc=", "number": 7, "title": "Can't install with buildout", "user": {"login": "andehen", "id": 754494, "node_id": "MDQ6VXNlcjc1NDQ5NA==", "avatar_url": "https://avatars0.githubusercontent.com/u/754494?v=4", "gravatar_id": "", "url": "https://api.github.com/users/andehen", "html_url": "https://github.com/andehen", "followers_url": "https://api.github.com/users/andehen/followers", "following_url": "https://api.github.com/users/andehen/following{/other_user}", "gists_url": "https://api.github.com/users/andehen/gists{/gist_id}", "starred_url": "https://api.github.com/users/andehen/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/andehen/subscriptions", "organizations_url": "https://api.github.com/users/andehen/orgs", "repos_url": "https://api.github.com/users/andehen/repos", "events_url": "https://api.github.com/users/andehen/events{/privacy}", "received_events_url": "https://api.github.com/users/andehen/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-06-09T12:18:32Z", "updated_at": "2016-06-09T12:57:12Z", "closed_at": "2016-06-09T12:57:12Z", "author_association": "NONE", "active_lock_reason": null, "body": "Trying to install another package (Jupyter) through buildout, but it fails at this package when installing  dependencies.\n\n```\nGetting distribution for 'entrypoints'.\nWhile:\n  Installing all.\n  Getting distribution for 'entrypoints'.\nError: Couldn't find a distribution for 'entrypoints'.\n```\n\nSame happens if you try to install entrypoints directly with buildout.\n\nNot sure why it can't find the package, as it is registered on PyPi. Could it be due to his package not having a setup.py file?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/6", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/6/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/6/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/6/events", "html_url": "https://github.com/takluyver/entrypoints/issues/6", "id": 158085457, "node_id": "MDU6SXNzdWUxNTgwODU0NTc=", "number": 6, "title": "No suitable distribution", "user": {"login": "ltaulell", "id": 1918606, "node_id": "MDQ6VXNlcjE5MTg2MDY=", "avatar_url": "https://avatars1.githubusercontent.com/u/1918606?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ltaulell", "html_url": "https://github.com/ltaulell", "followers_url": "https://api.github.com/users/ltaulell/followers", "following_url": "https://api.github.com/users/ltaulell/following{/other_user}", "gists_url": "https://api.github.com/users/ltaulell/gists{/gist_id}", "starred_url": "https://api.github.com/users/ltaulell/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ltaulell/subscriptions", "organizations_url": "https://api.github.com/users/ltaulell/orgs", "repos_url": "https://api.github.com/users/ltaulell/repos", "events_url": "https://api.github.com/users/ltaulell/events{/privacy}", "received_events_url": "https://api.github.com/users/ltaulell/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2016-06-02T08:27:54Z", "updated_at": "2016-06-02T12:50:51Z", "closed_at": "2016-06-02T12:50:51Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi,\n\njupyter-1.0.0 metapackage has a dependency on entrypoints\n\nTrying to install jupyter issue an error on entrypoints:\n\n```\nSearching for entrypoints\nReading https://pypi.python.org/simple/entrypoints/\nNo local packages or download links found for entrypoints\nerror: Could not find suitable distribution for Requirement.parse('entrypoints')\n```\n\nForcing to the whl file does no better:\n\n```\nProcessing entrypoints-0.2.2-py2.py3-none-any.whl\nerror: Couldn't find a setup script in /tmp/easy_install-psn0idx6/entrypoints-0.2.2-py2.py3-none-any.whl\n```\n\nBests\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/5", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/5/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/5/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/5/events", "html_url": "https://github.com/takluyver/entrypoints/issues/5", "id": 150647247, "node_id": "MDU6SXNzdWUxNTA2NDcyNDc=", "number": 5, "title": "Upload source archive to PyPI", "user": {"login": "FRidh", "id": 2129135, "node_id": "MDQ6VXNlcjIxMjkxMzU=", "avatar_url": "https://avatars3.githubusercontent.com/u/2129135?v=4", "gravatar_id": "", "url": "https://api.github.com/users/FRidh", "html_url": "https://github.com/FRidh", "followers_url": "https://api.github.com/users/FRidh/followers", "following_url": "https://api.github.com/users/FRidh/following{/other_user}", "gists_url": "https://api.github.com/users/FRidh/gists{/gist_id}", "starred_url": "https://api.github.com/users/FRidh/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/FRidh/subscriptions", "organizations_url": "https://api.github.com/users/FRidh/orgs", "repos_url": "https://api.github.com/users/FRidh/repos", "events_url": "https://api.github.com/users/FRidh/events{/privacy}", "received_events_url": "https://api.github.com/users/FRidh/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 9, "created_at": "2016-04-24T10:21:36Z", "updated_at": "2016-04-24T11:41:54Z", "closed_at": "2016-04-24T10:23:58Z", "author_association": "NONE", "active_lock_reason": null, "body": "Could you upload a source archive to PyPI? Right now there's only a .whl and this is a bit of a problem when trying to build nbconvert from source.\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/4", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/4/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/4/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/4/events", "html_url": "https://github.com/takluyver/entrypoints/issues/4", "id": 148775697, "node_id": "MDU6SXNzdWUxNDg3NzU2OTc=", "number": 4, "title": "please keep providing source tarball on PyPI", "user": {"login": "sandrotosi", "id": 346648, "node_id": "MDQ6VXNlcjM0NjY0OA==", "avatar_url": "https://avatars2.githubusercontent.com/u/346648?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sandrotosi", "html_url": "https://github.com/sandrotosi", "followers_url": "https://api.github.com/users/sandrotosi/followers", "following_url": "https://api.github.com/users/sandrotosi/following{/other_user}", "gists_url": "https://api.github.com/users/sandrotosi/gists{/gist_id}", "starred_url": "https://api.github.com/users/sandrotosi/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sandrotosi/subscriptions", "organizations_url": "https://api.github.com/users/sandrotosi/orgs", "repos_url": "https://api.github.com/users/sandrotosi/repos", "events_url": "https://api.github.com/users/sandrotosi/events{/privacy}", "received_events_url": "https://api.github.com/users/sandrotosi/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-04-15T21:37:08Z", "updated_at": "2016-04-15T22:08:18Z", "closed_at": "2016-04-15T22:08:18Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello,\ncould you please consider keep providing (and also add to the current releases) source tarball on PyPI and not only wheels? there are some situation where it's preferable to download the tarball\n\nthanks!\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/3", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/3/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/3/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/3/events", "html_url": "https://github.com/takluyver/entrypoints/issues/3", "id": 148740931, "node_id": "MDU6SXNzdWUxNDg3NDA5MzE=", "number": 3, "title": "TypeError: argument of type 'instance' is not iterable", "user": {"login": "mforbes", "id": 1028433, "node_id": "MDQ6VXNlcjEwMjg0MzM=", "avatar_url": "https://avatars1.githubusercontent.com/u/1028433?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mforbes", "html_url": "https://github.com/mforbes", "followers_url": "https://api.github.com/users/mforbes/followers", "following_url": "https://api.github.com/users/mforbes/following{/other_user}", "gists_url": "https://api.github.com/users/mforbes/gists{/gist_id}", "starred_url": "https://api.github.com/users/mforbes/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mforbes/subscriptions", "organizations_url": "https://api.github.com/users/mforbes/orgs", "repos_url": "https://api.github.com/users/mforbes/repos", "events_url": "https://api.github.com/users/mforbes/events{/privacy}", "received_events_url": "https://api.github.com/users/mforbes/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 18, "created_at": "2016-04-15T18:57:36Z", "updated_at": "2016-11-21T16:23:38Z", "closed_at": "2016-05-21T09:29:07Z", "author_association": "NONE", "active_lock_reason": null, "body": "Not exactly sure where this is coming from, but with version 0.2 (installed with conda), I cannot run `juypter nbconvert`:\n\n```\n$ jupyter nbconvert\nTraceback (most recent call last):\n  File \".../bin/jupyter-nbconvert\", line 3, in <module>\n    from nbconvert.nbconvertapp import main\n  File \".../lib/python2.7/site-packages/nbconvert/nbconvertapp.py\", line 99, in <module>\n    class NbConvertApp(JupyterApp):\n  File \".../lib/python2.7/site-packages/nbconvert/nbconvertapp.py\", line 179, in NbConvertApp\n    \"\"\".format(get_export_names()))\n  File \".../lib/python2.7/site-packages/nbconvert/exporters/export.py\", line 210, in get_export_names\n    sorted(entrypoints.get_group_named('nbconvert.exporters'))\n  File \"/data/apps/anaconda/envs/work/lib/python2.7/site-packages/entrypoints.py\", line 183, in get_group_named\n    for ep in get_group_all(group, path=path):\n  File \".../lib/python2.7/site-packages/entrypoints.py\", line 195, in get_group_all\n    if group in config:\nTypeError: argument of type 'instance' is not iterable\n```\n\n`config` is a `<ConfigParser.ConfigParser instance at 0x10592a320>`. \n\n`conda info` gives:\n\n```\nnbconvert 4.2.0 py27_0\nentrypoints 0.2 py27_0\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/2", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/2/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/2/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/2/events", "html_url": "https://github.com/takluyver/entrypoints/issues/2", "id": 142326792, "node_id": "MDU6SXNzdWUxNDIzMjY3OTI=", "number": 2, "title": "configparser dependency", "user": {"login": "aldanor", "id": 2418513, "node_id": "MDQ6VXNlcjI0MTg1MTM=", "avatar_url": "https://avatars0.githubusercontent.com/u/2418513?v=4", "gravatar_id": "", "url": "https://api.github.com/users/aldanor", "html_url": "https://github.com/aldanor", "followers_url": "https://api.github.com/users/aldanor/followers", "following_url": "https://api.github.com/users/aldanor/following{/other_user}", "gists_url": "https://api.github.com/users/aldanor/gists{/gist_id}", "starred_url": "https://api.github.com/users/aldanor/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/aldanor/subscriptions", "organizations_url": "https://api.github.com/users/aldanor/orgs", "repos_url": "https://api.github.com/users/aldanor/repos", "events_url": "https://api.github.com/users/aldanor/events{/privacy}", "received_events_url": "https://api.github.com/users/aldanor/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2016-03-21T11:58:52Z", "updated_at": "2016-07-28T14:07:26Z", "closed_at": "2016-07-28T14:07:26Z", "author_association": "NONE", "active_lock_reason": null, "body": "Is there any good reason to actually pull a configparser backport dependency from PyPI on `python == 2.7` rather than using the standard library? Could this dependency be eliminated in favor of `ConfigParser`?\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/takluyver/entrypoints/issues/1", "repository_url": "https://api.github.com/repos/takluyver/entrypoints", "labels_url": "https://api.github.com/repos/takluyver/entrypoints/issues/1/labels{/name}", "comments_url": "https://api.github.com/repos/takluyver/entrypoints/issues/1/comments", "events_url": "https://api.github.com/repos/takluyver/entrypoints/issues/1/events", "html_url": "https://github.com/takluyver/entrypoints/issues/1", "id": 142320087, "node_id": "MDU6SXNzdWUxNDIzMjAwODc=", "number": 1, "title": "Add `setup.py`?", "user": {"login": "aldanor", "id": 2418513, "node_id": "MDQ6VXNlcjI0MTg1MTM=", "avatar_url": "https://avatars0.githubusercontent.com/u/2418513?v=4", "gravatar_id": "", "url": "https://api.github.com/users/aldanor", "html_url": "https://github.com/aldanor", "followers_url": "https://api.github.com/users/aldanor/followers", "following_url": "https://api.github.com/users/aldanor/following{/other_user}", "gists_url": "https://api.github.com/users/aldanor/gists{/gist_id}", "starred_url": "https://api.github.com/users/aldanor/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/aldanor/subscriptions", "organizations_url": "https://api.github.com/users/aldanor/orgs", "repos_url": "https://api.github.com/users/aldanor/repos", "events_url": "https://api.github.com/users/aldanor/events{/privacy}", "received_events_url": "https://api.github.com/users/aldanor/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2016-03-21T11:24:57Z", "updated_at": "2016-03-21T11:57:43Z", "closed_at": "2016-03-21T11:33:45Z", "author_association": "NONE", "active_lock_reason": null, "body": "@takluyver \n\nSince this package is now a dependency of `nbconvert`, would you mind adding conventional setupools installer (`setup.py`)? Even though it's a trivial package, some tools expect `setup.py` to exist (e.g. `conda-build`, `tox` and many others).\n\nThis is just a suggestion and would be up to you of course :)\n\nEdit: I understand you're using your own pypi uploader/wrapper, this is a different question though.\n", "performed_via_github_app": null, "score": 1.0}]}