{"total_count": 2, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/mahmoud/face/issues/9", "repository_url": "https://api.github.com/repos/mahmoud/face", "labels_url": "https://api.github.com/repos/mahmoud/face/issues/9/labels{/name}", "comments_url": "https://api.github.com/repos/mahmoud/face/issues/9/comments", "events_url": "https://api.github.com/repos/mahmoud/face/issues/9/events", "html_url": "https://github.com/mahmoud/face/issues/9", "id": 581424296, "node_id": "MDU6SXNzdWU1ODE0MjQyOTY=", "number": 9, "title": "Add link to API docs from README", "user": {"login": "moshez", "id": 422703, "node_id": "MDQ6VXNlcjQyMjcwMw==", "avatar_url": "https://avatars0.githubusercontent.com/u/422703?v=4", "gravatar_id": "", "url": "https://api.github.com/users/moshez", "html_url": "https://github.com/moshez", "followers_url": "https://api.github.com/users/moshez/followers", "following_url": "https://api.github.com/users/moshez/following{/other_user}", "gists_url": "https://api.github.com/users/moshez/gists{/gist_id}", "starred_url": "https://api.github.com/users/moshez/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/moshez/subscriptions", "organizations_url": "https://api.github.com/users/moshez/orgs", "repos_url": "https://api.github.com/users/moshez/repos", "events_url": "https://api.github.com/users/moshez/events{/privacy}", "received_events_url": "https://api.github.com/users/moshez/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2020-03-14T23:51:21Z", "updated_at": "2020-05-25T21:49:55Z", "closed_at": "2020-05-25T21:49:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "It is not obvious where the canonical documentation lives", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mahmoud/face/issues/6", "repository_url": "https://api.github.com/repos/mahmoud/face", "labels_url": "https://api.github.com/repos/mahmoud/face/issues/6/labels{/name}", "comments_url": "https://api.github.com/repos/mahmoud/face/issues/6/comments", "events_url": "https://api.github.com/repos/mahmoud/face/issues/6/events", "html_url": "https://github.com/mahmoud/face/issues/6", "id": 323453660, "node_id": "MDU6SXNzdWUzMjM0NTM2NjA=", "number": 6, "title": "Unexpected error message when incorrect subcmd supplied", "user": {"login": "steven-cutting", "id": 8365892, "node_id": "MDQ6VXNlcjgzNjU4OTI=", "avatar_url": "https://avatars0.githubusercontent.com/u/8365892?v=4", "gravatar_id": "", "url": "https://api.github.com/users/steven-cutting", "html_url": "https://github.com/steven-cutting", "followers_url": "https://api.github.com/users/steven-cutting/followers", "following_url": "https://api.github.com/users/steven-cutting/following{/other_user}", "gists_url": "https://api.github.com/users/steven-cutting/gists{/gist_id}", "starred_url": "https://api.github.com/users/steven-cutting/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/steven-cutting/subscriptions", "organizations_url": "https://api.github.com/users/steven-cutting/orgs", "repos_url": "https://api.github.com/users/steven-cutting/repos", "events_url": "https://api.github.com/users/steven-cutting/events{/privacy}", "received_events_url": "https://api.github.com/users/steven-cutting/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-05-16T03:09:51Z", "updated_at": "2019-03-30T06:57:38Z", "closed_at": "2019-03-30T06:57:38Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "## Issue\r\n\r\nWhen an incorrect subcommand is supplied, the error says that there were `unexpected positional arguments`.\r\n\r\nBased on my understanding, positional arguments are not allowed at levels in which there exist further subcommands. So, I believe the error should say something along the lines of `incorrect subcommand provided`.\r\n\r\n## Reproduce\r\n\r\n```python\r\nfrom face import Command\r\n\r\ncmd = Command(lambda: print(\"foo\"), \"foo\")\r\nsubcmd = Command(lambda: print(\"bar\"), \"bar\")\r\nsubcmd.add(Command(lambda: print(\"baz\"), \"baz\"))\r\ncmd.add(subcmd)\r\n\r\ncmd.run(argv=[\"foo\", \"bar\", \"ba\"])  # ba should be baz\r\n```\r\n\r\nResults in the following error:\r\n\r\n```\r\nerror: foo bar: unexpected positional arguments: ['ba']\r\n```\r\n\r\n---\r\n\r\nIf you agree with the above, let me know and I can make it happen.\r\n", "performed_via_github_app": null, "score": 1.0}]}