{"total_count": 3, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils/issues/6", "repository_url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils", "labels_url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils/issues/6/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils/issues/6/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils/issues/6/events", "html_url": "https://github.com/mcmtroffaes/pybtex-docutils/issues/6", "id": 50662758, "node_id": "MDU6SXNzdWU1MDY2Mjc1OA==", "number": 6, "title": "Only 'emph' tag allowed", "user": {"login": "Jellby", "id": 7943459, "node_id": "MDQ6VXNlcjc5NDM0NTk=", "avatar_url": "https://avatars0.githubusercontent.com/u/7943459?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Jellby", "html_url": "https://github.com/Jellby", "followers_url": "https://api.github.com/users/Jellby/followers", "following_url": "https://api.github.com/users/Jellby/following{/other_user}", "gists_url": "https://api.github.com/users/Jellby/gists{/gist_id}", "starred_url": "https://api.github.com/users/Jellby/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Jellby/subscriptions", "organizations_url": "https://api.github.com/users/Jellby/orgs", "repos_url": "https://api.github.com/users/Jellby/repos", "events_url": "https://api.github.com/users/Jellby/events{/privacy}", "received_events_url": "https://api.github.com/users/Jellby/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 51052685, "node_id": "MDU6TGFiZWw1MTA1MjY4NQ==", "url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils/labels/bug", "name": "bug", "color": "fc2929", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2014-12-02T15:07:01Z", "updated_at": "2014-12-08T09:15:09Z", "closed_at": "2014-12-02T16:55:34Z", "author_association": "NONE", "active_lock_reason": null, "body": "When formatting an entry, I want to use other tags than just 'emph', but then I get messages like:\n\n```\n  File \"build/bdist.linux-x86_64/egg/pybtex_docutils.py\", line 57, in format_tag\n    tag = self.tags[tag_name]\nKeyError: 'b'\n```\n\nLooking at the code, it looks like only 'emph' is defined:\n\n```\ntags = {\n    'emph': docutils.nodes.emphasis,\n}\n```\n\nHow can I define other tags? (in particular, when using the sphinxcontrib.bibtex extension.)\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils/issues/4", "repository_url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils", "labels_url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils/issues/4/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils/issues/4/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils/issues/4/events", "html_url": "https://github.com/mcmtroffaes/pybtex-docutils/issues/4", "id": 46487025, "node_id": "MDU6SXNzdWU0NjQ4NzAyNQ==", "number": 4, "title": "'em' tag not defined", "user": {"login": "tino", "id": 99524, "node_id": "MDQ6VXNlcjk5NTI0", "avatar_url": "https://avatars2.githubusercontent.com/u/99524?v=4", "gravatar_id": "", "url": "https://api.github.com/users/tino", "html_url": "https://github.com/tino", "followers_url": "https://api.github.com/users/tino/followers", "following_url": "https://api.github.com/users/tino/following{/other_user}", "gists_url": "https://api.github.com/users/tino/gists{/gist_id}", "starred_url": "https://api.github.com/users/tino/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/tino/subscriptions", "organizations_url": "https://api.github.com/users/tino/orgs", "repos_url": "https://api.github.com/users/tino/repos", "events_url": "https://api.github.com/users/tino/events{/privacy}", "received_events_url": "https://api.github.com/users/tino/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 51052689, "node_id": "MDU6TGFiZWw1MTA1MjY4OQ==", "url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils/labels/question", "name": "question", "color": "cc317c", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2014-10-22T09:00:13Z", "updated_at": "2014-10-22T12:31:05Z", "closed_at": "2014-10-22T12:31:05Z", "author_association": "NONE", "active_lock_reason": null, "body": "Somehow `pybtex.richtext` wants an 'em' tag, which is not defined ('emph' is). Any idea why?\n\nFull traceback:\n\n```\n# Sphinx version: 1.2.3\n# Python version: 2.7.3\n# Docutils version: 0.12 release\n# Jinja2 version: 2.7.3\n# Loaded extensions:\n#   sphinx.ext.todo from /home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/sphinx/ext/todo.pyc\n#   utils.pybtex_apa_style from /home/spafe/apps/afstudeer-app/verslag_checkouts/v3/source/../utils/pybtex_apa_style.py\n#   sphinx.ext.oldcmarkup from /home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/sphinx/ext/oldcmarkup.pyc\n#   sphinxcontrib.bibtex from /home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/sphinxcontrib/bibtex/__init__.pyc\nTraceback (most recent call last):\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/sphinx/cmdline.py\", line 254, in main\n    app.build(force_all, filenames)\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/sphinx/application.py\", line 220, in build\n    self.builder.build_update()\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/sphinx/builders/__init__.py\", line 214, in build_update\n    'out of date' % len(to_build))\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/sphinx/builders/__init__.py\", line 234, in build\n    purple, length):\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/sphinx/builders/__init__.py\", line 134, in status_iterator\n    for item in iterable:\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/sphinx/environment.py\", line 478, in update_generator\n    self.read_doc(docname, app=app)\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/sphinx/environment.py\", line 628, in read_doc\n    pub.publish()\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/docutils/core.py\", line 218, in publish\n    self.apply_transforms()\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/docutils/core.py\", line 199, in apply_transforms\n    self.document.transformer.apply_transforms()\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/docutils/transforms/__init__.py\", line 171, in apply_transforms\n    transform.apply(**kwargs)\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/sphinxcontrib/bibtex/transforms.py\", line 112, in apply\n    citation = backend.citation(entry, self.document)\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/pybtex_docutils.py\", line 92, in citation\n    text = entry.text.render(self)\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/pybtex/richtext.py\", line 146, in render\n    rendered_list.append(item.render(backend))\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/pybtex/richtext.py\", line 146, in render\n    rendered_list.append(item.render(backend))\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/pybtex/richtext.py\", line 146, in render\n    rendered_list.append(item.render(backend))\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/pybtex/richtext.py\", line 303, in render\n    return backend.format_tag(self.name, text)\n  File \"/home/spafe/apps/afstudeer-app/local/lib/python2.7/site-packages/pybtex_docutils.py\", line 56, in format_tag\n    tag = self.tags[tag_name]\nKeyError: 'em'\n```\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils/issues/3", "repository_url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils", "labels_url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils/issues/3/labels{/name}", "comments_url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils/issues/3/comments", "events_url": "https://api.github.com/repos/mcmtroffaes/pybtex-docutils/issues/3/events", "html_url": "https://github.com/mcmtroffaes/pybtex-docutils/issues/3", "id": 19196161, "node_id": "MDU6SXNzdWUxOTE5NjE2MQ==", "number": 3, "title": "Can't process .bib file with doi fields", "user": {"login": "guyer", "id": 1830725, "node_id": "MDQ6VXNlcjE4MzA3MjU=", "avatar_url": "https://avatars3.githubusercontent.com/u/1830725?v=4", "gravatar_id": "", "url": "https://api.github.com/users/guyer", "html_url": "https://github.com/guyer", "followers_url": "https://api.github.com/users/guyer/followers", "following_url": "https://api.github.com/users/guyer/following{/other_user}", "gists_url": "https://api.github.com/users/guyer/gists{/gist_id}", "starred_url": "https://api.github.com/users/guyer/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/guyer/subscriptions", "organizations_url": "https://api.github.com/users/guyer/orgs", "repos_url": "https://api.github.com/users/guyer/repos", "events_url": "https://api.github.com/users/guyer/events{/privacy}", "received_events_url": "https://api.github.com/users/guyer/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2013-09-09T13:48:34Z", "updated_at": "2014-09-19T21:34:34Z", "closed_at": "2013-09-10T09:19:56Z", "author_association": "NONE", "active_lock_reason": null, "body": "We would like doi's rendered in our bibtex output and I see that the latest pybtex supports this. When I pip install pybtex, sphinx-bibtex, and pybtex-docutils from source and run on our docs, I get the following error:\n\n``` python\nAssertionError\n> /Users/guyer/.virtualenvs/petsc/src/pybtex-docutils/pybtex_docutils.py(61)format_href()\n-> assert isinstance(url, basestring)\n(Pdb) p url\n[u'http://dx.doi.org/', u'10.1146/annurev.matsci.32.101901.155803']\n```\n\nI've got:\n- Sphinx v1.2b1\n- sphinxcontrib-bibtex 0.2.9a1 mcmtroffaes/sphinxcontrib-bibtex@dd2298dd4d\n- pybtex-docutils 0.2.1a0 3649b9f771\n- pybtex  0.16 http://bazaar.launchpad.net/~ero-sennin/pybtex/trunk/revision/842\n\nFWIW, the .bib entry in question is\n\n``` bibtex\n@article{BoettingerReview:2002,\n   author =  {W. J. Boettinger and J. A. Warren and C. Beckermann and A.\n              Karma},\n   title =   {Phase-field simulation of solidification},\n   journal = {Annual Review of Materials Research},\n   volume =  32,\n   year =    2002,\n   pages =   {163-194},\n   url =     {http://arjournals.annualreviews.org/doi/abs/10.1146/annurev.matsci.32.101901.155803},\n   doi =     {10.1146/annurev.matsci.32.101901.155803},\n}\n```\n", "performed_via_github_app": null, "score": 1.0}]}