{"total_count": 36, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/84", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/84/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/84/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/84/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/84", "id": 680196653, "node_id": "MDU6SXNzdWU2ODAxOTY2NTM=", "number": 84, "title": "Bug in new version in generate?", "user": {"login": "RosanneZe", "id": 25586561, "node_id": "MDQ6VXNlcjI1NTg2NTYx", "avatar_url": "https://avatars0.githubusercontent.com/u/25586561?v=4", "gravatar_id": "", "url": "https://api.github.com/users/RosanneZe", "html_url": "https://github.com/RosanneZe", "followers_url": "https://api.github.com/users/RosanneZe/followers", "following_url": "https://api.github.com/users/RosanneZe/following{/other_user}", "gists_url": "https://api.github.com/users/RosanneZe/gists{/gist_id}", "starred_url": "https://api.github.com/users/RosanneZe/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/RosanneZe/subscriptions", "organizations_url": "https://api.github.com/users/RosanneZe/orgs", "repos_url": "https://api.github.com/users/RosanneZe/repos", "events_url": "https://api.github.com/users/RosanneZe/events{/privacy}", "received_events_url": "https://api.github.com/users/RosanneZe/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 718363861, "node_id": "MDU6TGFiZWw3MTgzNjM4NjE=", "url": "https://api.github.com/repos/WhyNotHugo/python-barcode/labels/bug", "name": "bug", "color": "ee0701", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 5, "created_at": "2020-08-17T12:27:23Z", "updated_at": "2020-08-18T09:25:09Z", "closed_at": "2020-08-18T09:25:09Z", "author_association": "NONE", "active_lock_reason": null, "body": "In the new version if I try to use:\r\n\r\n```python\r\nimport barcode\r\nbarcode.generate('ean13', '123455559121112')\r\n```\r\nI get an error `TypeError: get() got an unexpected keyword argument 'writer_options'` I get this both in version 0.12 and 0.13. Is there something I can do about this, or is this a bug?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/80", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/80/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/80/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/80/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/80", "id": 664533087, "node_id": "MDU6SXNzdWU2NjQ1MzMwODc=", "number": 80, "title": "generate wrong number ", "user": {"login": "MRTUNC", "id": 42121592, "node_id": "MDQ6VXNlcjQyMTIxNTky", "avatar_url": "https://avatars3.githubusercontent.com/u/42121592?v=4", "gravatar_id": "", "url": "https://api.github.com/users/MRTUNC", "html_url": "https://github.com/MRTUNC", "followers_url": "https://api.github.com/users/MRTUNC/followers", "following_url": "https://api.github.com/users/MRTUNC/following{/other_user}", "gists_url": "https://api.github.com/users/MRTUNC/gists{/gist_id}", "starred_url": "https://api.github.com/users/MRTUNC/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/MRTUNC/subscriptions", "organizations_url": "https://api.github.com/users/MRTUNC/orgs", "repos_url": "https://api.github.com/users/MRTUNC/repos", "events_url": "https://api.github.com/users/MRTUNC/events{/privacy}", "received_events_url": "https://api.github.com/users/MRTUNC/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-07-23T14:40:16Z", "updated_at": "2020-08-15T21:11:04Z", "closed_at": "2020-08-15T21:11:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "This module is usefull and easy.thanks  developer.\r\nBut \u0131 have got  a problem that generate wrong number\r\nhere is my code:\r\n\r\n```python\r\nfrom barcode import EAN13\r\nimport barcode\r\nfrom barcode.writer import ImageWriter\r\n\r\nserino=\"1234567891012\"\r\ndosyaadi=str(serino)+\".jpg\"\r\nwith open(dosyaadi, 'wb') as f:\r\n    EAN13(str(serino), writer=ImageWriter()).write(f)\r\n```\r\n\r\n![image](https://user-images.githubusercontent.com/42121592/88299652-4558c000-cd0b-11ea-829c-6f2d52901288.png)\r\n\r\n As you see ;\r\nlast caracter is not true;\r\nI have tried too much but \u0131 cant ;\r\nWould you please help me  ?\r\nWhat is wrong ? ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/78", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/78/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/78/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/78/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/78", "id": 644073638, "node_id": "MDU6SXNzdWU2NDQwNzM2Mzg=", "number": 78, "title": "Does not work on Raspberry Pi with either Python 2.7 or 3.5.3", "user": {"login": "peterantypas", "id": 1565933, "node_id": "MDQ6VXNlcjE1NjU5MzM=", "avatar_url": "https://avatars0.githubusercontent.com/u/1565933?v=4", "gravatar_id": "", "url": "https://api.github.com/users/peterantypas", "html_url": "https://github.com/peterantypas", "followers_url": "https://api.github.com/users/peterantypas/followers", "following_url": "https://api.github.com/users/peterantypas/following{/other_user}", "gists_url": "https://api.github.com/users/peterantypas/gists{/gist_id}", "starred_url": "https://api.github.com/users/peterantypas/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/peterantypas/subscriptions", "organizations_url": "https://api.github.com/users/peterantypas/orgs", "repos_url": "https://api.github.com/users/peterantypas/repos", "events_url": "https://api.github.com/users/peterantypas/events{/privacy}", "received_events_url": "https://api.github.com/users/peterantypas/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-06-23T19:01:57Z", "updated_at": "2020-06-23T19:53:05Z", "closed_at": "2020-06-23T19:53:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "Installed with both pip and pip3. The ImageWriter class cannot be instantiated. This causes all example code to fail.\r\n\r\n> Python 3.5.3 (default, Sep 27 2018, 17:25:39) \r\n[GCC 6.3.0 20170516] on linux\r\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\r\n>>> w = barcode.writer.ImageWriter()\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\nNameError: name 'barcode' is not defined\r\n>>> from barcode.writer import ImageWriter\r\n>>> w = ImageWriter()\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\nTypeError: 'NoneType' object is not callable\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/76", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/76/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/76/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/76/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/76", "id": 640941283, "node_id": "MDU6SXNzdWU2NDA5NDEyODM=", "number": 76, "title": "OSError : Cannot open resource ", "user": {"login": "TONYSTARK-EDITH", "id": 53046920, "node_id": "MDQ6VXNlcjUzMDQ2OTIw", "avatar_url": "https://avatars2.githubusercontent.com/u/53046920?v=4", "gravatar_id": "", "url": "https://api.github.com/users/TONYSTARK-EDITH", "html_url": "https://github.com/TONYSTARK-EDITH", "followers_url": "https://api.github.com/users/TONYSTARK-EDITH/followers", "following_url": "https://api.github.com/users/TONYSTARK-EDITH/following{/other_user}", "gists_url": "https://api.github.com/users/TONYSTARK-EDITH/gists{/gist_id}", "starred_url": "https://api.github.com/users/TONYSTARK-EDITH/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/TONYSTARK-EDITH/subscriptions", "organizations_url": "https://api.github.com/users/TONYSTARK-EDITH/orgs", "repos_url": "https://api.github.com/users/TONYSTARK-EDITH/repos", "events_url": "https://api.github.com/users/TONYSTARK-EDITH/events{/privacy}", "received_events_url": "https://api.github.com/users/TONYSTARK-EDITH/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-06-18T06:19:59Z", "updated_at": "2020-06-18T11:20:03Z", "closed_at": "2020-06-18T11:20:03Z", "author_association": "NONE", "active_lock_reason": null, "body": "I tried to generate barcode using graphical user interface made using `pyqt5`, it works when i run the script but when i made it as an application (.exe) when i try to generate it , it throws an traceback of \r\n```\r\nTraceback: (most recent call last)\r\n File \"Bar.py\" line 37, in <lambda>\r\n File \"Bar.py\" line 51, in testEan\r\n File \"site packages\\barcode\\base.py\" line 68 in save\r\n File \"site packages\\barcode\\codex.py\" line 261 in render\r\n File \"site packages\\barcode\\base.py\" line 111 in render\r\n File \"site packages\\barcode\\writer.py\" line 226 in render\r\n File \"site packages\\barcode\\writer.py\" line 356 in _paint_text\r\n File \"site packages\\PIL\\ImageFont.py\" line 648 in truetype\r\n File \"site packages\\PIL\\ImageFont.py\" line 645 in freetype\r\n File \"site packages\\PIL\\ImageFont.py\" line 193 in __init__\r\nOsError : cannot open resource\r\n```\r\n\r\nMy code is \r\n```\r\nimport pkg_resources.py2_warn\r\nfrom PyQt5 import QtCore, QtGui, QtWidgets\r\nimport barcode\r\nfrom barcode.writer import ImageWriter\r\nimport shutil\r\nimport os\r\n\r\n\r\nclass Ui_Form(object):\r\n    def setupUi(self, Form):\r\n        Form.setObjectName(\"Form\")\r\n        Form.resize(607, 503)\r\n        self.pushButton = QtWidgets.QPushButton(Form)\r\n        self.pushButton.setGeometry(QtCore.QRect(-170, 220, 93, 28))\r\n        self.pushButton.setObjectName(\"pushButton\")\r\n        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)\r\n        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(130, 180, 311, 80))\r\n        self.horizontalLayoutWidget.setObjectName(\"horizontalLayoutWidget\")\r\n        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)\r\n        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)\r\n        self.horizontalLayout.setObjectName(\"horizontalLayout\")\r\n        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)\r\n        self.lineEdit.setObjectName(\"lineEdit\")\r\n        self.horizontalLayout.addWidget(self.lineEdit)\r\n        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)\r\n        self.pushButton_2.setObjectName(\"pushButton_2\")\r\n        self.horizontalLayout.addWidget(self.pushButton_2)\r\n        self.pushButton_2.clicked.connect(lambda: self.testEan(self.lineEdit.text()))\r\n        self.retranslateUi(Form)\r\n        QtCore.QMetaObject.connectSlotsByName(Form)\r\n\r\n    def retranslateUi(self, Form):\r\n        _translate = QtCore.QCoreApplication.translate\r\n        Form.setWindowTitle(_translate(\"Form\", \"Form\"))\r\n        self.pushButton.setText(_translate(\"Form\", \"PushButton\"))\r\n        self.pushButton_2.setText(_translate(\"Form\", \"Generate\"))\r\n\r\n    def testEan(self, i):\r\n        EAN = barcode.get_barcode_class('code128')\r\n        s = '0' * (8 - len(str(i)) - 1) + str(i)\r\n        ean = EAN(s, writer=ImageWriter())\r\n        fullname = ean.save(str(i))\r\n        QtWidgets.QMessageBox().about(QtWidgets.QWidget(), \"Info\", \"Success\")\r\n\r\n\r\nif __name__ == \"__main__\":\r\n    import sys\r\n\r\n    app = QtWidgets.QApplication(sys.argv)\r\n    Form = QtWidgets.QWidget()\r\n    ui = Ui_Form()\r\n    ui.setupUi(Form)\r\n    Form.show()\r\n    sys.exit(app.exec_())\r\n```\r\n\r\n**### It works perfectly when i try to run it as a script but when i convert it to an standalone application it gives some error**\r\n```\r\nOS           :  windows 10\r\nPython       : 3.8.3\r\nPyinstaller  : 3.6\r\nbarcode      : 0.11.0\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/69", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/69/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/69/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/69/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/69", "id": 607019958, "node_id": "MDU6SXNzdWU2MDcwMTk5NTg=", "number": 69, "title": "Cannot save as png after packaging into exe file", "user": {"login": "Yinjiafeng", "id": 60877121, "node_id": "MDQ6VXNlcjYwODc3MTIx", "avatar_url": "https://avatars3.githubusercontent.com/u/60877121?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Yinjiafeng", "html_url": "https://github.com/Yinjiafeng", "followers_url": "https://api.github.com/users/Yinjiafeng/followers", "following_url": "https://api.github.com/users/Yinjiafeng/following{/other_user}", "gists_url": "https://api.github.com/users/Yinjiafeng/gists{/gist_id}", "starred_url": "https://api.github.com/users/Yinjiafeng/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Yinjiafeng/subscriptions", "organizations_url": "https://api.github.com/users/Yinjiafeng/orgs", "repos_url": "https://api.github.com/users/Yinjiafeng/repos", "events_url": "https://api.github.com/users/Yinjiafeng/events{/privacy}", "received_events_url": "https://api.github.com/users/Yinjiafeng/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2020-04-26T14:03:09Z", "updated_at": "2020-05-25T08:36:13Z", "closed_at": "2020-05-25T08:36:04Z", "author_association": "NONE", "active_lock_reason": null, "body": "![\u5fae\u4fe1\u622a\u56fe_20200426105205](https://user-images.githubusercontent.com/60877121/80309750-6f344080-8809-11ea-8828-0116bd39397a.png)\r\n```\r\nTraceback (most recent call last):\r\n  File \"site-packages\\PIL\\ImageFont.py\", line 186, in __init__\r\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 9: ordinal not in range(128)\r\n```\r\nThis error occurs under python3.6, how to solve it", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/68", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/68/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/68/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/68/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/68", "id": 596031926, "node_id": "MDU6SXNzdWU1OTYwMzE5MjY=", "number": 68, "title": "barcode.get  writer_options not used", "user": {"login": "karna48", "id": 26833777, "node_id": "MDQ6VXNlcjI2ODMzNzc3", "avatar_url": "https://avatars0.githubusercontent.com/u/26833777?v=4", "gravatar_id": "", "url": "https://api.github.com/users/karna48", "html_url": "https://github.com/karna48", "followers_url": "https://api.github.com/users/karna48/followers", "following_url": "https://api.github.com/users/karna48/following{/other_user}", "gists_url": "https://api.github.com/users/karna48/gists{/gist_id}", "starred_url": "https://api.github.com/users/karna48/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/karna48/subscriptions", "organizations_url": "https://api.github.com/users/karna48/orgs", "repos_url": "https://api.github.com/users/karna48/repos", "events_url": "https://api.github.com/users/karna48/events{/privacy}", "received_events_url": "https://api.github.com/users/karna48/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 1868934624, "node_id": "MDU6TGFiZWwxODY4OTM0NjI0", "url": "https://api.github.com/repos/WhyNotHugo/python-barcode/labels/api-inconsistency", "name": "api-inconsistency", "color": "721aba", "default": false, "description": "inconsistencies in the API between various barcodes or writers"}, {"id": 718363861, "node_id": "MDU6TGFiZWw3MTgzNjM4NjE=", "url": "https://api.github.com/repos/WhyNotHugo/python-barcode/labels/bug", "name": "bug", "color": "ee0701", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-04-07T17:26:27Z", "updated_at": "2020-05-15T07:12:02Z", "closed_at": "2020-05-15T07:12:02Z", "author_association": "NONE", "active_lock_reason": null, "body": "def get(name, code=None, writer=None, options=None, writer_options=None):\r\n\r\ndoes not pass writer_options anywhere and the documentation does not speak about it", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/64", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/64/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/64/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/64/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/64", "id": 583224643, "node_id": "MDU6SXNzdWU1ODMyMjQ2NDM=", "number": 64, "title": "Transparent ImageWriter background", "user": {"login": "Aculisme", "id": 26525103, "node_id": "MDQ6VXNlcjI2NTI1MTAz", "avatar_url": "https://avatars2.githubusercontent.com/u/26525103?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Aculisme", "html_url": "https://github.com/Aculisme", "followers_url": "https://api.github.com/users/Aculisme/followers", "following_url": "https://api.github.com/users/Aculisme/following{/other_user}", "gists_url": "https://api.github.com/users/Aculisme/gists{/gist_id}", "starred_url": "https://api.github.com/users/Aculisme/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Aculisme/subscriptions", "organizations_url": "https://api.github.com/users/Aculisme/orgs", "repos_url": "https://api.github.com/users/Aculisme/repos", "events_url": "https://api.github.com/users/Aculisme/events{/privacy}", "received_events_url": "https://api.github.com/users/Aculisme/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 718363863, "node_id": "MDU6TGFiZWw3MTgzNjM4NjM=", "url": "https://api.github.com/repos/WhyNotHugo/python-barcode/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2020-03-17T18:47:55Z", "updated_at": "2020-08-18T05:33:19Z", "closed_at": "2020-08-15T20:15:59Z", "author_association": "NONE", "active_lock_reason": null, "body": "I love this library, and was wondering whether there were any plans for allowing transparent backgrounds as a option for the `background` attribute in `barcode.writer.ImageWriter`, effectively allowing for png barcodes with transparent backgrounds that are easy to paste over other images in PIL post-processing. This could be implemented by allowing for `rgba(r,g,b,a)` as an input instead of just `white`, `black`, `orange`, etc.:\r\n```\r\noptions={\r\n            \"background\":\"rgba(0,0,0,0)\",\r\n            }\r\n```\r\nThanks.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/63", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/63/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/63/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/63/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/63", "id": 574855147, "node_id": "MDU6SXNzdWU1NzQ4NTUxNDc=", "number": 63, "title": "Unable to import barcode", "user": {"login": "Soumalya-Mondal", "id": 58221994, "node_id": "MDQ6VXNlcjU4MjIxOTk0", "avatar_url": "https://avatars3.githubusercontent.com/u/58221994?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Soumalya-Mondal", "html_url": "https://github.com/Soumalya-Mondal", "followers_url": "https://api.github.com/users/Soumalya-Mondal/followers", "following_url": "https://api.github.com/users/Soumalya-Mondal/following{/other_user}", "gists_url": "https://api.github.com/users/Soumalya-Mondal/gists{/gist_id}", "starred_url": "https://api.github.com/users/Soumalya-Mondal/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Soumalya-Mondal/subscriptions", "organizations_url": "https://api.github.com/users/Soumalya-Mondal/orgs", "repos_url": "https://api.github.com/users/Soumalya-Mondal/repos", "events_url": "https://api.github.com/users/Soumalya-Mondal/events{/privacy}", "received_events_url": "https://api.github.com/users/Soumalya-Mondal/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 718363867, "node_id": "MDU6TGFiZWw3MTgzNjM4Njc=", "url": "https://api.github.com/repos/WhyNotHugo/python-barcode/labels/question", "name": "question", "color": "cc317c", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2020-03-03T18:23:22Z", "updated_at": "2020-05-23T06:58:45Z", "closed_at": "2020-05-23T06:58:36Z", "author_association": "NONE", "active_lock_reason": null, "body": "i already install barcode module from official python site like \"pip install python-barcode\". but whenever i write a code on text editor like 1-Visual Studio 2-SubLime 3-Pycharm theirs an error pop up and it's says \"Unable to import 'barcode' pylint(input-error)[1,1]\" ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/62", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/62/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/62/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/62/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/62", "id": 570275720, "node_id": "MDU6SXNzdWU1NzAyNzU3MjA=", "number": 62, "title": "UnboundLocalError: local variable 'barcode' referenced before assignment", "user": {"login": "xuanduy1508", "id": 61442900, "node_id": "MDQ6VXNlcjYxNDQyOTAw", "avatar_url": "https://avatars0.githubusercontent.com/u/61442900?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xuanduy1508", "html_url": "https://github.com/xuanduy1508", "followers_url": "https://api.github.com/users/xuanduy1508/followers", "following_url": "https://api.github.com/users/xuanduy1508/following{/other_user}", "gists_url": "https://api.github.com/users/xuanduy1508/gists{/gist_id}", "starred_url": "https://api.github.com/users/xuanduy1508/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xuanduy1508/subscriptions", "organizations_url": "https://api.github.com/users/xuanduy1508/orgs", "repos_url": "https://api.github.com/users/xuanduy1508/repos", "events_url": "https://api.github.com/users/xuanduy1508/events{/privacy}", "received_events_url": "https://api.github.com/users/xuanduy1508/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2020-02-25T02:53:51Z", "updated_at": "2020-03-30T11:59:02Z", "closed_at": "2020-03-30T11:59:02Z", "author_association": "NONE", "active_lock_reason": null, "body": "![image](https://user-images.githubusercontent.com/61442900/75210783-ab6d0580-57b4-11ea-9718-9bb93cf2effb.png)\r\nhelp me pls. thanks.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/60", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/60/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/60/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/60/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/60", "id": 569724890, "node_id": "MDU6SXNzdWU1Njk3MjQ4OTA=", "number": 60, "title": "Inline svg does not need the doctype", "user": {"login": "Azd325", "id": 426541, "node_id": "MDQ6VXNlcjQyNjU0MQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/426541?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Azd325", "html_url": "https://github.com/Azd325", "followers_url": "https://api.github.com/users/Azd325/followers", "following_url": "https://api.github.com/users/Azd325/following{/other_user}", "gists_url": "https://api.github.com/users/Azd325/gists{/gist_id}", "starred_url": "https://api.github.com/users/Azd325/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Azd325/subscriptions", "organizations_url": "https://api.github.com/users/Azd325/orgs", "repos_url": "https://api.github.com/users/Azd325/repos", "events_url": "https://api.github.com/users/Azd325/events{/privacy}", "received_events_url": "https://api.github.com/users/Azd325/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 718363863, "node_id": "MDU6TGFiZWw3MTgzNjM4NjM=", "url": "https://api.github.com/repos/WhyNotHugo/python-barcode/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-02-24T09:16:37Z", "updated_at": "2020-08-10T18:20:48Z", "closed_at": "2020-08-10T18:20:48Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "If you use the svg output as inline svg in html the doctype declaration is not needed and could lead to problems.\r\n\r\nhttps://stackoverflow.com/a/38172170/548558", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/55", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/55/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/55/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/55/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/55", "id": 513044291, "node_id": "MDU6SXNzdWU1MTMwNDQyOTE=", "number": 55, "title": "When using an ImageWriter with 'Code39' the add_checksum option is ignored", "user": {"login": "srolin", "id": 8670893, "node_id": "MDQ6VXNlcjg2NzA4OTM=", "avatar_url": "https://avatars3.githubusercontent.com/u/8670893?v=4", "gravatar_id": "", "url": "https://api.github.com/users/srolin", "html_url": "https://github.com/srolin", "followers_url": "https://api.github.com/users/srolin/followers", "following_url": "https://api.github.com/users/srolin/following{/other_user}", "gists_url": "https://api.github.com/users/srolin/gists{/gist_id}", "starred_url": "https://api.github.com/users/srolin/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/srolin/subscriptions", "organizations_url": "https://api.github.com/users/srolin/orgs", "repos_url": "https://api.github.com/users/srolin/repos", "events_url": "https://api.github.com/users/srolin/events{/privacy}", "received_events_url": "https://api.github.com/users/srolin/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-10-28T00:21:15Z", "updated_at": "2020-02-25T01:22:18Z", "closed_at": "2020-02-25T01:22:18Z", "author_association": "NONE", "active_lock_reason": null, "body": "When using the generator function to create a 'Code39' barcode, the writer_options={'add_checksum': False} is ignored.\r\n\r\nThe addition of the check digit happens during the class __init__ which hasn't received the writer_options.\r\n\r\nI have a fix for this by moving the check into the render function and adding  an instance variable to track when it has been added.  (I wasn't sure if the render function could end up being called more than once and didn't want additional check digits adding.\r\n\r\nWill create a PR for the fix.\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/52", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/52/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/52/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/52/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/52", "id": 501493493, "node_id": "MDU6SXNzdWU1MDE0OTM0OTM=", "number": 52, "title": "can not install it in win10 or centos7", "user": {"login": "bbg221", "id": 15084748, "node_id": "MDQ6VXNlcjE1MDg0NzQ4", "avatar_url": "https://avatars2.githubusercontent.com/u/15084748?v=4", "gravatar_id": "", "url": "https://api.github.com/users/bbg221", "html_url": "https://github.com/bbg221", "followers_url": "https://api.github.com/users/bbg221/followers", "following_url": "https://api.github.com/users/bbg221/following{/other_user}", "gists_url": "https://api.github.com/users/bbg221/gists{/gist_id}", "starred_url": "https://api.github.com/users/bbg221/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/bbg221/subscriptions", "organizations_url": "https://api.github.com/users/bbg221/orgs", "repos_url": "https://api.github.com/users/bbg221/repos", "events_url": "https://api.github.com/users/bbg221/events{/privacy}", "received_events_url": "https://api.github.com/users/bbg221/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-10-02T13:35:27Z", "updated_at": "2020-02-25T01:21:42Z", "closed_at": "2020-02-25T01:21:42Z", "author_association": "NONE", "active_lock_reason": null, "body": "I download the code from the trunk line and install it  with 'python setup.py install'  into my win10 and centos7.  all of them are failed.\r\n \"ImportError: No module named pathlib\" is occurred first, after I fix it by 'pip install pathlib',  \r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \".\\setup.py\", line 17, in <module>\r\n    long_description=Path('README.rst').read_text(),\r\nAttributeError: 'WindowsPath' object has no attribute 'read_text'\r\n```  \r\noccurred in windows  and \r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"setup.py\", line 17, in <module>\r\n    long_description=Path('README.rst').read_text(),\r\nAttributeError: 'PosixPath' object has no attribute 'read_text'\r\n```\r\noccurred in centos7. \r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/46", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/46/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/46/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/46/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/46", "id": 479934728, "node_id": "MDU6SXNzdWU0Nzk5MzQ3Mjg=", "number": 46, "title": "TypeError: string argument expected, got 'bytes' ?", "user": {"login": "jekoie", "id": 6836400, "node_id": "MDQ6VXNlcjY4MzY0MDA=", "avatar_url": "https://avatars1.githubusercontent.com/u/6836400?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jekoie", "html_url": "https://github.com/jekoie", "followers_url": "https://api.github.com/users/jekoie/followers", "following_url": "https://api.github.com/users/jekoie/following{/other_user}", "gists_url": "https://api.github.com/users/jekoie/gists{/gist_id}", "starred_url": "https://api.github.com/users/jekoie/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jekoie/subscriptions", "organizations_url": "https://api.github.com/users/jekoie/orgs", "repos_url": "https://api.github.com/users/jekoie/repos", "events_url": "https://api.github.com/users/jekoie/events{/privacy}", "received_events_url": "https://api.github.com/users/jekoie/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-08-13T02:52:36Z", "updated_at": "2019-09-18T13:36:31Z", "closed_at": "2019-09-18T13:36:31Z", "author_association": "NONE", "active_lock_reason": null, "body": "the barcode run error in python3.6\r\n```\r\nimport barcode\r\nimport io\r\nfrom barcode.writer import ImageWriter\r\nimport traceback\r\n\r\nfp = io.StringIO()\r\nbarcode.generate('gs1_128', 'iloveyou', writer=ImageWriter(), output=fp)\r\n```\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\jekoie\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3326, in run_code\r\n    exec(code_obj, self.user_global_ns, self.user_ns)\r\n  File \"<ipython-input-14-aa318e8f6722>\", line 7, in <module>\r\n    barcode.generate('gs1_128', 'iloveyou', writer=ImageWriter(), output=fp)\r\n  File \"C:\\Users\\jekoie\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\barcode\\__init__.py\", line 80, in generate\r\n    barcode.write(output, options, text)\r\n  File \"C:\\Users\\jekoie\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\barcode\\base.py\", line 90, in write\r\n    output.save(fp, format=self.writer.format)\r\n  File \"C:\\Users\\jekoie\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\PIL\\Image.py\", line 2088, in save\r\n    save_handler(self, fp, filename)\r\n  File \"C:\\Users\\jekoie\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\PIL\\PngImagePlugin.py\", line 807, in _save\r\nTypeError: string argument expected, got 'bytes'\r\n\r\n**the python3.6 pillow treat raw code as bytes, but barcode treat as string, so it raise error?**\r\n**another issue is  how can i create a barcode only show graph without number under the graph??**", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/45", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/45/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/45/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/45/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/45", "id": 475346538, "node_id": "MDU6SXNzdWU0NzUzNDY1Mzg=", "number": 45, "title": "TypeError running commandline example", "user": {"login": "guxi798", "id": 6333749, "node_id": "MDQ6VXNlcjYzMzM3NDk=", "avatar_url": "https://avatars0.githubusercontent.com/u/6333749?v=4", "gravatar_id": "", "url": "https://api.github.com/users/guxi798", "html_url": "https://github.com/guxi798", "followers_url": "https://api.github.com/users/guxi798/followers", "following_url": "https://api.github.com/users/guxi798/following{/other_user}", "gists_url": "https://api.github.com/users/guxi798/gists{/gist_id}", "starred_url": "https://api.github.com/users/guxi798/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/guxi798/subscriptions", "organizations_url": "https://api.github.com/users/guxi798/orgs", "repos_url": "https://api.github.com/users/guxi798/repos", "events_url": "https://api.github.com/users/guxi798/events{/privacy}", "received_events_url": "https://api.github.com/users/guxi798/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 4, "created_at": "2019-07-31T20:39:19Z", "updated_at": "2020-02-25T01:14:51Z", "closed_at": "2020-02-25T01:14:51Z", "author_association": "NONE", "active_lock_reason": null, "body": "Running Python 3.6.5. I tested the command-line example with ended with the following error.\r\n`python-barcode create \"My Text\" outfile`\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"/anaconda3/bin/python-barcode\", line 10, in <module>\r\n    sys.exit(main())\r\n  File \"/anaconda3/lib/python3.6/site-packages/barcode/pybarcode.py\", line 119, in main\r\n    func(args, parser)\r\n  File \"/anaconda3/lib/python3.6/site-packages/barcode/pybarcode.py\", line 63, in create_barcode\r\n    args.text)\r\n  File \"/anaconda3/lib/python3.6/site-packages/barcode/__init__.py\", line 73, in generate\r\n    barcode = get(name, code, writer, options)\r\n  File \"/anaconda3/lib/python3.6/site-packages/barcode/__init__.py\", line 61, in get\r\n    return barcode(code, writer, **options)\r\nTypeError: __init__() got an unexpected keyword argument 'compress'\r\n```\r\n\r\nAny suggestions?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/42", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/42/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/42/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/42/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/42", "id": 460256679, "node_id": "MDU6SXNzdWU0NjAyNTY2Nzk=", "number": 42, "title": "Missing changelog for 0.10.0", "user": {"login": "pokoli", "id": 1160726, "node_id": "MDQ6VXNlcjExNjA3MjY=", "avatar_url": "https://avatars2.githubusercontent.com/u/1160726?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pokoli", "html_url": "https://github.com/pokoli", "followers_url": "https://api.github.com/users/pokoli/followers", "following_url": "https://api.github.com/users/pokoli/following{/other_user}", "gists_url": "https://api.github.com/users/pokoli/gists{/gist_id}", "starred_url": "https://api.github.com/users/pokoli/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pokoli/subscriptions", "organizations_url": "https://api.github.com/users/pokoli/orgs", "repos_url": "https://api.github.com/users/pokoli/repos", "events_url": "https://api.github.com/users/pokoli/events{/privacy}", "received_events_url": "https://api.github.com/users/pokoli/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2019-06-25T07:25:10Z", "updated_at": "2019-10-29T15:52:09Z", "closed_at": "2019-10-29T15:52:08Z", "author_association": "NONE", "active_lock_reason": null, "body": "I see version 0.10.0 has been uploaded to pypi but the changelog does not list the changes in this version. \r\n\r\nIIUC this release contains support for the gs1-128 barcodes. Does it? ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/40", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/40/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/40/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/40/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/40", "id": 454146418, "node_id": "MDU6SXNzdWU0NTQxNDY0MTg=", "number": 40, "title": "How to set parameter for svg \"width\"  and \"height\"", "user": {"login": "shangqianfang", "id": 48992290, "node_id": "MDQ6VXNlcjQ4OTkyMjkw", "avatar_url": "https://avatars3.githubusercontent.com/u/48992290?v=4", "gravatar_id": "", "url": "https://api.github.com/users/shangqianfang", "html_url": "https://github.com/shangqianfang", "followers_url": "https://api.github.com/users/shangqianfang/followers", "following_url": "https://api.github.com/users/shangqianfang/following{/other_user}", "gists_url": "https://api.github.com/users/shangqianfang/gists{/gist_id}", "starred_url": "https://api.github.com/users/shangqianfang/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/shangqianfang/subscriptions", "organizations_url": "https://api.github.com/users/shangqianfang/orgs", "repos_url": "https://api.github.com/users/shangqianfang/repos", "events_url": "https://api.github.com/users/shangqianfang/events{/privacy}", "received_events_url": "https://api.github.com/users/shangqianfang/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-06-10T12:29:57Z", "updated_at": "2020-02-25T01:12:01Z", "closed_at": "2020-02-25T01:12:01Z", "author_association": "NONE", "active_lock_reason": null, "body": "How to set parameter for svg \"width\"  and \"height\"? Thanks!", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/38", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/38/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/38/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/38/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/38", "id": 450926205, "node_id": "MDU6SXNzdWU0NTA5MjYyMDU=", "number": 38, "title": "Passing writer_options with generate()", "user": {"login": "ildarakhmetov", "id": 28851825, "node_id": "MDQ6VXNlcjI4ODUxODI1", "avatar_url": "https://avatars3.githubusercontent.com/u/28851825?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ildarakhmetov", "html_url": "https://github.com/ildarakhmetov", "followers_url": "https://api.github.com/users/ildarakhmetov/followers", "following_url": "https://api.github.com/users/ildarakhmetov/following{/other_user}", "gists_url": "https://api.github.com/users/ildarakhmetov/gists{/gist_id}", "starred_url": "https://api.github.com/users/ildarakhmetov/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ildarakhmetov/subscriptions", "organizations_url": "https://api.github.com/users/ildarakhmetov/orgs", "repos_url": "https://api.github.com/users/ildarakhmetov/repos", "events_url": "https://api.github.com/users/ildarakhmetov/events{/privacy}", "received_events_url": "https://api.github.com/users/ildarakhmetov/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2019-05-31T18:26:59Z", "updated_at": "2020-02-25T01:08:08Z", "closed_at": "2020-02-25T01:08:08Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm calling `generate()` function to create a code128 barcode, and I need to pass custom `writer_options` payload. Here is the code fragment:\r\n\r\n```\r\nwriter_options = {\r\n    'module_width': 0.3,\r\n    'module_height': 25.0,\r\n    'quiet_zone': 1,\r\n    'font_size': 10,\r\n    'text_distance': 0,\r\n    'background': 'white',\r\n    'foreground': 'black',\r\n    'write_text': True,\r\n    'text': '',\r\n}\r\nname = generate('code128', foo, output=f\"barcode_{foo}\", text=' ', writer=ImageWriter(), writer_options=writer_options)\r\n```\r\n\r\nThis code gives me the following error message:\r\n```\r\nTraceback (most recent call last):\r\n  File \"gen_barcode_foreign.py\", line 55, in <module>\r\n    name = generate('code128', tracking, output=f\"barcode_{tracking}\", text=' ', writer=ImageWriter(), writer_options=writer_options)\r\n  File \"d:\\python_test\\barcodes\\venv\\lib\\site-packages\\barcode\\__init__.py\", line 73, in generate\r\n    barcode = get(name, code, writer, options)\r\n  File \"d:\\python_test\\barcodes\\venv\\lib\\site-packages\\barcode\\__init__.py\", line 61, in get\r\n    return barcode(code, writer, **options)\r\nTypeError: __init__() got an unexpected keyword argument 'module_width'\r\n```\r\n\r\nI tried to edit `__init__.py`, changing the line #61 from `return barcode(code, writer, **options)` to `return barcode(code, writer)`, and it helped, `generate()` now works fine.\r\n\r\nNot sure if this is the correct way to solve this issue though.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/36", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/36/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/36/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/36/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/36", "id": 445140151, "node_id": "MDU6SXNzdWU0NDUxNDAxNTE=", "number": 36, "title": "ean-128/gs1-128 support?", "user": {"login": "adsad213", "id": 49121132, "node_id": "MDQ6VXNlcjQ5MTIxMTMy", "avatar_url": "https://avatars2.githubusercontent.com/u/49121132?v=4", "gravatar_id": "", "url": "https://api.github.com/users/adsad213", "html_url": "https://github.com/adsad213", "followers_url": "https://api.github.com/users/adsad213/followers", "following_url": "https://api.github.com/users/adsad213/following{/other_user}", "gists_url": "https://api.github.com/users/adsad213/gists{/gist_id}", "starred_url": "https://api.github.com/users/adsad213/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/adsad213/subscriptions", "organizations_url": "https://api.github.com/users/adsad213/orgs", "repos_url": "https://api.github.com/users/adsad213/repos", "events_url": "https://api.github.com/users/adsad213/events{/privacy}", "received_events_url": "https://api.github.com/users/adsad213/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 718363863, "node_id": "MDU6TGFiZWw3MTgzNjM4NjM=", "url": "https://api.github.com/repos/WhyNotHugo/python-barcode/labels/enhancement", "name": "enhancement", "color": "84b6eb", "default": true, "description": null}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 8, "created_at": "2019-05-16T20:16:06Z", "updated_at": "2019-05-24T09:00:43Z", "closed_at": "2019-05-24T09:00:43Z", "author_association": "NONE", "active_lock_reason": null, "body": "since gs1-128 is based on code128, could this possibly support it?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/34", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/34/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/34/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/34/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/34", "id": 439971703, "node_id": "MDU6SXNzdWU0Mzk5NzE3MDM=", "number": 34, "title": "no module name error", "user": {"login": "infocuitpro", "id": 50199146, "node_id": "MDQ6VXNlcjUwMTk5MTQ2", "avatar_url": "https://avatars0.githubusercontent.com/u/50199146?v=4", "gravatar_id": "", "url": "https://api.github.com/users/infocuitpro", "html_url": "https://github.com/infocuitpro", "followers_url": "https://api.github.com/users/infocuitpro/followers", "following_url": "https://api.github.com/users/infocuitpro/following{/other_user}", "gists_url": "https://api.github.com/users/infocuitpro/gists{/gist_id}", "starred_url": "https://api.github.com/users/infocuitpro/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/infocuitpro/subscriptions", "organizations_url": "https://api.github.com/users/infocuitpro/orgs", "repos_url": "https://api.github.com/users/infocuitpro/repos", "events_url": "https://api.github.com/users/infocuitpro/events{/privacy}", "received_events_url": "https://api.github.com/users/infocuitpro/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2019-05-03T09:51:56Z", "updated_at": "2019-09-18T13:37:27Z", "closed_at": "2019-09-18T13:37:27Z", "author_association": "NONE", "active_lock_reason": null, "body": "i am installed successfully the python-barcode packages. but i get the no moduled name error when i use the module. \r\n\"ModuleNotFoundError: No module named 'barcode'\"\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/29", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/29/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/29/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/29/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/29", "id": 422327480, "node_id": "MDU6SXNzdWU0MjIzMjc0ODA=", "number": 29, "title": "Option to suppress check digit?", "user": {"login": "Justin-E-Taylor", "id": 23110763, "node_id": "MDQ6VXNlcjIzMTEwNzYz", "avatar_url": "https://avatars0.githubusercontent.com/u/23110763?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Justin-E-Taylor", "html_url": "https://github.com/Justin-E-Taylor", "followers_url": "https://api.github.com/users/Justin-E-Taylor/followers", "following_url": "https://api.github.com/users/Justin-E-Taylor/following{/other_user}", "gists_url": "https://api.github.com/users/Justin-E-Taylor/gists{/gist_id}", "starred_url": "https://api.github.com/users/Justin-E-Taylor/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Justin-E-Taylor/subscriptions", "organizations_url": "https://api.github.com/users/Justin-E-Taylor/orgs", "repos_url": "https://api.github.com/users/Justin-E-Taylor/repos", "events_url": "https://api.github.com/users/Justin-E-Taylor/events{/privacy}", "received_events_url": "https://api.github.com/users/Justin-E-Taylor/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-03-18T16:53:28Z", "updated_at": "2019-05-23T21:32:15Z", "closed_at": "2019-05-23T21:32:15Z", "author_association": "NONE", "active_lock_reason": null, "body": "Is there an option to suppress the check digit?  I'm testing with the samples on the homepage, substituting in type code39, if that matters. \r\n\r\nTIA", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/27", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/27/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/27/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/27/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/27", "id": 414582640, "node_id": "MDU6SXNzdWU0MTQ1ODI2NDA=", "number": 27, "title": "I'm getting wrong barcodes", "user": {"login": "EnriqueSoria", "id": 7394684, "node_id": "MDQ6VXNlcjczOTQ2ODQ=", "avatar_url": "https://avatars1.githubusercontent.com/u/7394684?v=4", "gravatar_id": "", "url": "https://api.github.com/users/EnriqueSoria", "html_url": "https://github.com/EnriqueSoria", "followers_url": "https://api.github.com/users/EnriqueSoria/followers", "following_url": "https://api.github.com/users/EnriqueSoria/following{/other_user}", "gists_url": "https://api.github.com/users/EnriqueSoria/gists{/gist_id}", "starred_url": "https://api.github.com/users/EnriqueSoria/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/EnriqueSoria/subscriptions", "organizations_url": "https://api.github.com/users/EnriqueSoria/orgs", "repos_url": "https://api.github.com/users/EnriqueSoria/repos", "events_url": "https://api.github.com/users/EnriqueSoria/events{/privacy}", "received_events_url": "https://api.github.com/users/EnriqueSoria/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-02-26T12:17:08Z", "updated_at": "2019-03-11T07:36:09Z", "closed_at": "2019-03-11T07:36:09Z", "author_association": "NONE", "active_lock_reason": null, "body": "Is ist working? I'm getting wrong barcodes.\r\n\r\n![imagen](https://user-images.githubusercontent.com/7394684/53412051-8e96ca00-39c8-11e9-8a4b-54eb658fddd4.png)\r\n\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/25", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/25/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/25/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/25/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/25", "id": 413207152, "node_id": "MDU6SXNzdWU0MTMyMDcxNTI=", "number": 25, "title": "Example in readme does not function", "user": {"login": "lifekaizen", "id": 7156025, "node_id": "MDQ6VXNlcjcxNTYwMjU=", "avatar_url": "https://avatars1.githubusercontent.com/u/7156025?v=4", "gravatar_id": "", "url": "https://api.github.com/users/lifekaizen", "html_url": "https://github.com/lifekaizen", "followers_url": "https://api.github.com/users/lifekaizen/followers", "following_url": "https://api.github.com/users/lifekaizen/following{/other_user}", "gists_url": "https://api.github.com/users/lifekaizen/gists{/gist_id}", "starred_url": "https://api.github.com/users/lifekaizen/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/lifekaizen/subscriptions", "organizations_url": "https://api.github.com/users/lifekaizen/orgs", "repos_url": "https://api.github.com/users/lifekaizen/repos", "events_url": "https://api.github.com/users/lifekaizen/events{/privacy}", "received_events_url": "https://api.github.com/users/lifekaizen/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2019-02-22T01:59:11Z", "updated_at": "2019-02-22T14:21:47Z", "closed_at": "2019-02-22T14:21:47Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "This section:\r\n> Commandline:\r\n> `$ pybarcode create \"My Text\" outfile`\r\n> `New barcode saved as outfile.svg.`\r\n> `Try 'pybarcode -h' for help.`\r\n\r\nResults in the error `can't open file 'pybarcode'`:\r\n```\r\n$ python3 pybarcode create \"My Text\" outfile\r\n/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'pybarcode': [Errno 2] No such file or directory\r\n```\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/21", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/21/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/21/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/21/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/21", "id": 388586951, "node_id": "MDU6SXNzdWUzODg1ODY5NTE=", "number": 21, "title": "render barcode in pillow image", "user": {"login": "jeandebleau", "id": 22517950, "node_id": "MDQ6VXNlcjIyNTE3OTUw", "avatar_url": "https://avatars0.githubusercontent.com/u/22517950?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jeandebleau", "html_url": "https://github.com/jeandebleau", "followers_url": "https://api.github.com/users/jeandebleau/followers", "following_url": "https://api.github.com/users/jeandebleau/following{/other_user}", "gists_url": "https://api.github.com/users/jeandebleau/gists{/gist_id}", "starred_url": "https://api.github.com/users/jeandebleau/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jeandebleau/subscriptions", "organizations_url": "https://api.github.com/users/jeandebleau/orgs", "repos_url": "https://api.github.com/users/jeandebleau/repos", "events_url": "https://api.github.com/users/jeandebleau/events{/privacy}", "received_events_url": "https://api.github.com/users/jeandebleau/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-12-07T10:11:46Z", "updated_at": "2018-12-07T13:02:17Z", "closed_at": "2018-12-07T13:02:17Z", "author_association": "NONE", "active_lock_reason": null, "body": "Is there a simple example to render a barcode into a pillow image without saving it ? ", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/20", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/20/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/20/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/20/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/20", "id": 386427772, "node_id": "MDU6SXNzdWUzODY0Mjc3NzI=", "number": 20, "title": "random barcode  generating", "user": {"login": "Abhi561", "id": 40542635, "node_id": "MDQ6VXNlcjQwNTQyNjM1", "avatar_url": "https://avatars2.githubusercontent.com/u/40542635?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Abhi561", "html_url": "https://github.com/Abhi561", "followers_url": "https://api.github.com/users/Abhi561/followers", "following_url": "https://api.github.com/users/Abhi561/following{/other_user}", "gists_url": "https://api.github.com/users/Abhi561/gists{/gist_id}", "starred_url": "https://api.github.com/users/Abhi561/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Abhi561/subscriptions", "organizations_url": "https://api.github.com/users/Abhi561/orgs", "repos_url": "https://api.github.com/users/Abhi561/repos", "events_url": "https://api.github.com/users/Abhi561/events{/privacy}", "received_events_url": "https://api.github.com/users/Abhi561/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-12-01T06:03:53Z", "updated_at": "2019-01-24T04:25:32Z", "closed_at": "2019-01-24T04:25:31Z", "author_association": "NONE", "active_lock_reason": null, "body": "how to generate random barcodes using python", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/19", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/19/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/19/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/19/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/19", "id": 386427694, "node_id": "MDU6SXNzdWUzODY0Mjc2OTQ=", "number": 19, "title": "Random barcode generating", "user": {"login": "Abhi561", "id": 40542635, "node_id": "MDQ6VXNlcjQwNTQyNjM1", "avatar_url": "https://avatars2.githubusercontent.com/u/40542635?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Abhi561", "html_url": "https://github.com/Abhi561", "followers_url": "https://api.github.com/users/Abhi561/followers", "following_url": "https://api.github.com/users/Abhi561/following{/other_user}", "gists_url": "https://api.github.com/users/Abhi561/gists{/gist_id}", "starred_url": "https://api.github.com/users/Abhi561/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Abhi561/subscriptions", "organizations_url": "https://api.github.com/users/Abhi561/orgs", "repos_url": "https://api.github.com/users/Abhi561/repos", "events_url": "https://api.github.com/users/Abhi561/events{/privacy}", "received_events_url": "https://api.github.com/users/Abhi561/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2018-12-01T06:02:32Z", "updated_at": "2018-12-01T06:02:53Z", "closed_at": "2018-12-01T06:02:53Z", "author_association": "NONE", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/18", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/18/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/18/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/18/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/18", "id": 383694666, "node_id": "MDU6SXNzdWUzODM2OTQ2NjY=", "number": 18, "title": "Pip install does not include newer releases (Ubuntu; caps at v0.7)", "user": {"login": "ryantp", "id": 25127589, "node_id": "MDQ6VXNlcjI1MTI3NTg5", "avatar_url": "https://avatars3.githubusercontent.com/u/25127589?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ryantp", "html_url": "https://github.com/ryantp", "followers_url": "https://api.github.com/users/ryantp/followers", "following_url": "https://api.github.com/users/ryantp/following{/other_user}", "gists_url": "https://api.github.com/users/ryantp/gists{/gist_id}", "starred_url": "https://api.github.com/users/ryantp/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ryantp/subscriptions", "organizations_url": "https://api.github.com/users/ryantp/orgs", "repos_url": "https://api.github.com/users/ryantp/repos", "events_url": "https://api.github.com/users/ryantp/events{/privacy}", "received_events_url": "https://api.github.com/users/ryantp/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-11-23T03:30:54Z", "updated_at": "2018-11-23T13:38:05Z", "closed_at": "2018-11-23T03:32:25Z", "author_association": "NONE", "active_lock_reason": null, "body": "![screenshot from 2018-11-22 19-26-18](https://user-images.githubusercontent.com/25127589/48927670-b12abb80-ee8c-11e8-980c-c7b436882bd2.png)\r\n\r\n> after that sweet code128", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/16", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/16/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/16/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/16/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/16", "id": 372177956, "node_id": "MDU6SXNzdWUzNzIxNzc5NTY=", "number": 16, "title": "no such modules", "user": {"login": "mathachew7", "id": 31032095, "node_id": "MDQ6VXNlcjMxMDMyMDk1", "avatar_url": "https://avatars0.githubusercontent.com/u/31032095?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mathachew7", "html_url": "https://github.com/mathachew7", "followers_url": "https://api.github.com/users/mathachew7/followers", "following_url": "https://api.github.com/users/mathachew7/following{/other_user}", "gists_url": "https://api.github.com/users/mathachew7/gists{/gist_id}", "starred_url": "https://api.github.com/users/mathachew7/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mathachew7/subscriptions", "organizations_url": "https://api.github.com/users/mathachew7/orgs", "repos_url": "https://api.github.com/users/mathachew7/repos", "events_url": "https://api.github.com/users/mathachew7/events{/privacy}", "received_events_url": "https://api.github.com/users/mathachew7/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-10-20T06:04:56Z", "updated_at": "2018-10-20T21:10:10Z", "closed_at": "2018-10-20T21:09:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "what to do now ? as there is no such modules.\r\nI tried pip install pyBarcode but nothing happend\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/15", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/15/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/15/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/15/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/15", "id": 371905980, "node_id": "MDU6SXNzdWUzNzE5MDU5ODA=", "number": 15, "title": "So only generate barcode, can't read image to decode barcode ?", "user": {"login": "RicardoScofileld", "id": 33416599, "node_id": "MDQ6VXNlcjMzNDE2NTk5", "avatar_url": "https://avatars1.githubusercontent.com/u/33416599?v=4", "gravatar_id": "", "url": "https://api.github.com/users/RicardoScofileld", "html_url": "https://github.com/RicardoScofileld", "followers_url": "https://api.github.com/users/RicardoScofileld/followers", "following_url": "https://api.github.com/users/RicardoScofileld/following{/other_user}", "gists_url": "https://api.github.com/users/RicardoScofileld/gists{/gist_id}", "starred_url": "https://api.github.com/users/RicardoScofileld/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/RicardoScofileld/subscriptions", "organizations_url": "https://api.github.com/users/RicardoScofileld/orgs", "repos_url": "https://api.github.com/users/RicardoScofileld/repos", "events_url": "https://api.github.com/users/RicardoScofileld/events{/privacy}", "received_events_url": "https://api.github.com/users/RicardoScofileld/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-10-19T10:50:52Z", "updated_at": "2019-02-18T02:43:38Z", "closed_at": "2019-02-18T02:43:38Z", "author_association": "NONE", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/12", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/12/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/12/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/12/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/12", "id": 347388694, "node_id": "MDU6SXNzdWUzNDczODg2OTQ=", "number": 12, "title": "TypeError running # Example with PNG in usage guide", "user": {"login": "DannyDannyDanny", "id": 16453674, "node_id": "MDQ6VXNlcjE2NDUzNjc0", "avatar_url": "https://avatars0.githubusercontent.com/u/16453674?v=4", "gravatar_id": "", "url": "https://api.github.com/users/DannyDannyDanny", "html_url": "https://github.com/DannyDannyDanny", "followers_url": "https://api.github.com/users/DannyDannyDanny/followers", "following_url": "https://api.github.com/users/DannyDannyDanny/following{/other_user}", "gists_url": "https://api.github.com/users/DannyDannyDanny/gists{/gist_id}", "starred_url": "https://api.github.com/users/DannyDannyDanny/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/DannyDannyDanny/subscriptions", "organizations_url": "https://api.github.com/users/DannyDannyDanny/orgs", "repos_url": "https://api.github.com/users/DannyDannyDanny/repos", "events_url": "https://api.github.com/users/DannyDannyDanny/events{/privacy}", "received_events_url": "https://api.github.com/users/DannyDannyDanny/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 9, "created_at": "2018-08-03T13:05:17Z", "updated_at": "2019-07-22T15:45:49Z", "closed_at": "2018-08-19T23:05:19Z", "author_association": "NONE", "active_lock_reason": null, "body": "I'm running Python 3.5.5. A subsection of the usage guide:\r\n```python\r\nimport barcode\r\nfrom barcode.writer import ImageWriter\r\nEAN = barcode.get_barcode_class('code128')\r\nean = EAN(u'5901234123457', writer=ImageWriter())\r\n```\r\n\r\n ...gives me the following error:\r\n```\r\n---------------------------------------------------------------------------\r\nTypeError                                 Traceback (most recent call last)\r\n<ipython-input-67-21778fac1b87> in <module>()\r\n----> 1 ean = EAN(u'5901234123457', writer=ImageWriter())\r\n\r\nTypeError: 'NoneType' object is not callable\r\n```\r\nAm I doing something wrong?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/10", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/10/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/10/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/10/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/10", "id": 332415336, "node_id": "MDU6SXNzdWUzMzI0MTUzMzY=", "number": 10, "title": "Code39 and Code128 Missing kwarg Default", "user": {"login": "JoshMayberry", "id": 11482252, "node_id": "MDQ6VXNlcjExNDgyMjUy", "avatar_url": "https://avatars2.githubusercontent.com/u/11482252?v=4", "gravatar_id": "", "url": "https://api.github.com/users/JoshMayberry", "html_url": "https://github.com/JoshMayberry", "followers_url": "https://api.github.com/users/JoshMayberry/followers", "following_url": "https://api.github.com/users/JoshMayberry/following{/other_user}", "gists_url": "https://api.github.com/users/JoshMayberry/gists{/gist_id}", "starred_url": "https://api.github.com/users/JoshMayberry/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/JoshMayberry/subscriptions", "organizations_url": "https://api.github.com/users/JoshMayberry/orgs", "repos_url": "https://api.github.com/users/JoshMayberry/repos", "events_url": "https://api.github.com/users/JoshMayberry/events{/privacy}", "received_events_url": "https://api.github.com/users/JoshMayberry/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-06-14T13:58:07Z", "updated_at": "2018-06-14T16:46:22Z", "closed_at": "2018-06-14T16:46:22Z", "author_association": "NONE", "active_lock_reason": null, "body": "For barcodes that are not code39 and code128, the user is able to call the render function without specifying 'writer_options'. This is because that argument is set equal to None by default in 'base.py'\r\n\r\nHowever, in 'codex.py', both classes Code39 and Code128 override render(), but do not set 'writer_options' equal to None by default.\r\n\r\nProposed Change: Use `def render(self, writer_options=None, text=None):` instead of `def render(self, writer_options, text=None):` for Code39 and Code128.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/9", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/9/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/9/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/9/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/9", "id": 325493526, "node_id": "MDU6SXNzdWUzMjU0OTM1MjY=", "number": 9, "title": "Installation on Windows fails", "user": {"login": "josephernest", "id": 6168083, "node_id": "MDQ6VXNlcjYxNjgwODM=", "avatar_url": "https://avatars0.githubusercontent.com/u/6168083?v=4", "gravatar_id": "", "url": "https://api.github.com/users/josephernest", "html_url": "https://github.com/josephernest", "followers_url": "https://api.github.com/users/josephernest/followers", "following_url": "https://api.github.com/users/josephernest/following{/other_user}", "gists_url": "https://api.github.com/users/josephernest/gists{/gist_id}", "starred_url": "https://api.github.com/users/josephernest/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/josephernest/subscriptions", "organizations_url": "https://api.github.com/users/josephernest/orgs", "repos_url": "https://api.github.com/users/josephernest/repos", "events_url": "https://api.github.com/users/josephernest/events{/privacy}", "received_events_url": "https://api.github.com/users/josephernest/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-05-22T23:05:37Z", "updated_at": "2018-07-26T19:42:53Z", "closed_at": "2018-07-26T19:42:24Z", "author_association": "NONE", "active_lock_reason": null, "body": "On Windows 7 x64, Python 2.7 64-bit, \r\n\r\n    pip install python-barcode\r\n\r\ngives\r\n\r\n      Traceback (most recent call last):\r\n      File \"<string>\", line 1, in <module>\r\n      File \"c:\\users\\blah\\appdata\\local\\temp\\pip-build-q_pfeu\\python-barcode\\se\r\n      tup.py\", line 18, in <module>\r\n      long_description=Path('README.rst').read_text(),\r\n      AttributeError: 'WindowsPath' object has no attribute 'read_text'\r\n\r\nWould you have any idea?\r\n\r\nThank you in advance.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/8", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/8/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/8/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/8/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/8", "id": 325113282, "node_id": "MDU6SXNzdWUzMjUxMTMyODI=", "number": 8, "title": "Using 'raw' without using 'save' gives no output", "user": {"login": "sharifanani", "id": 11825589, "node_id": "MDQ6VXNlcjExODI1NTg5", "avatar_url": "https://avatars2.githubusercontent.com/u/11825589?v=4", "gravatar_id": "", "url": "https://api.github.com/users/sharifanani", "html_url": "https://github.com/sharifanani", "followers_url": "https://api.github.com/users/sharifanani/followers", "following_url": "https://api.github.com/users/sharifanani/following{/other_user}", "gists_url": "https://api.github.com/users/sharifanani/gists{/gist_id}", "starred_url": "https://api.github.com/users/sharifanani/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/sharifanani/subscriptions", "organizations_url": "https://api.github.com/users/sharifanani/orgs", "repos_url": "https://api.github.com/users/sharifanani/repos", "events_url": "https://api.github.com/users/sharifanani/events{/privacy}", "received_events_url": "https://api.github.com/users/sharifanani/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 6, "created_at": "2018-05-22T01:48:54Z", "updated_at": "2018-07-26T19:54:08Z", "closed_at": "2018-07-26T19:54:08Z", "author_association": "NONE", "active_lock_reason": null, "body": "I think the title explains it all.\r\n\r\nIf I try to use .raw to server an SVG barcode without using .save first, I get an empty output...\r\n\r\nExample:\r\nTrying to serve this in my django project:\r\n\r\n```\r\nclass APIBarcode(View):\r\n\r\n    def get(self, request, *args, **kwargs):\r\n        uuid = request.GET.get('uuid')\r\n        C39 = barcode.get_barcode_class('code39')\r\n        toserve = C39(uuid)\r\n        toserve.save('c39code')\r\n        return HttpResponse(toserve.raw, content_type=\"image/svg+xml\")\r\n```\r\n\r\nGives the following output:\r\n![image](https://user-images.githubusercontent.com/11825589/40337929-a858c8a6-5d2f-11e8-891b-fa7ecdcf632c.png)\r\n\r\nBut serving this:\r\n```\r\nclass APIBarcode(View):\r\n\r\n    def get(self, request, *args, **kwargs):\r\n        uuid = request.GET.get('uuid')\r\n        C39 = barcode.get_barcode_class('code39')\r\n        toserve = C39(uuid)\r\n        # toserve.save('c39code')\r\n        return HttpResponse(toserve.raw, content_type=\"image/svg+xml\")\r\n```\r\nGives the following output:\r\n\r\n![image](https://user-images.githubusercontent.com/11825589/40337973-e869d9e4-5d2f-11e8-9045-3b01c3cee5d2.png)\r\n\r\n\r\nIf someone can point me to where I should be looking I would gladly attempt to fix it!", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/6", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/6/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/6/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/6/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/6", "id": 315233781, "node_id": "MDU6SXNzdWUzMTUyMzM3ODE=", "number": 6, "title": "Commandline usage fails with, AttributeError: module 'barcode' has no attribute '__description__'", "user": {"login": "jakkanen", "id": 2806166, "node_id": "MDQ6VXNlcjI4MDYxNjY=", "avatar_url": "https://avatars0.githubusercontent.com/u/2806166?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jakkanen", "html_url": "https://github.com/jakkanen", "followers_url": "https://api.github.com/users/jakkanen/followers", "following_url": "https://api.github.com/users/jakkanen/following{/other_user}", "gists_url": "https://api.github.com/users/jakkanen/gists{/gist_id}", "starred_url": "https://api.github.com/users/jakkanen/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jakkanen/subscriptions", "organizations_url": "https://api.github.com/users/jakkanen/orgs", "repos_url": "https://api.github.com/users/jakkanen/repos", "events_url": "https://api.github.com/users/jakkanen/events{/privacy}", "received_events_url": "https://api.github.com/users/jakkanen/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2018-04-17T21:01:00Z", "updated_at": "2018-05-11T17:40:17Z", "closed_at": "2018-05-11T17:40:17Z", "author_association": "NONE", "active_lock_reason": null, "body": "Installed python-barcode with, `pip3.6 install python-barcode`\r\nCommand-line usage fails as follows:\r\n```$ python-barcode -h\r\nTraceback (most recent call last):\r\n  File \"/usr/local/bin/python-barcode\", line 11, in <module>\r\n    sys.exit(main())\r\n  File \"/usr/local/lib/python3.6/site-packages/barcode/pybarcode.py\", line 82, in main\r\n    description=barcode.__description__, epilog=' '.join(msg)\r\nAttributeError: module 'barcode' has no attribute '__description__'```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/5", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/5/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/5/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/5/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/5", "id": 308167277, "node_id": "MDU6SXNzdWUzMDgxNjcyNzc=", "number": 5, "title": "Comment doesn't display package version", "user": {"login": "henniss", "id": 17056237, "node_id": "MDQ6VXNlcjE3MDU2MjM3", "avatar_url": "https://avatars3.githubusercontent.com/u/17056237?v=4", "gravatar_id": "", "url": "https://api.github.com/users/henniss", "html_url": "https://github.com/henniss", "followers_url": "https://api.github.com/users/henniss/followers", "following_url": "https://api.github.com/users/henniss/following{/other_user}", "gists_url": "https://api.github.com/users/henniss/gists{/gist_id}", "starred_url": "https://api.github.com/users/henniss/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/henniss/subscriptions", "organizations_url": "https://api.github.com/users/henniss/orgs", "repos_url": "https://api.github.com/users/henniss/repos", "events_url": "https://api.github.com/users/henniss/events{/privacy}", "received_events_url": "https://api.github.com/users/henniss/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-03-23T20:22:05Z", "updated_at": "2018-05-11T17:30:12Z", "closed_at": "2018-05-11T17:30:12Z", "author_association": "NONE", "active_lock_reason": null, "body": "When I write a Code128 barcode in Python3, I get the following:\r\n\r\n```\r\n<svg height=\"23.000mm\" version=\"1.1\" width=\"29.000mm\" xmlns=\"http://www.w3.org/2000/svg\">\r\n    <!--Autogenerated with python-barcode <module 'barcode.version' from '[...]/lib/python3.6/site-packages/barcode/version.py'>-->\r\n    <g id=\"barcode_group\">...\r\n```\r\n\r\nIt should probably be more like\r\n```\r\n<svg height=\"23.000mm\" version=\"1.1\" width=\"29.000mm\" xmlns=\"http://www.w3.org/2000/svg\">\r\n    <!--Autogenerated with python-barcode v0.8.1-->\r\n    <g id=\"barcode_group\">...\r\n```\r\n\r\nThe problem seems to be that `from barcode import version` on line 9 of `barcode.writer` imports the `barcode.version` module, rather than importing the version object from `barcode.__init__`.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/3", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/3/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/3/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/3/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/3", "id": 300133429, "node_id": "MDU6SXNzdWUzMDAxMzM0Mjk=", "number": 3, "title": "Ean-128 is not supporting", "user": {"login": "thameemstud", "id": 8832804, "node_id": "MDQ6VXNlcjg4MzI4MDQ=", "avatar_url": "https://avatars1.githubusercontent.com/u/8832804?v=4", "gravatar_id": "", "url": "https://api.github.com/users/thameemstud", "html_url": "https://github.com/thameemstud", "followers_url": "https://api.github.com/users/thameemstud/followers", "following_url": "https://api.github.com/users/thameemstud/following{/other_user}", "gists_url": "https://api.github.com/users/thameemstud/gists{/gist_id}", "starred_url": "https://api.github.com/users/thameemstud/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/thameemstud/subscriptions", "organizations_url": "https://api.github.com/users/thameemstud/orgs", "repos_url": "https://api.github.com/users/thameemstud/repos", "events_url": "https://api.github.com/users/thameemstud/events{/privacy}", "received_events_url": "https://api.github.com/users/thameemstud/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-02-26T07:26:24Z", "updated_at": "2019-05-23T14:09:14Z", "closed_at": "2019-05-23T14:09:14Z", "author_association": "NONE", "active_lock_reason": null, "body": "", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/1", "repository_url": "https://api.github.com/repos/WhyNotHugo/python-barcode", "labels_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/1/labels{/name}", "comments_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/1/comments", "events_url": "https://api.github.com/repos/WhyNotHugo/python-barcode/issues/1/events", "html_url": "https://github.com/WhyNotHugo/python-barcode/issues/1", "id": 286328729, "node_id": "MDU6SXNzdWUyODYzMjg3Mjk=", "number": 1, "title": "How to read the barcodes?", "user": {"login": "mayurpande", "id": 6522456, "node_id": "MDQ6VXNlcjY1MjI0NTY=", "avatar_url": "https://avatars3.githubusercontent.com/u/6522456?v=4", "gravatar_id": "", "url": "https://api.github.com/users/mayurpande", "html_url": "https://github.com/mayurpande", "followers_url": "https://api.github.com/users/mayurpande/followers", "following_url": "https://api.github.com/users/mayurpande/following{/other_user}", "gists_url": "https://api.github.com/users/mayurpande/gists{/gist_id}", "starred_url": "https://api.github.com/users/mayurpande/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/mayurpande/subscriptions", "organizations_url": "https://api.github.com/users/mayurpande/orgs", "repos_url": "https://api.github.com/users/mayurpande/repos", "events_url": "https://api.github.com/users/mayurpande/events{/privacy}", "received_events_url": "https://api.github.com/users/mayurpande/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2018-01-05T15:59:24Z", "updated_at": "2018-01-10T00:08:47Z", "closed_at": "2018-01-10T00:08:47Z", "author_association": "NONE", "active_lock_reason": null, "body": "This looks like what I need. However if I wanted to scan this barcode and read into my program to see what it is, is this possible?", "performed_via_github_app": null, "score": 1.0}]}