{"total_count": 11, "incomplete_results": false, "items": [{"url": "https://api.github.com/repos/dashea/requests-file/issues/20", "repository_url": "https://api.github.com/repos/dashea/requests-file", "labels_url": "https://api.github.com/repos/dashea/requests-file/issues/20/labels{/name}", "comments_url": "https://api.github.com/repos/dashea/requests-file/issues/20/comments", "events_url": "https://api.github.com/repos/dashea/requests-file/issues/20/events", "html_url": "https://github.com/dashea/requests-file/issues/20", "id": 618485306, "node_id": "MDU6SXNzdWU2MTg0ODUzMDY=", "number": 20, "title": "Bug : requests-file not supporting web framework errors - leads to xss vulnerability", "user": {"login": "knassar702", "id": 45688522, "node_id": "MDQ6VXNlcjQ1Njg4NTIy", "avatar_url": "https://avatars3.githubusercontent.com/u/45688522?v=4", "gravatar_id": "", "url": "https://api.github.com/users/knassar702", "html_url": "https://github.com/knassar702", "followers_url": "https://api.github.com/users/knassar702/followers", "following_url": "https://api.github.com/users/knassar702/following{/other_user}", "gists_url": "https://api.github.com/users/knassar702/gists{/gist_id}", "starred_url": "https://api.github.com/users/knassar702/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/knassar702/subscriptions", "organizations_url": "https://api.github.com/users/knassar702/orgs", "repos_url": "https://api.github.com/users/knassar702/repos", "events_url": "https://api.github.com/users/knassar702/events{/privacy}", "received_events_url": "https://api.github.com/users/knassar702/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2020-05-14T19:34:54Z", "updated_at": "2020-05-17T12:57:29Z", "closed_at": "2020-05-17T12:57:29Z", "author_association": "NONE", "active_lock_reason": null, "body": "##### _if you have any error in python web frameworks, the server will be send (500 : internal error error) in the response without print the error name or code_ **(without debugging Mode)**\r\n<h5> here im using requests module to send http request</h5>\r\n\r\n ### _with error_ : \r\n#### you can't find the errors in your code (without debugging Mode)\r\n* Error in Flask Framework\r\n![errr](https://user-images.githubusercontent.com/45688522/81969979-134a2400-961f-11ea-801b-ae0f820ae3c5.png)\r\n* Error in tornado Framework\r\n![ter_err](https://user-images.githubusercontent.com/45688522/81975116-d8e48500-9626-11ea-8ad0-15371de0283a.png)\r\n\r\n### without error  : \r\n* Flask Framework\r\n![without_errr](https://user-images.githubusercontent.com/45688522/81970134-51474800-961f-11ea-9d15-3da784345035.png)\r\n\r\n* tornado Framework\r\n![ter_no](https://user-images.githubusercontent.com/45688522/81975236-029dac00-9627-11ea-9e68-6d2687a970be.png)\r\n\r\n## but in requests-file it's so different \r\n## with error : \r\n* Flask Framework\r\n![err_req](https://user-images.githubusercontent.com/45688522/81970562-04b03c80-9620-11ea-9bd9-8a9862c539e4.png)\r\n\r\n* tornado Framework\r\n![ter_err_f](https://user-images.githubusercontent.com/45688522/81975529-7770e600-9627-11ea-8ef2-a09ba914a1a8.png)\r\n#### this not a secure for the app :X \r\n### now the attacker can be use this error for XSS Attacks because The error was printed on the page without any filter\r\n* Flask Framework\r\n![xss_req](https://user-images.githubusercontent.com/45688522/81970957-9b7cf900-9620-11ea-853c-69afff0dfd32.png)\r\n* tornado Framework\r\n![ter_xss](https://user-images.githubusercontent.com/45688522/81976549-fdd9f780-9628-11ea-9be7-e45e157a205b.png)\r\n\r\nhmmm let's try to add xss payload in requests like requests-file\r\n* Flask Framework\r\n![no_xss](https://user-images.githubusercontent.com/45688522/81976742-4a253780-9629-11ea-84a8-f4103d0b3e54.png)\r\n* tornado Framework\r\n![ter_no_xss](https://user-images.githubusercontent.com/45688522/81976867-72ad3180-9629-11ea-9353-3a5e01e19295.png)\r\n\r\nwhy i can't find any xss like requests-file .?\r\n * because requests module supporting web errors not like requests-file\r\n## impact : \r\n**now All requests-file users(web dev) are vulnerable to this attack (XSS),With the help of xss a hacker or attacker can perform social engineering on users by redirecting them from real website to fake one.\r\nhacker can steal their cookies and download a malware on their system, and there are many more attacking scenarios a skilled attacker can perform with xss.**\r\n### Video : https://youtu.be/oxp_cE0qPeU\r\n### Web Lab's : https://github.com/knassar702/theproject\r\n### About xss : https://owasp.org/www-community/attacks/xss/\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/dashea/requests-file/issues/17", "repository_url": "https://api.github.com/repos/dashea/requests-file", "labels_url": "https://api.github.com/repos/dashea/requests-file/issues/17/labels{/name}", "comments_url": "https://api.github.com/repos/dashea/requests-file/issues/17/comments", "events_url": "https://api.github.com/repos/dashea/requests-file/issues/17/events", "html_url": "https://github.com/dashea/requests-file/issues/17", "id": 606059495, "node_id": "MDU6SXNzdWU2MDYwNTk0OTU=", "number": 17, "title": "Latest version 1.5 not longer compatible with python 2.7", "user": {"login": "andresp99999", "id": 1036725, "node_id": "MDQ6VXNlcjEwMzY3MjU=", "avatar_url": "https://avatars0.githubusercontent.com/u/1036725?v=4", "gravatar_id": "", "url": "https://api.github.com/users/andresp99999", "html_url": "https://github.com/andresp99999", "followers_url": "https://api.github.com/users/andresp99999/followers", "following_url": "https://api.github.com/users/andresp99999/following{/other_user}", "gists_url": "https://api.github.com/users/andresp99999/gists{/gist_id}", "starred_url": "https://api.github.com/users/andresp99999/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/andresp99999/subscriptions", "organizations_url": "https://api.github.com/users/andresp99999/orgs", "repos_url": "https://api.github.com/users/andresp99999/repos", "events_url": "https://api.github.com/users/andresp99999/events{/privacy}", "received_events_url": "https://api.github.com/users/andresp99999/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2020-04-24T05:50:39Z", "updated_at": "2020-04-25T13:58:15Z", "closed_at": "2020-04-25T13:58:14Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello,\r\n\r\n  We just noticed that the most recent version upgrade included a line that is not compatible with Python 2.7. This is a stacktrace of the error when trying to use it from tldextract.\r\n\r\n```\r\n>>> \r\n>>> import tldextract\r\n>>> tldextract.extract('xx.com')\r\nTraceback (most recent call last):\r\n  File \"<stdin>\", line 1, in <module>\r\n  File \"tldextract/tldextract.py\", line 303, in extract\r\n    return TLD_EXTRACTOR(url)\r\n  File \"tldextract/tldextract.py\", line 183, in __call__\r\n    suffix_index = self._get_tld_extractor().suffix_index(translations)\r\n  File \"tldextract/tldextract.py\", line 223, in _get_tld_extractor\r\n    raw_suffix_list_data = find_first_response(self.suffix_list_urls)\r\n  File \"tldextract/remote.py\", line 37, in find_first_response\r\n    session.mount('file://', FileAdapter())\r\n  File \"requests_file.py\", line 14, in __init__\r\n    super().__init__()\r\nTypeError: super() takes at least 1 argument (0 given)\r\n```\r\n\r\nAs a quick workaround we created a fork and pushed this change: https://github.com/AirPR/requests-file/commit/d9c580ef250aaf708eb48b48c302a92d7f63dcf6 (this was affecting a prod system).\r\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/dashea/requests-file/issues/15", "repository_url": "https://api.github.com/repos/dashea/requests-file", "labels_url": "https://api.github.com/repos/dashea/requests-file/issues/15/labels{/name}", "comments_url": "https://api.github.com/repos/dashea/requests-file/issues/15/comments", "events_url": "https://api.github.com/repos/dashea/requests-file/issues/15/events", "html_url": "https://github.com/dashea/requests-file/issues/15", "id": 528178436, "node_id": "MDU6SXNzdWU1MjgxNzg0MzY=", "number": 15, "title": "FileAdapter does not properly close FileIO resources", "user": {"login": "stevendlander", "id": 3169732, "node_id": "MDQ6VXNlcjMxNjk3MzI=", "avatar_url": "https://avatars1.githubusercontent.com/u/3169732?v=4", "gravatar_id": "", "url": "https://api.github.com/users/stevendlander", "html_url": "https://github.com/stevendlander", "followers_url": "https://api.github.com/users/stevendlander/followers", "following_url": "https://api.github.com/users/stevendlander/following{/other_user}", "gists_url": "https://api.github.com/users/stevendlander/gists{/gist_id}", "starred_url": "https://api.github.com/users/stevendlander/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/stevendlander/subscriptions", "organizations_url": "https://api.github.com/users/stevendlander/orgs", "repos_url": "https://api.github.com/users/stevendlander/repos", "events_url": "https://api.github.com/users/stevendlander/events{/privacy}", "received_events_url": "https://api.github.com/users/stevendlander/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2019-11-25T15:57:02Z", "updated_at": "2020-05-16T02:22:39Z", "closed_at": "2020-05-16T02:22:39Z", "author_association": "NONE", "active_lock_reason": null, "body": "When opening local files using the FileAdapter in requests, the following `ResourceWarning` is thrown during unit tests:\r\n\r\n```\r\nResourceWarning: unclosed file <_io.FileIO name='/Users/my_user/Projects/my_project/path/to/my/data/big_data_list.dat' mode='rb' closefd=True>\r\n```\r\nThis is happening on Python 3.7.4 interpreter.  Converting the [response object](https://github.com/dashea/requests-file/blob/master/requests_file.py#L31) to an instance variable, and then calling `self._resp.raw.close()` within the [FileAdapter.close()](https://github.com/dashea/requests-file/blob/master/requests_file.py#L109) method resolves this problem.\r\n\r\nI can submit a pull request, if needed.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/dashea/requests-file/issues/13", "repository_url": "https://api.github.com/repos/dashea/requests-file", "labels_url": "https://api.github.com/repos/dashea/requests-file/issues/13/labels{/name}", "comments_url": "https://api.github.com/repos/dashea/requests-file/issues/13/comments", "events_url": "https://api.github.com/repos/dashea/requests-file/issues/13/events", "html_url": "https://github.com/dashea/requests-file/issues/13", "id": 336397342, "node_id": "MDU6SXNzdWUzMzYzOTczNDI=", "number": 13, "title": "Unable to open relative paths", "user": {"login": "smokes2345", "id": 903008, "node_id": "MDQ6VXNlcjkwMzAwOA==", "avatar_url": "https://avatars3.githubusercontent.com/u/903008?v=4", "gravatar_id": "", "url": "https://api.github.com/users/smokes2345", "html_url": "https://github.com/smokes2345", "followers_url": "https://api.github.com/users/smokes2345/followers", "following_url": "https://api.github.com/users/smokes2345/following{/other_user}", "gists_url": "https://api.github.com/users/smokes2345/gists{/gist_id}", "starred_url": "https://api.github.com/users/smokes2345/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/smokes2345/subscriptions", "organizations_url": "https://api.github.com/users/smokes2345/orgs", "repos_url": "https://api.github.com/users/smokes2345/repos", "events_url": "https://api.github.com/users/smokes2345/events{/privacy}", "received_events_url": "https://api.github.com/users/smokes2345/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-06-27T21:41:27Z", "updated_at": "2018-07-23T14:54:41Z", "closed_at": "2018-07-23T14:54:41Z", "author_association": "NONE", "active_lock_reason": null, "body": "How would I access relative paths?\r\n\r\n>>> session.mount('file://', FileAdapter())\r\n>>> session.get('file:///./some_sort_of.yaml')\r\n<Response [404]>\r\n>>>", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/dashea/requests-file/issues/12", "repository_url": "https://api.github.com/repos/dashea/requests-file", "labels_url": "https://api.github.com/repos/dashea/requests-file/issues/12/labels{/name}", "comments_url": "https://api.github.com/repos/dashea/requests-file/issues/12/comments", "events_url": "https://api.github.com/repos/dashea/requests-file/issues/12/events", "html_url": "https://github.com/dashea/requests-file/issues/12", "id": 286489458, "node_id": "MDU6SXNzdWUyODY0ODk0NTg=", "number": 12, "title": "missing tag?", "user": {"login": "anarcat", "id": 796623, "node_id": "MDQ6VXNlcjc5NjYyMw==", "avatar_url": "https://avatars3.githubusercontent.com/u/796623?v=4", "gravatar_id": "", "url": "https://api.github.com/users/anarcat", "html_url": "https://github.com/anarcat", "followers_url": "https://api.github.com/users/anarcat/followers", "following_url": "https://api.github.com/users/anarcat/following{/other_user}", "gists_url": "https://api.github.com/users/anarcat/gists{/gist_id}", "starred_url": "https://api.github.com/users/anarcat/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/anarcat/subscriptions", "organizations_url": "https://api.github.com/users/anarcat/orgs", "repos_url": "https://api.github.com/users/anarcat/repos", "events_url": "https://api.github.com/users/anarcat/events{/privacy}", "received_events_url": "https://api.github.com/users/anarcat/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2018-01-06T14:53:50Z", "updated_at": "2018-01-08T13:59:00Z", "closed_at": "2018-01-08T13:58:59Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Hi!\r\n\r\nI'm trying to package the new 1.4.3 release that showed up on PyPI, but I don't see a tag here... I assume d57a6a0c10ed3d67b014bd2f1896f38cf98565ad is the right commit?", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/dashea/requests-file/issues/11", "repository_url": "https://api.github.com/repos/dashea/requests-file", "labels_url": "https://api.github.com/repos/dashea/requests-file/issues/11/labels{/name}", "comments_url": "https://api.github.com/repos/dashea/requests-file/issues/11/comments", "events_url": "https://api.github.com/repos/dashea/requests-file/issues/11/events", "html_url": "https://github.com/dashea/requests-file/issues/11", "id": 284580169, "node_id": "MDU6SXNzdWUyODQ1ODAxNjk=", "number": 11, "title": "Can't make deb package from sources.", "user": {"login": "Lamberk", "id": 8708878, "node_id": "MDQ6VXNlcjg3MDg4Nzg=", "avatar_url": "https://avatars0.githubusercontent.com/u/8708878?v=4", "gravatar_id": "", "url": "https://api.github.com/users/Lamberk", "html_url": "https://github.com/Lamberk", "followers_url": "https://api.github.com/users/Lamberk/followers", "following_url": "https://api.github.com/users/Lamberk/following{/other_user}", "gists_url": "https://api.github.com/users/Lamberk/gists{/gist_id}", "starred_url": "https://api.github.com/users/Lamberk/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/Lamberk/subscriptions", "organizations_url": "https://api.github.com/users/Lamberk/orgs", "repos_url": "https://api.github.com/users/Lamberk/repos", "events_url": "https://api.github.com/users/Lamberk/events{/privacy}", "received_events_url": "https://api.github.com/users/Lamberk/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 0, "created_at": "2017-12-26T16:37:27Z", "updated_at": "2018-01-02T21:16:57Z", "closed_at": "2018-01-02T21:16:57Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hi! I am trying to make deb package from sources and one test is failed.\r\n```\r\nsudo pypi-install requests-file\r\n-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-\r\nrunning the following command in directory: deb_dist/tmp_py2dsc/requests-file-1.4.2\r\n/usr/bin/python setup.py --command-packages stdeb.command sdist_dsc --dist-dir=/tmp/tmpZooboQ/deb_dist --use-premade-distfile=/tmp/tmpZooboQ/requests-file-1.4.2.tar.gz bdist_deb\r\n-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-\r\nrunning sdist_dsc\r\nrunning egg_info\r\nwriting requirements to requests_file.egg-info/requires.txt\r\nwriting requests_file.egg-info/PKG-INFO\r\nwriting top-level names to requests_file.egg-info/top_level.txt\r\nwriting dependency_links to requests_file.egg-info/dependency_links.txt\r\nreading manifest file 'requests_file.egg-info/SOURCES.txt'\r\nreading manifest template 'MANIFEST.in'\r\nwriting manifest file 'requests_file.egg-info/SOURCES.txt'\r\nCALLING dpkg-source -b requests-file-1.4.2 requests-file_1.4.2.orig.tar.gz (in dir /tmp/tmpZooboQ/deb_dist)\r\ndpkg-source: info: using source format '3.0 (quilt)'\r\ndpkg-source: info: building requests-file using existing ./requests-file_1.4.2.orig.tar.gz\r\ndpkg-source: info: building requests-file in requests-file_1.4.2-1.debian.tar.xz\r\ndpkg-source: info: building requests-file in requests-file_1.4.2-1.dsc\r\ndpkg-buildpackage: warning: using a gain-root-command while being root\r\ndpkg-buildpackage: source package requests-file\r\ndpkg-buildpackage: source version 1.4.2-1\r\ndpkg-buildpackage: source distribution unstable\r\ndpkg-buildpackage: source changed by David Shea <dshea@redhat.com>\r\n dpkg-source --before-build requests-file-1.4.2\r\n fakeroot debian/rules clean\r\ndh clean --with python2 --buildsystem=pybuild\r\n   dh_testdir -O--buildsystem=pybuild\r\n   dh_auto_clean -O--buildsystem=pybuild\r\nI: pybuild base:184: python2.7 setup.py clean \r\nrunning clean\r\nremoving '/tmp/tmpZooboQ/deb_dist/requests-file-1.4.2/.pybuild/pythonX.Y_2.7/build' (and everything under it)\r\n'build/bdist.linux-x86_64' does not exist -- can't clean it\r\n'build/scripts-2.7' does not exist -- can't clean it\r\n   dh_clean -O--buildsystem=pybuild\r\n dpkg-source -b requests-file-1.4.2\r\ndpkg-source: info: using source format '3.0 (quilt)'\r\ndpkg-source: info: building requests-file using existing ./requests-file_1.4.2.orig.tar.gz\r\ndpkg-source: info: building requests-file in requests-file_1.4.2-1.debian.tar.xz\r\ndpkg-source: info: building requests-file in requests-file_1.4.2-1.dsc\r\n dpkg-genchanges -S -sa >../requests-file_1.4.2-1_source.changes\r\ndpkg-genchanges: including full source code in upload\r\n dpkg-source --after-build requests-file-1.4.2\r\ndpkg-buildpackage: full upload (original source is included)\r\ndpkg-source: warning: extracting unsigned source package (requests-file_1.4.2-1.dsc)\r\ndpkg-source: info: extracting requests-file in requests-file-1.4.2\r\ndpkg-source: info: unpacking requests-file_1.4.2.orig.tar.gz\r\ndpkg-source: info: unpacking requests-file_1.4.2-1.debian.tar.xz\r\nrunning bdist_deb\r\ndpkg-buildpackage: warning: using a gain-root-command while being root\r\ndpkg-buildpackage: source package requests-file\r\ndpkg-buildpackage: source version 1.4.2-1\r\ndpkg-buildpackage: source distribution unstable\r\ndpkg-buildpackage: source changed by David Shea <dshea@redhat.com>\r\ndpkg-buildpackage: host architecture amd64\r\n dpkg-source --before-build requests-file-1.4.2\r\n fakeroot debian/rules clean\r\ndh clean --with python2 --buildsystem=pybuild\r\n   dh_testdir -O--buildsystem=pybuild\r\n   dh_auto_clean -O--buildsystem=pybuild\r\nI: pybuild base:184: python2.7 setup.py clean \r\nrunning clean\r\nremoving '/tmp/tmpZooboQ/deb_dist/requests-file-1.4.2/.pybuild/pythonX.Y_2.7/build' (and everything under it)\r\n'build/bdist.linux-x86_64' does not exist -- can't clean it\r\n'build/scripts-2.7' does not exist -- can't clean it\r\n   dh_clean -O--buildsystem=pybuild\r\n debian/rules build\r\ndh build --with python2 --buildsystem=pybuild\r\n   dh_testdir -O--buildsystem=pybuild\r\n   dh_update_autotools_config -O--buildsystem=pybuild\r\n   dh_auto_configure -O--buildsystem=pybuild\r\nI: pybuild base:184: python2.7 setup.py config \r\nrunning config\r\n   dh_auto_build -O--buildsystem=pybuild\r\nI: pybuild base:184: /usr/bin/python setup.py build \r\nrunning build\r\nrunning build_py\r\ncopying requests_file.py -> /tmp/tmpZooboQ/deb_dist/requests-file-1.4.2/.pybuild/pythonX.Y_2.7/build\r\n   dh_auto_test -O--buildsystem=pybuild\r\nI: pybuild base:184: python2.7 setup.py test \r\nrunning test\r\nrunning egg_info\r\nwriting requirements to requests_file.egg-info/requires.txt\r\nwriting requests_file.egg-info/PKG-INFO\r\nwriting top-level names to requests_file.egg-info/top_level.txt\r\nwriting dependency_links to requests_file.egg-info/dependency_links.txt\r\nreading manifest file 'requests_file.egg-info/SOURCES.txt'\r\nreading manifest template 'MANIFEST.in'\r\nwriting manifest file 'requests_file.egg-info/SOURCES.txt'\r\nrunning build_ext\r\ntest_close (tests.FileRequestTestCase) ... ok\r\ntest_fetch_missing (tests.FileRequestTestCase) ... ok\r\ntest_fetch_missing_localized (tests.FileRequestTestCase) ... ok\r\ntest_fetch_no_access (tests.FileRequestTestCase) ... FAIL\r\ntest_fetch_nonlocal (tests.FileRequestTestCase) ... ok\r\ntest_fetch_post (tests.FileRequestTestCase) ... ok\r\ntest_fetch_regular (tests.FileRequestTestCase) ... ok\r\ntest_funny_names (tests.FileRequestTestCase) ... ok\r\ntest_head (tests.FileRequestTestCase) ... ok\r\ntest_missing_close (tests.FileRequestTestCase) ... ok\r\ntest_windows_legacy (tests.FileRequestTestCase)\r\nTest |-encoded drive characters on Windows ... skipped 'skipping windows URL test'\r\n\r\n======================================================================\r\nFAIL: test_fetch_no_access (tests.FileRequestTestCase)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/tmp/tmpZooboQ/deb_dist/requests-file-1.4.2/tests/__init__.py\", line 60, in test_fetch_no_access\r\n    self.assertEqual(response.status_code, requests.codes.forbidden)\r\nAssertionError: 200 != 403\r\n\r\n----------------------------------------------------------------------\r\nRan 11 tests in 0.023s\r\n```", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/dashea/requests-file/issues/10", "repository_url": "https://api.github.com/repos/dashea/requests-file", "labels_url": "https://api.github.com/repos/dashea/requests-file/issues/10/labels{/name}", "comments_url": "https://api.github.com/repos/dashea/requests-file/issues/10/comments", "events_url": "https://api.github.com/repos/dashea/requests-file/issues/10/events", "html_url": "https://github.com/dashea/requests-file/issues/10", "id": 266960640, "node_id": "MDU6SXNzdWUyNjY5NjA2NDA=", "number": 10, "title": "debian packaging", "user": {"login": "anarcat", "id": 796623, "node_id": "MDQ6VXNlcjc5NjYyMw==", "avatar_url": "https://avatars3.githubusercontent.com/u/796623?v=4", "gravatar_id": "", "url": "https://api.github.com/users/anarcat", "html_url": "https://github.com/anarcat", "followers_url": "https://api.github.com/users/anarcat/followers", "following_url": "https://api.github.com/users/anarcat/following{/other_user}", "gists_url": "https://api.github.com/users/anarcat/gists{/gist_id}", "starred_url": "https://api.github.com/users/anarcat/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/anarcat/subscriptions", "organizations_url": "https://api.github.com/users/anarcat/orgs", "repos_url": "https://api.github.com/users/anarcat/repos", "events_url": "https://api.github.com/users/anarcat/events{/privacy}", "received_events_url": "https://api.github.com/users/anarcat/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-10-19T19:29:25Z", "updated_at": "2017-10-19T20:30:02Z", "closed_at": "2017-10-19T20:30:02Z", "author_association": "CONTRIBUTOR", "active_lock_reason": null, "body": "Hi,\r\n\r\nFor your information, I am working on packaging this library for debian. You can follow the progress of this effort in [#879125](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=879125) on the Debian BTS. if you are interested in maintaining the package yourself upstream, that's also a possibility, especially if you are a debian maintainer or developer. if not, I can also act as a sponsor when a new release is published.\r\n\r\nThis is just a notification, but can also act as a coordination point for upstream packaging if you wish to followup on this. otherwise, feel free to close this issue whenever you like.\r\n\r\nThank you for your attention.", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/dashea/requests-file/issues/5", "repository_url": "https://api.github.com/repos/dashea/requests-file", "labels_url": "https://api.github.com/repos/dashea/requests-file/issues/5/labels{/name}", "comments_url": "https://api.github.com/repos/dashea/requests-file/issues/5/comments", "events_url": "https://api.github.com/repos/dashea/requests-file/issues/5/events", "html_url": "https://github.com/dashea/requests-file/issues/5", "id": 185107370, "node_id": "MDU6SXNzdWUxODUxMDczNzA=", "number": 5, "title": "Use requests-file on windows (automatically created file paths)", "user": {"login": "LeKono", "id": 22174607, "node_id": "MDQ6VXNlcjIyMTc0NjA3", "avatar_url": "https://avatars1.githubusercontent.com/u/22174607?v=4", "gravatar_id": "", "url": "https://api.github.com/users/LeKono", "html_url": "https://github.com/LeKono", "followers_url": "https://api.github.com/users/LeKono/followers", "following_url": "https://api.github.com/users/LeKono/following{/other_user}", "gists_url": "https://api.github.com/users/LeKono/gists{/gist_id}", "starred_url": "https://api.github.com/users/LeKono/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/LeKono/subscriptions", "organizations_url": "https://api.github.com/users/LeKono/orgs", "repos_url": "https://api.github.com/users/LeKono/repos", "events_url": "https://api.github.com/users/LeKono/events{/privacy}", "received_events_url": "https://api.github.com/users/LeKono/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2016-10-25T12:46:34Z", "updated_at": "2016-11-14T15:24:55Z", "closed_at": "2016-11-14T15:24:55Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hey guys, \n\nI am building paths in my test files automaticaly using `os.sep`. If I build paths to files they are created with a `\\`. Later in the code I use the `FileAdapter`. The problem here is: It decodes all paths with `/` so the automatically created windows paths will not be decoded propperly and raise an Exception.\n\nRegards,\nKono\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/dashea/requests-file/issues/3", "repository_url": "https://api.github.com/repos/dashea/requests-file", "labels_url": "https://api.github.com/repos/dashea/requests-file/issues/3/labels{/name}", "comments_url": "https://api.github.com/repos/dashea/requests-file/issues/3/comments", "events_url": "https://api.github.com/repos/dashea/requests-file/issues/3/events", "html_url": "https://github.com/dashea/requests-file/issues/3", "id": 162123736, "node_id": "MDU6SXNzdWUxNjIxMjM3MzY=", "number": 3, "title": "Name file include spec symbol not correct parse.", "user": {"login": "xiva-wgt", "id": 9335978, "node_id": "MDQ6VXNlcjkzMzU5Nzg=", "avatar_url": "https://avatars2.githubusercontent.com/u/9335978?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xiva-wgt", "html_url": "https://github.com/xiva-wgt", "followers_url": "https://api.github.com/users/xiva-wgt/followers", "following_url": "https://api.github.com/users/xiva-wgt/following{/other_user}", "gists_url": "https://api.github.com/users/xiva-wgt/gists{/gist_id}", "starred_url": "https://api.github.com/users/xiva-wgt/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xiva-wgt/subscriptions", "organizations_url": "https://api.github.com/users/xiva-wgt/orgs", "repos_url": "https://api.github.com/users/xiva-wgt/repos", "events_url": "https://api.github.com/users/xiva-wgt/events{/privacy}", "received_events_url": "https://api.github.com/users/xiva-wgt/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2016-06-24T10:57:30Z", "updated_at": "2016-06-24T12:26:38Z", "closed_at": "2016-06-24T12:26:38Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello!\nSample local url 'url = 'file:///C:/blabla/ru.plus.launcher_2.0_TESTBUILD#5_4_minAPI14.apk''\nSpecial characters available in the file name https://support.microsoft.com/en-us/kb/177506 section \"MORE INFORMATION\"\n'#' good symbol\n\npath_parts = [unquote(p) for p in url_parts.path.split('/')]\n\nreplace to\n\nurl_parts_path = url_parts.path\nif url_parts.fragment:\n    url_parts_path += '#' + url_parts.fragment\npath_parts = [unquote(p) for p in url_parts_path.path.split('/')]\n\nthanks in advance, best regards\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/dashea/requests-file/issues/2", "repository_url": "https://api.github.com/repos/dashea/requests-file", "labels_url": "https://api.github.com/repos/dashea/requests-file/issues/2/labels{/name}", "comments_url": "https://api.github.com/repos/dashea/requests-file/issues/2/comments", "events_url": "https://api.github.com/repos/dashea/requests-file/issues/2/events", "html_url": "https://github.com/dashea/requests-file/issues/2", "id": 97711526, "node_id": "MDU6SXNzdWU5NzcxMTUyNg==", "number": 2, "title": "Please made adapter cross-platform - a variant solution in ticket.", "user": {"login": "xiva-wgt", "id": 9335978, "node_id": "MDQ6VXNlcjkzMzU5Nzg=", "avatar_url": "https://avatars2.githubusercontent.com/u/9335978?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xiva-wgt", "html_url": "https://github.com/xiva-wgt", "followers_url": "https://api.github.com/users/xiva-wgt/followers", "following_url": "https://api.github.com/users/xiva-wgt/following{/other_user}", "gists_url": "https://api.github.com/users/xiva-wgt/gists{/gist_id}", "starred_url": "https://api.github.com/users/xiva-wgt/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xiva-wgt/subscriptions", "organizations_url": "https://api.github.com/users/xiva-wgt/orgs", "repos_url": "https://api.github.com/users/xiva-wgt/repos", "events_url": "https://api.github.com/users/xiva-wgt/events{/privacy}", "received_events_url": "https://api.github.com/users/xiva-wgt/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 2, "created_at": "2015-07-28T13:46:55Z", "updated_at": "2015-08-24T18:56:09Z", "closed_at": "2015-08-24T18:55:05Z", "author_association": "NONE", "active_lock_reason": null, "body": "file-adapter don't download on windows.\nif 'path_parts = [unquote(p) for p in url_parts.path.split('/')]'\nreplace to\n'drive, filepath = os.path.splitdrive(url_parts.path)\npath_parts = [unquote(p) for p in filepath.replace('\\\\', '/').split('/')]'\nand\n'path_parts[0] = os.sep'\nreplace to\n'path_parts[0] = drive + os.sep'\nfile-adapter work on windows and unix-like system.\nthanks in advance, best regards\n", "performed_via_github_app": null, "score": 1.0}, {"url": "https://api.github.com/repos/dashea/requests-file/issues/1", "repository_url": "https://api.github.com/repos/dashea/requests-file", "labels_url": "https://api.github.com/repos/dashea/requests-file/issues/1/labels{/name}", "comments_url": "https://api.github.com/repos/dashea/requests-file/issues/1/comments", "events_url": "https://api.github.com/repos/dashea/requests-file/issues/1/events", "html_url": "https://github.com/dashea/requests-file/issues/1", "id": 97699535, "node_id": "MDU6SXNzdWU5NzY5OTUzNQ==", "number": 1, "title": "Error Windows 7 x64 python 2.7.8", "user": {"login": "xiva-wgt", "id": 9335978, "node_id": "MDQ6VXNlcjkzMzU5Nzg=", "avatar_url": "https://avatars2.githubusercontent.com/u/9335978?v=4", "gravatar_id": "", "url": "https://api.github.com/users/xiva-wgt", "html_url": "https://github.com/xiva-wgt", "followers_url": "https://api.github.com/users/xiva-wgt/followers", "following_url": "https://api.github.com/users/xiva-wgt/following{/other_user}", "gists_url": "https://api.github.com/users/xiva-wgt/gists{/gist_id}", "starred_url": "https://api.github.com/users/xiva-wgt/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/xiva-wgt/subscriptions", "organizations_url": "https://api.github.com/users/xiva-wgt/orgs", "repos_url": "https://api.github.com/users/xiva-wgt/repos", "events_url": "https://api.github.com/users/xiva-wgt/events{/privacy}", "received_events_url": "https://api.github.com/users/xiva-wgt/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2015-07-28T12:54:10Z", "updated_at": "2015-08-24T18:55:05Z", "closed_at": "2015-08-24T18:55:05Z", "author_association": "NONE", "active_lock_reason": null, "body": "Hello!\nError Windows 7 x64 python 2.7.8\n\nError Windows 7 x64 python 2.7.8\n    resp_str = str(e).encode(locale.nl_langinfo(locale.CODESET))\nAttributeError: 'module' object has no attribute 'nl_langinfo'\n\nmaybe better to use '.encode(locale.getpreferredencoding())' to resolve this error?\n", "performed_via_github_app": null, "score": 1.0}]}